### ISSUE TITLE
Add example:  `with-create-react-app`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#118]
## Description

Add the simplest possible example of how to use this library with [create react app](https://github.com/facebook/create-react-app).

This issue is open to anyone and could serve as a fun introduction to `remirror` 😄 

Examples are located within the `support/examples` directory.

**Comment by aarongreenlee** [comment]
I tried to make this work today and had some challenges. The TypeScript config seemed to be one of the issues. Ultimately, I copied the social and wysiwyg examples and ended up with storybook components that could not apply state changes. Typing a key resulted in a stuttering with the keystrokes briefly showing before being removed. It was as if the component was controlled. I manually reproduced the razzel example without trouble.

**Comment by ifiokjr** [comment]
@aarongreenlee thanks for looking into this. I completely missed this message under a barrage of github notifications. I'll look into the issue over the weekend.

**Comment by aarongreenlee** [comment]
To support `create-react-app` the way we use the emotion dependency will need to change for any components we want to make importable into an editor being assembled in `create-react-app`. 

Specifically, the styles will need to be converted to use the `styled.div` format (similar to styled-components) or we'll have to use the JSX Pragma method ([see docs](https://emotion.sh/docs/css-prop)).

> Set the jsx pragma at the top of your source file that uses the `css` prop. This option works best for testing out the css prop feature or in projects where the babel configuration is not configurable (create-react-app, codesandbox, etc.).

Without making this change the `css` prop will render as `[object Object]`.

**Comment by ifiokjr** [comment]
This may have become more difficult. I've switched over to `pnpm`, which uses  symlinks, for the package manager. I think `create-react-app` struggles with symlinks. Maybe I'll create an examples' repository instead.
