### ISSUE TITLE
getHTML lost br tag

### ISSUE THREAD

**Issue by shaodahong** [remirror/remirror#1189]
### Steps to reproduce
1. enter and use `getHTML`
2. output string not container `<br>`

### Expected results
container `<br>`

### Actual results
not container `<br>`

**Comment by ocavue** [comment]
By default, `enter` will not create `<br>` but create a new `<p>` instead. If you want `<br>`, make sure you have `HardBreakExtension` and then press `shift-enter`.


https://user-images.githubusercontent.com/24715727/131691827-4105cc1c-f54f-4e18-a8b8-5c3eacca666d.mov

Notice that the result from `getHTML` is not equal to the actual DOM element in your editor. ProseMirror may add some extra things in the actual DOM element for better browser compatibility.
