### ISSUE TITLE
TaskList toggle button crashes editor when cursor is placed in task list

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1197]
### Steps to reproduce

1. Open editor with toggle menu button for `toggleTaskList`, e.g. https://remirror.vercel.app/?path=/story/editors-social--basic
2. Add a task list, e.g. via toggle menu button (or enter `[ ]`)

The same happens when adding a bullet or ordered list node to the document. It doesn't happen if there is no toggle button for `toggleTaskList`.

https://user-images.githubusercontent.com/9339055/131669582-eaa8e48d-1c47-4d1b-a9cf-3d3e92fe9715.mov

### Expected results

Task list is added

### Actual results

Editor crashes

![image](https://user-images.githubusercontent.com/9339055/131668870-80c50c19-0da8-47a5-9cbd-1ed7e9c94b2e.png)

### Possible Solution

The error is caused by `list-commands.deepChangeListType`: https://github.com/remirror/remirror/blob/4d5b617b29a30bf3728b4e3ab738db2e7b244d19/packages/remirror__extension-list/src/list-commands.ts#L347

I suspect the issue is that the toggle menu button calls `toggleTaskList` to check if it could be executed (i.e. to disable the button or not) but the code actually tries to change the document.

I don't really understand why this happens only for task lists but not for bullet or ordered lists.

**Comment by whawker** [comment]
Following on from [discussions on discord](https://discord.com/channels/726035064831344711/745695521305526302/882613024958083072).

Seems a fix can be applied in commands extension to ensure **unchained** commands always use a fresh transaction, which fixes this bug.

Changed here: https://github.com/remirror/remirror/blob/5ae9a8151d6792a1107c229eec70ec366d707936/packages/remirror__core/src/builtins/commands-extension.ts#L1136
```diff
- return command(...args)({ state, dispatch, view, tr: this.transaction });
+ return command(...args)({ state, dispatch, view, tr: state.tr });
```

This breaks some tests, namely [this one](https://github.com/remirror/remirror/blob/main/packages/remirror__react-core/__tests__/controlled.spec.tsx#L322-L325) and [this one](https://github.com/remirror/remirror/blob/main/packages/remirror__react-core/__tests__/core.spec.tsx#L386-L390) but running these scenarios for real in Storybook, **both cases do work as expected**, so there must be an issue in the test runner.
