### ISSUE TITLE
Add extraAttrs to nodes and marks in core-extensions

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#123]
## Description

Add `extraAttrs` functionality to the node and mark extensions within the `@remirror/core-extensions` library.

The option allows users to customise the recognised attrs without having to extend or create a new extension.

This is a great way to dive into the library and learn more about remirror. 

## Possible Implementation

See this commit (https://github.com/ifiokjr/remirror/pull/122/commits/ca0da7df6b813c8c98b05f684d424574d93a0561) for how the functionality was added to both the header, link and paragraph extensions.

**Comment by charlex** [comment]
This might satisfy this: https://github.com/ifiokjr/remirror/issues/111#issue-470717126

**Comment by jhnsnc** [comment]
This appears to be complete unless you want to make simple marks like bold, code, italic, strike, and underline extensible with `extraAttrs`.

**Comment by ifiokjr** [comment]
This has now been addressed in the `next` branch. 

The `createNodeSpec` and `createMarkSpec` methods of the `NodeExtension` and `MarkExtension` classes each receive a  parameter that should be used  to add the extra attributes in the right place. 

If you don't apply the attributes when creating an extension an error will be thrown. To avoid this error you can set the static property `disableExtraAttributes` of the extension to `true`.

Here is an example extension using the new API. 

https://github.com/remirror/remirror/blob/4dbeac48b824b94290797bc0be067f13766a0767/%40remirror/extension-bold/src/bold-extension.ts#L42-L77
