### ISSUE TITLE
Toggle from ordered to task list throws RangeError

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1237]
### Summary

With latest Remirror version (v1.0.23), toggling an ordered list to a task list crashes the editor.

### Steps to reproduce

1. Open reproduction case: https://codesandbox.io/s/remirror-basic-alignment-forked-12u5e?file=/src/Editor/index.js
2. Click on [Ordered] button to create ordered list
3. Click on [Task] to toggle list to task list

https://user-images.githubusercontent.com/9339055/133218727-358bfd20-550b-4c25-89eb-dcbe272f129f.mov

### Expected results

Editor contains a task list

### Actual results

Editor crashes with:
![image](https://user-images.githubusercontent.com/9339055/133218420-166480e4-56f8-457c-ac47-a5661aaf1f63.png)

**Comment by ronnyroeller** [comment]
@ocavue #1239 indeed removed the RangeError but now I can't change ordered lists to task task (and vice-versa). CodeSandbox doesn't have remirror:v1.0.24 so far but here is a screencast from running the codesandbox locally (https://codesandbox.io/s/remirror-basic-alignment-forked-12u5e?file=/src/Editor/index.js): 

https://user-images.githubusercontent.com/9339055/133566185-e8b8fd34-b334-41b5-a62d-a30651cd9bab.mov

**Comment by ocavue** [comment]
@ronnyroeller I will check it

**Comment by ronnyroeller** [comment]
In our app (which has more extensions), I see now this error when adding a task list:

![image](https://user-images.githubusercontent.com/9339055/133566590-b462d2af-f45e-4450-a331-69cf3433c29d.png)

I'm trying to find a minimal reproduction case for it.

**Comment by ocavue** [comment]
@ronnyroeller I can't reproduce your video with codesandbox, after I update `remirror` to `1.0.24` and saved `package.json`.

**Comment by ocavue** [comment]
@ronnyroeller Could you also check if you have two versions of `@remirror/extension-list` in your `yarn.lock`?

**Comment by ronnyroeller** [comment]
You were right, ocavue. Reinstalling the dependencies solved the sandbox isse.
The "Applying a mismatched transaction" is still there. Trying to find a minimal reproduction case for that one now.

**Comment by ronnyroeller** [comment]
Closing this ticket. The "Applying a mismatched transaction" error was caused by debouncing commands.
