### ISSUE TITLE
Input rules don't allow to convert task list to bullet list

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1249]
### Summary

Input rules allow to convert a bullet list into a task list but the reverse is not not possible.

### Steps to reproduce

1. Use editor on remirror.io homepage
2. Enter `[ ]` to create a task list
3. Enter `* ` in the task list item

https://user-images.githubusercontent.com/9339055/134172706-b2da0c8a-1e76-4ab5-8e14-3af3dcbf0cce.mov

### Expected results

Task list becomes a bullet lists.

### Actual results

Task list stays a task list.

**Comment by ankon** [comment]
For the record: The same behavior also happens with enumerated lists, where I would expect `1.` to switch to an enumeration.
