### ISSUE TITLE
List items don't handle tabs

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1258]
### Summary

Pressing tab in a list delegates the handling to the browser, which leads to list item losing focus (I've also seen tab characters being inserted into the text).

### Steps to reproduce

1. Open storybook for list extension: https://remirror.vercel.app/?path=/story/extensions-list--basic
2. Place cursor in second row
3. Press tab key -> this increases indention as expected
4. Press again tab key

https://user-images.githubusercontent.com/9339055/134498623-ece7dec4-e4d5-4c39-9fb5-2ab6d4932691.mov

### Expected results

Indention is further increased (Google Docs has this behavior) or tab key is ignored (Notion has this behavior).

### Actual results

List item loses focus

**Comment by ocavue** [comment]
> Indention is further increased (Google Docs has this behavior) or tab key is ignored (Notion has this behavior).

We can't simply increase indention because HTML structure (`<ul>`, `<li>`) doesn't allow this. Google Docs can do this because they use `<div>`.

Ignoring tab key should be possible. I'll look into it.
