### ISSUE TITLE
Backspace doesn't convert list item to paragraph (2nd line)

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#1264]
### Summary

Using backspace in a list item doesn't convert a list item to a non-list item but keeps the line in the list. 

### Steps to reproduce

1. Open the list demo: https://remirror.vercel.app/?path=/story/extensions-list--basic
2. Create a bullet list (or another type of list)
3. Enter some text and press enter -> This create a second bullet
4. Press backspace in the second bullet item

https://user-images.githubusercontent.com/9339055/134898026-3c41f474-ef63-45b7-8f5e-f34c4544e255.mov

### Expected results

Second bullet item becomes a normal paragraph.

### Actual results

The second line doesn't show the bullet but is still indented.

**Comment by ocavue** [comment]
I believe this is expected behavior since both MS Word and Google Docs has the same action:

https://user-images.githubusercontent.com/24715727/136132566-df5d202b-1b85-44a2-9b88-5ddd5d4f7dfa.mp4

**Comment by ronnyroeller** [comment]
> I believe this is expected behavior since both MS Word and Google Docs has the same action:

I think this works for Google Docs because pressing Backspace the second time converts the list item into a paragraph. This means there is a way to easily add a paragraph at the end of a list. For Remirror, that's not the case because the second Backspace removes the line - i.e. the user still doesn't have a paragraph after the list.

**Comment by ocavue** [comment]
> I think this works for Google Docs because pressing Backspace the second time converts the list item into a paragraph.

Agree. 

The current behavior is extended from ProseMirror, which makes it difficult to modify. You can see that remirror and  https://prosemirror.net/examples/basic/ have the same behavior.

For now, you can press Enter (instead of Backspace) to create a new paragraph after the list.

**Comment by whawker** [comment]
I believe this issue has been resolved. I can no longer reproduce it

**Comment by juliankrispel** [comment]
Hey folks, I've just written [a blog post about this](https://jkrsp.com/blog/prosemirror-backspace-problem/) and have released a little [backspace handler on npm](https://www.npmjs.com/package/prosemirror-better-backspace), hoping it helps!
