### ISSUE TITLE
@remirror/pm/state browser exports point to the wrong files

### ISSUE THREAD

**Issue by mtfoley** [remirror/remirror#1387]
### Discussed in https://github.com/remirror/remirror/discussions/1386

<div type='discussions-op-text'>

<sup>Originally posted by **mtfoley** November 23, 2021</sup>
I am trying to update https://github.com/open-sauced/open-sauced to use snowpack instead of webpack.  One of the things I have run into is that I think this package.json file points to the wrong resources for its nested exports of "browser".

https://github.com/remirror/remirror/blob/3d62a9b937e48169fbe8c13871f882bfac74832f/packages/remirror__pm/package.json#L25-L28

This appears to be typical of multiple nested exports, but I think the one above for "browser" should point to "./collab/dist/remirror-pm-collab.browser.esm.js". Right now, these point to files not found in the dist directories installed by NPM.

cc @0-vortex @bdougie</div>

**Comment by ocavue** [comment]
Thank you for reporting it. I'll fix it now.

**Comment by ocavue** [comment]
This should be fixed in the latest version. For example:

![image](https://user-images.githubusercontent.com/24715727/143106004-2518d8c0-0bc8-4e12-86da-4a8b1992e6ee.png)
