### ISSUE TITLE
Issue when restoring saved markup of resizable ImageExtension 

### ISSUE THREAD

**Issue by BFriedrichs** [remirror/remirror#1388]
### Summary

The width and height of resized images aren't properly loaded. Setting the width and height works perfectly fine and appear in the markup but Remirror doesn't interpret the values perfectly. 

### Steps to reproduce

1.  Load ImageExtension with `enableResizing` set to true.
2. Resize an image and save the resulting markup
3. Reload the page (or editor) with the saved markup, the image will now be back to default dimensions

### Expected results

After reloading, the editor should have restored the image dimensions properly.

### Actual results

The image dimensions are reset

### Possible Solution

Disclaimer, I'm on Chrome MacOS so some of the handling there might be different.

I think the fix is rather simple.
The image extension saves the width and height into the elements attributes.
In the ImageExtensions `getDimensions` the `width` and `height` get initialised using `element.style` and then, if they don't exist, chained with `??` to retrieve the element attributes. The problem being that `element.style` doesn't have `null` or `undefined` as values but rather an empty string `""`. Which means the `??` operator (working as intended) skips the rest of the evaluation. I suggest either prioritising the elements attributes to begin with (simply moving it to the start of the chain), changing the check to utilise `||` or safeguarding against this in some other way.

Relevant code passage:
https://github.com/remirror/remirror/blob/7775e6c4fe1139c43a78c4b0e4084609d0a899b2/packages/remirror__extension-image/src/image-extension.ts#L284-L286

**Comment by ocavue** [comment]
Thank you for your reporting and detailed analysis. I really appreciate it.

I will fix this as soon as possible. 

Just curious, what do you mean by `save the resulting markup`? Are you saving some kind of HTML string?

**Comment by BFriedrichs** [comment]
Ah, yes i use the getHTML helper function during the onChange. I save it for direct server side rendering but when editing on client side I load the string as the initial value.

**Comment by ocavue** [comment]
I see. Is there any chance you can use JSON instead of HTML string as the initial value? HTML parsing is likely to be problematic (e.g. this issue). JSON is much much more reliable for saving users' data.

**Comment by ocavue** [comment]
@BFriedrichs I've released a new version to fix this issue. Thank again for raising this issue. Let me know if the new version works for you.
