### ISSUE TITLE
Cannot clear all marks with commands.removeMark

### ISSUE THREAD

**Issue by labkey-alan** [remirror/remirror#1398]
### Summary

We recently upgraded from version `1.0.0-next.60`, we got everything working except for the ability to clear all marks at the current selection. We used `commands.removeMark({ type: null });` to remove all of the marks at the current selection, but this doesn't work anymore, and no errors are produced.

### Steps to reproduce

1. Create an editor
2. Add a button to your editor that uses the removeMark command:
    ```typescript
    const { commands } = useRemirrorContext();
    const clearMarkup = useCallback(() => commands.removeMark({ type: null }), [commands]);
    
    // somewhere in your render:
    <button type="button" onClick={clearMarkup}>Clear</button>
    ```

### Expected results

Any markup applied to the currently selected text in the editor would be removed e.g.:
**this text *that is bold and italic***
would become:
this text that is bold and italic

### Actual results

Nothing happens to the text, an error is emitted in my JS console:

```
There is a problem with the schema or you are trying to access a node / mark that doesn't exists.

Mark type: null does not exist on the current schema.
```

I am able to create my own command in a custom extension which works, it looks like this:
```typescrript
(): CommandFunction => parameter => {
    const { dispatch, tr } = parameter;
    const { from, to } = tr.selection;
    dispatch?.(tr.removeMark(from, to, null));
    return true;
}
```

### Possible Solution
[Due to the usage of `invariant` in `removeMark` ](https://github.com/remirror/remirror/blob/8e4398c8dcf5bfd5f03f92d176abd6d19a4c96a1/packages/remirror__core-utils/src/command-utils.ts#L429) an error is triggered when null is passed, even though null is explicitly supported in the underlying `tr.removeMark` command. To fix this particular issue you could do an explicit null check:

```typescript
export function removeMark(props: RemoveMarkProps): CommandFunction {
    return ({ dispatch, tr, state }) => {
        const { type, expand = true, range } = props;
        const selection = getTextSelection(props.selection ?? range ?? tr.selection, tr.doc);
        const markType = isString(type) ? state.schema.marks[type] : type;
        let { from, to, $from, $to } = selection;

        if (type !== null) {
            invariant(markType, {
                code: ErrorConstant.SCHEMA,
                message: `Mark type: ${type} does not exist on the current schema.`,
            });
        }

        const markRange = getMarkRange($from, markType, $to);

        if (expand && markRange) {
            ({ from, to } = markRange);
        }

        dispatch?.(tr.removeMark(from, isNumber(to) ? to : from, markType));

        return true;
    };
}
```

**Comment by KSABCarl** [comment]
I wrote a extension that does that in my current project based off how it's done in Tiptap:
```typescript
import { command, PlainExtension } from '@remirror/core';
import { CommandFunction, HelpersExtension } from 'remirror';

export class ClearFormattingExtension extends PlainExtension {
  get name() {
    return 'clearFormatting' as const;
  }

  @command()
  clearFormatting(props): CommandFunction {
    return ({ dispatch, tr, state }) => {
      const { empty, ranges } = state.selection;

      if (empty) {
        return;
      }

      Object.entries(state.schema.marks).forEach(([, mark]) => {
        ranges.forEach((range) => {
          dispatch?.(
            tr.removeMark(range.$from.pos, range.$to.pos, mark as any)
          );
        });
      });
      return true;
    };
  }
}

declare global {
  namespace Remirror {
    interface AllExtensions {
      clearFormatting: HelpersExtension;
    }
  }
}
```
It's not thoroughly tested and I'm a newbie in regards to remirror so there could be errors.

**Comment by whawker** [comment]
As `null` behaviour is explicitly mentioned in the [ProseMirror ref](https://prosemirror.net/docs/ref/#transform.Transform.removeMark), we should support this.
