### ISSUE TITLE
Yjs extension leaks yjs `UndoManager` instances when editor re-renders

### ISSUE THREAD

**Issue by ankon** [remirror/remirror#1448]
### Summary

Yjs extension leaks yjs `UndoManager` instances when the editor re-renders:
1. The yjs extension creates a `yUndoPlugin` instance as part of its "external" plugins (https://github.com/remirror/remirror/blob/963a1edcc2034f9b3af8765f55707ec2a2806129/packages/remirror__extension-yjs/src/yjs-extension.ts#L173-L198)
2. The `yUndoPlugin` creates a new Yjs `UndoManager` instance in it's `initState` callback (https://github.com/yjs/y-prosemirror/blob/039be96fb520e972fa37f0e896b585ef19da1beb/src/plugins/undo-plugin.js#L35-L48)
4. The `UndoManager` attaches itself to the document's `afterTransaction` event (https://github.com/yjs/yjs/blob/645f05b0bb2435552582f587f5379c33adda6ffe/src/utils/UndoManager.js#L166)
3. Remirror creates a new state on each rerender as part of the `useReactFramework` hook: https://github.com/remirror/remirror/blob/963a1edcc2034f9b3af8765f55707ec2a2806129/packages/remirror__react-core/src/hooks/use-react-framework.tsx#L43-L45

### Steps to reproduce

sandbox TBD, basically: 
1. Configure remirror with the yjs extension
2. Trigger rerenders of the editor (for example through hook changes etc)

### Expected results

Everything is happy.

### Actual results

* `Y.Doc` instance slowly collects more `afterTransaction` handlers
* Editor becomes slower and slower after key presses as the browser is busy creating undo transactions over and over
* Eventually browser crashes due to out-of-memory

### Possible Solution

y-prosemirror allows to provide a undo manager. We have forked the remirror yjs extension again to do that, see https://github.com/Collaborne/remirror-extension-yjs/commit/7c77917801c271c5f9b77c895fa8f9d84da12c63 for the commit.
In remirror "proper" you will have to update the y-prosemirror dependency to at least 1.0.14 to include https://github.com/yjs/y-prosemirror/pull/87, due to historic reasons we use our own y-prosemirror and basically merged that PR.

**Comment by ocavue** [comment]
I don't know much about YJS, but I'd like to merge it if you can submit a PR to Remirror. (I can take care of the updating y-prosemirror dependency)

**Comment by ankon** [comment]
See #1457 for a proposed fix (basically a merge of our changes + two tests)
