### ISSUE TITLE
remirror-floating-popover (Mentions Suggestions menu) lets elements below shine through (seems like incorrect z-index)

### ISSUE THREAD

**Issue by ceisele-r** [remirror/remirror#1459]
### Summary

Using the `MentionAtomExtension`, I am facing the problem that some "lower" elements shine through the Mentions Suggestions popup menu.

Versions used:
```
"@remirror/pm": "^1.0.9",
"@remirror/react": "^1.0.18",
"@remirror/react-editors": "^0.1.41",
```

### Steps to reproduce

1. Have an input with a label below the editor
2. Open the mentions popup so that it covers the input label below the editor
3. The label from the input below the editor "shines through"/lays over the mentions popup:
![image](https://user-images.githubusercontent.com/54797986/148250972-ead5bf03-ee8f-4312-936b-6cd4a4872db5.png)

Note that the element from below (the input label) has an implicit `z-index: auto`.

### Expected results

Suggestions Popup menu is the upmost element.

### Actual results

Input from below is "above" mentions popup

### Possible Solution

If I provide the element with class `remirror-floating-popover` a css `z-index` of only 1, it solves the issue.

### Screenshot(s)

See above.

**Comment by ceisele-r** [comment]
Please ignore this, this was a stacking context issue on our side. Sorry.

**Comment by Powersource** [comment]
Could you elaborate on what you did to fix this?

**Comment by Powersource** [comment]
Thank you. I think I need to learn more about stacking contexts. But in the meantime I seem to have fixed it by setting `.remirror-floating-popover { z-index: 10; }` globally.
