### ISSUE TITLE
EmojiExtension / EmojiPopupComponent seems to be visually broken (in SocialEditor)

### ISSUE THREAD

**Issue by ceisele-r** [remirror/remirror#1467]
### Summary

The `EmojiExtension` in combination with the `EmojiPopupComponent` as being used in the `SocialEditor` seems to be visually broken.
I found this page https://docs.remirror.org/showcase/social (looks like an earlier page of the docs), where the Emoji component looks good:
![image](https://user-images.githubusercontent.com/54797986/149494337-bbc9b47a-29c3-4fce-8145-e31f14511d71.png)

But on the current docs on https://remirror.io/ , the emoji popup looks broken:
![image](https://user-images.githubusercontent.com/54797986/149494467-0e985019-9e82-4a28-990a-1395d353a1d2.png)

It does not have a border, it is displayed "inside" the Html input compared to a mentions popup:
![image](https://user-images.githubusercontent.com/54797986/149494667-42ca666e-09a0-42ef-b198-e67301e1bc3a.png)

=> In the (I assume) earlier docs, the Emoji Popup looked similar to what the mentions popup looks now but now the Emoji Popup looks broken.

### Steps to reproduce

Type `:` in the sample editor here https://remirror.io/ or here https://remirror.io/docs/showcase/social .

### Expected results

I would expect that the style of the Emoji Popup matches the Mentions Popup.

### Actual results

See above.

### Possible Solution

I don't have a possible solution here besides using the same popup for Emojis as it is used for Mentions.

### Screenshot(s)

See above.

**Comment by ceisele-r** [comment]
Probably https://github.com/remirror/remirror/blob/a2ca7a83f35b3831b97817eb2cb38b1a82d60ab8/packages/remirror__react-components/src/components/emoji-popup-component.tsx#L33 is missing property `renderOutsideEditor` and https://github.com/remirror/remirror/blob/a2ca7a83f35b3831b97817eb2cb38b1a82d60ab8/packages/remirror__react-components/src/components/emoji-popup-component.tsx#L34 is missing `className={cx(Theme.MENTION_ATOM_POPUP_WRAPPER)}`

**Comment by ocavue** [comment]
@ceisele-r  Thanks for your PR. This has been fixed on the current website. 

![image](https://user-images.githubusercontent.com/24715727/149665259-2e5c54b4-d94e-45df-a758-2fa88b200a10.png)
