### ISSUE TITLE
Can't add bold style to a link

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#1491]
### Summary

Link and bold/italic/etc should be able to exist at the same time.
 
### Steps to reproduce

https://user-images.githubusercontent.com/24715727/151674360-b6b3f657-1681-4f0b-9223-54a6c3d01b12.mp4

**Comment by whawker** [comment]
This is because the link extension [explicitly excludes all other marks](https://github.com/remirror/remirror/blob/main/packages/remirror__extension-link/src/link-extension.ts#L223)

As a workaround (assuming direct access to `LinkExtension`) you could do

```ts
new LinkExtension({
  markOverride: { excludes: undefined }
})
```
