### ISSUE TITLE
Mention can't be delete on android 

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#1509]
### Summary

A user on Discord has reported that mention can't be deleted by pressing backspace/delete key on android. The device is running android 9 (Pie) with chrome version 97. 

### Steps to reproduce

1. open https://remirror.io
2. type `@P`
3. select a name from the dropdown menu
4. press the backspace key

https://user-images.githubusercontent.com/24715727/152633059-e8d8a0d4-404d-4843-8e96-6e820cce7266.mp4

### Expected results

The mention can be deleted. 

### Actual results

The keyboard is hidden after pressing the backspace key. 

### Possible Solution

N/A

### Screenshot(s)

See the video above.

**Comment by whawker** [comment]
Closing, as we can't fix this. It's a known issue on ProseMirror
