### ISSUE TITLE
Remirror CSS interferes with nested ProseMirror editors 

### ISSUE THREAD

**Issue by benrbray** [remirror/remirror#1521]
### Summary

I maintain [`prosemirror-math`](https://github.com/benrbray/prosemirror-math) which allows the user to edit math expressions inline. 
 I'm working on creating a Remirror extension to support the same behavior.

The plugin works using a custom NodeView that contains a nested ProseMirror editor (that is, an entirely separate editor instance appears inside the NodeView when the user is editing a math expression, similar to the Remirror code blocks that create CodeMirror instances).  Perhaps this is not the ideal solution, but I settled on this approach after trying a few other methods that didn't have the desired behavior. 

Unfortunately, some of the Remirror CSS leaks into the nested editor, even though it's an ordinary ProseMirror instance, not controlled by Remirror.  The main culprit seems to be here:

https://github.com/remirror/remirror/blob/826670eaba81d589fbad8037867ba8628b76ec3a/packages/remirror__styles/all.css#L4484-L4490

Which seems to be generated by this code:

https://github.com/remirror/remirror/blob/826670eaba81d589fbad8037867ba8628b76ec3a/packages/remirror__theme/src/theme.ts#L64-L69

Until this is fixed, I will have to manually override the CSS for the nested editor, but this isn't a very reliable solution.  I don't think using shadow DOMs inside a NodeView is supported by ProseMirror, otherwise I would consider that as well. 

### Steps to reproduce

Create a NodeView with a nested ProseMirror editor inside.  If this issue isn't clear enough I can provide a MWE.

### Actual results

![image](https://user-images.githubusercontent.com/221963/154513079-7c2f9254-1ef6-47b4-b952-0552803c69ac.png)

### Expected results

The chosen Remirror theme should not influence the behavior / appearance of the nested ProseMirror instance whatsoever.

### Possible Solution

Make sure all references to the `.ProseMirror` class are actually something like `.remirror-editor.ProseMirror`.

I'm happy to make a PR if the only change is indeed changing `.ProseMirror -> .remirror-editor.ProseMirror` everywhere, but it's not entirely clear to me how all the CSS is generated + tested so maybe someone more familiar with the repo can offer advice.

**Comment by whawker** [comment]
> Make sure all references to the `.ProseMirror` class are actually something like `.remirror-editor.ProseMirror.`

This definitely makes sense, we just need to check that it doesn't break other styles we use, as it will give the selectors higher specificity.

In terms of where to make the changes, it should just be modifying the files [here](https://github.com/remirror/remirror/tree/main/packages/remirror__styles) - then running `pnpm fix` (which with run `pnpm fix:css`) which will copy the files over to the themes package.
