### ISSUE TITLE
Provide Code Snippets in Storybook

### ISSUE THREAD

**Issue by schroeder-g** [remirror/remirror#1551]
### Description

There's a lot of utility around examples in the Storybook that isn't provided by the docs. However, there's currently no way to access the code that supplemented the examples. This would be greatly helpful for implementing the various features available in your library. 

### Context

Specifically in this case, it's not obvious how to conditionally style block quotes within the editor. it's being done [here](https://remirror.vercel.app/?path=/story/extensions-blockquote--basic), but I'm not sure how to leverage that in my own code.

The [`source-code-add-on` ](https://storybook.js.org/addons/storybook-source-code-addon) would make this relatively trivial.  Is this something you would consider tackling? It'd make remirror adoption far breezier. 

Many thanks 🙏

**Comment by dercias** [comment]
The storybook source code is in the folder [packages/storybook-react/](https://github.com/remirror/remirror/tree/main/packages/storybook-react). You can extract the examples from there.

**Comment by schroeder-g** [comment]
Thank you @dercias !
