### ISSUE TITLE
FontSizeExtension - rounding error

### ISSUE THREAD

**Issue by artfb** [remirror/remirror#1563]
### Summary
Got:
```
Unhandled Runtime Error
Error: Value must be a finite number
```

https://github.com/remirror/remirror/blob/main/packages/remirror__extension-font-size/src/font-size-extension.ts#L125

### Steps to reproduce

When trying to paste some random stuff into editor.
Turned out that style declaration `<some-tag style="font-size: clamp(...)` causes exception. Not sure where should I catch it in my app.

### Expected results

Error gets caught within extension.

### Actual results

Unhandled exception

### Screenshot

<img width="965" alt="image" src="https://user-images.githubusercontent.com/467327/159267501-de7e7de3-27aa-4556-ac92-c259e5eb45b7.png">

**Comment by whawker** [comment]
@artfb would you be able to share the HTML you tried to paste?

**Comment by artfb** [comment]
I copied whole page cmd a, cmd c, cmd v.
After some debugging turned out that part causing error was:

```
<div style="font-size: clamp(12px, 1.5vw, 14px); (...)" />
```

**Comment by whawker** [comment]
Thanks.

Note to self, check if `window.getComputedStyle` could fix this.

**Comment by whawker** [comment]
FWIW, `getComputedStyle` can not be used on paste content, as element in paste buffer is detached from the document

**Comment by whawker** [comment]
@artfb This should be resolved here. https://pr1643-remirror-ocavue.vercel.app/?path=/story/extensions-fontsize--basic
