### ISSUE TITLE
Tab-Key behavior inside the editor changed

### ISSUE THREAD

**Issue by VFritsch** [remirror/remirror#1574]
### Summary

In a older version of remirror, pressing the Tab-Key caused the editor to lose focus -> jump to the next element, while pressing it inside a list it added a new indent.

This behavior is not supported anymore in the current version.

Is there any way to enable this behavior again or recreate it manually via code with properties/components?
### Steps to reproduce

Still working in this version:
https://615b820a97b64a25171ada6e--remirror.netlify.app/

### Expected results

There should be a way to replicate the old behavior or allow both events for pressing the tab-key.

### Actual results

Pressing Tab inside the empty editor does nothing, only the identation inside a list is working.

**Comment by whawker** [comment]
Will raise this at the next maintainer meeting. I find this painful too. Related to #1489

**Comment by whawker** [comment]
@VFritsch this should be fixed. Sorry for the delay!

**Comment by VFritsch** [comment]
Thank you very much!
