### ISSUE TITLE
Unable to add a new annotation properly after deleting an existing annotation

### ISSUE THREAD

**Issue by devcer** [remirror/remirror#1655]
### Summary

Unable to properly add and remove annotations from the remirror doc.

### Steps to reproduce

* Go to https://remirror.vercel.app/?path=/story/extensions-annotation--configurable
* create few annotations
* delete an annotation
* create a new annotation

### Expected results

* The new annotation should have been properly created

### Actual results

* A random annotation at a random place is getting created

### Possible Solution
* May be value of tr.selection is incorrect inside addAnnotation command

### Screenshot(s)

https://user-images.githubusercontent.com/3799600/170030492-b5939e05-c0f8-46e6-9c15-91add8f8600e.mov

**Comment by devcer** [comment]
@ronnyroeller @whawker thoughts?

**Comment by devcer** [comment]
@ronnyroeller @whawker @ifiokjr can you please add sponsored label to this issue and prioritise?

**Comment by whawker** [comment]
@devcer Happy to take a look, however from the looks of it you're not sponsoring us?

**Comment by devcer** [comment]
@whawker Thanks for taking a look. \o/ We have been very happy with remirror and our company has been sponsoring remirror from the past few months, Not sure if the sponsorship went through for this month yet but you can check for the last few months. I'm from Userfocus and you must have received the sponsorship from `narulachirag` or `user-focus`.

**Comment by whawker** [comment]
No worries. For what it's worth, I can see a sponsorship beginning 8th April, which was then cancelled 2nd May

**Comment by devcer** [comment]
Okay. I will check with my team and get this reinstated again. Thanks for your help again.

**Comment by whawker** [comment]
@devcer published fix. Available on remirror@1.0.88 / @remirror/extension-annotation@1.1.26

**Comment by devcer** [comment]
Thank you, Will. It works 🥳
