### ISSUE TITLE
TaskList Checkboxes do not honor editable flag

### ISSUE THREAD

**Issue by labkey-alan** [remirror/remirror#1657]
### Summary

A task list item rendered in a Remirror component with `editable={false}` can still be checked/unchecked, which triggers the onChange handler.

### Steps to reproduce

1. Instaniate a Remirror Editor with the TaskList extension
2. Render a remirror editor with `editable={false}`, and with the content that has a task list
3. Click checkbox

### Expected results

Nothing should happen, the checkboxes should be disabled, clicks should yield no results, and onChange handlers should not be called.

### Actual results

The checkbox changes state (from check to unchecked, or unchecked to checked), onChange handlers are triggered. Even if you intercept the onChange and don't modify the document, the checkbox changes state.

### Possible Solution

In the `TaskListItemExtension` check if the document is editable, if so don't do anything in the click handlers, and render the checkboxes with `disabled`.

**Comment by whawker** [comment]
The fix for this is simple, if the editor is initially rendered as `editable={false}`.

However if the editable flag changes a runtime, looks like we need to publish some sort of event to update the node view.

@labkey-alan does your `editable` flag change at run time?

**Comment by whawker** [comment]
@labkey-alan see the above PR - would be keen to know your thoughts on the checkbox not being "disabled" (visually speaking)

The PR itself prevents the checkbox state being modified.

**Comment by whawker** [comment]
I has asked on the [ProseMirror forum](https://discuss.prosemirror.net/t/is-it-possible-to-subscribe-to-view-editable-flag-changing/4648) whether it is possible to trigger behaviour when `editable` changes

**Comment by labkey-alan** [comment]
Our editor does change the editable flag after initial render in a few edge cases, but I think we'd be fine living with that for the time being. I think it's less important if the checkbox doesn't appear disabled, what's important is that a user clicking on the checkbox has no effect. It's pretty easy to make the checkbox look disabled via CSS in our case as well, we have a css class on the parent rendering the editor that indicates read only mode, so we should be able to add a css style along the lines of `.read-only input[type="checkbox"] { /* make it look disabled */ }`

**Comment by labkey-alan** [comment]
Thank you so much for taking care of this so quickly!
