### ISSUE TITLE
@remirror/styles/styled-components > styled-components.d.ts > missing extensionCountStyledCss

### ISSUE THREAD

**Issue by DoK6n** [remirror/remirror#1681]
### Summary

@remirror/styles/styled-components
missing extensionCountStyledCss in styled-components.d.ts

### Steps to reproduce

<img width="304" alt="image" src="https://user-images.githubusercontent.com/39258608/171790802-8a7d901f-d712-4e55-b449-216536b0161c.png">

### Expected results

export declare const extensionCountStyledCss: ReturnType<typeof css>;

### Actual results

<img width="961" alt="image" src="https://user-images.githubusercontent.com/39258608/171790704-10571f57-f7c6-48a8-8b2e-8cc67aa3ce90.png">

### Possible Solution

@remirror/styles/styled-components > styled-components.d.ts
add -> export declare const extensionCountStyledCss: ReturnType<typeof css>;

**Comment by whawker** [comment]
Good spot @DoK6n, I forgot to update the themes/styles when I added the count extension.

Published [`@remirror/styles`](https://www.npmjs.com/package/@remirror/styles) 1.1.4 which should fix this.
