### ISSUE TITLE
Jest-remirror - TypeError: Cannot read property 'builders' of undefined

### ISSUE THREAD

**Issue by DiegoPayan** [remirror/remirror#1706]
### Summary

After trying to upgrade to the latest released versions, I started getting a new error on my tests.

### Steps to reproduce

- Create a new React project with create-react-app
- Install the latest released versions of remirror, @remirror/react and jest-remirror
```
    "remirror": "^1.0.86",
    "@remirror/react": "1.0.40",
    "jest-remirror": "1.0.46", 
```
- Import anything from `jest-remirror` in any file
``` 
    import { jsdomPolyfill } from "jest-remirror";
    jsdomPolyfill(); 
```
- Run `yarn test`

Can take a look at this simplified example https://codesandbox.io/s/autumn-glade-u2x2km

### Expected results

Test running without throwing errors that comes from the library

### Actual results

Tests are throwing `TypeError: Cannot read property 'builders' of undefined`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22713458/172686365-fa3ef508-8b60-402e-9eec-2b30e631351d.png)

**Comment by whawker** [comment]
Hi @DiegoPayan, please see #1677 for workaround

**Comment by whawker** [comment]
P.s. I'll see if can implement a proper fix tomorrow

**Comment by DiegoPayan** [comment]
@whawker Thanks for your answer, i've tried the workaround and it worked in code sandbox and locally but just when using `npm install`, for some reason with `yarn install` is still not working.
