### ISSUE TITLE
Issue when updating to @remirror/react-components@1.0.31+

### ISSUE THREAD

**Issue by strdr4605** [remirror/remirror#1721]
### Summary

Here are my remirror deps:

```json
    "@remirror/pm": "^1.0.16",
    "@remirror/react-components": "^1.0.30",
    "@remirror/react-core": "^1.1.3",
    "@remirror/react-hooks": "^1.0.30",
    "remirror": "^1.0.76",
```

when I try to update to:

```diff
    "@remirror/pm": "^1.0.16",
-    "@remirror/react-components": "^1.0.30",
+   "@remirror/react-components": "^1.0.31",
    "@remirror/react-core": "^1.1.3",
-    "@remirror/react-hooks": "^1.0.30",
+    "@remirror/react-hooks": "^1.0.31",
    "remirror": "^1.0.76",
```

I get the error:

```
`useRemirrorContext` was called outside of the `remirror` context. It can only be used within an active remirror context created by the `<Remirror />`.

For more information visit https://remirror.io/docs/errors#rmr0200 
    at FloatingWrapper (/node_modules/@remirror/react-components/dist/remirror-react-components.browser.esm.js:1793:30)
    at FloatingToolbar (/node_modules/@remirror/react-components/dist/remirror-react-components.browser.esm.js:1880:25)
```

I see that only these changes were made:

chore(changeset): version update (https://github.com/remirror/remirror/pull/1614) https://github.com/remirror/remirror/commit/118fc255b4570de1e1d52103b9409c664e3e587d

### Steps to reproduce

I may be an issue with my project. But it's strange that a patch update will break the app.
I am looking for ideas about where the problem could be.
@ocavue

**Comment by ocavue** [comment]
Does removing `node_modules` and `yarn.lock` and then reinstalling dependencies help? 

I guess you have multiple different versions of one remirror packages installed.

**Comment by strdr4605** [comment]
You are right, but I can not remove `package-lock.json` file as it will break other deps in the project.
I had to uninstall all remirror packages and do install again.

I even did a small script to get all remirror packages and pipe them to `npm uninstall`

```bash
cat package.json | grep remirror | awk '{printf "%s ",$1}' | awk 'gsub(/[\":]/,"")'
# @remirror/pm @remirror/react-components @remirror/react-core @remirror/react-hooks remirror
```

In case someone also has the same issue and can't remove the lock file.
