### ISSUE TITLE
Custom link validation function option - link extension

### ISSUE THREAD

**Issue by marcoSven** [remirror/remirror#1730]
### Description

Ability to provide a custom link validation function for the Remirror link extension.

### Context

For a project that already uses another method of link validation, it would be more maintainable and easier to match results.

**Comment by Amethystafyy282** [comment]
I think this might help.
`new LinkExtension({ autoLinkRegex: 'your_regexp' }),`

**Comment by marcoSven** [comment]
Thank you @Amethystafyy282 I am aware of this option but I am proposing the option to provide your own validation that would be used instead of the autoLinkRegex

https://github.com/marcoSven/remirror/commit/f7f824fd4e72e53e16f69b4617d8f1190009ef8a#diff-c6362a6560783faf0b832a4b10098233042a3092f87b84b29f28f46c94410ac9R158
