### ISSUE TITLE
Add bidi support

### ISSUE THREAD

**Issue by sijad** [remirror/remirror#179]
## Description

some languages, such as Persian, Arabic, Hebrew, etc need to be aligned from Right To Left in editor.
a direction extension need to be added to change `dir` attribute.
another possible solution would be handling bidi automatically by input, please see https://github.com/ianstormtaylor/slate/pull/204

## Checklist

- [X] I have read the [**contributing**][contributing] document.

[contributing]: https://github.com/ifiokjr/remirror/blob/canary/docs/pages/contributing.md

**Comment by ifiokjr** [comment]
This is really important and is something to be addressed.

**Comment by sijad** [comment]
one approach can be like `draft-js` which try to guess `dir` based text input.
there also can a new extension to let user change the `dir` similar to CKEditor and TinyMCE.

do you have any suggestion which approach would be better or how it should be implemented?

**Comment by ifiokjr** [comment]
Okay, this is addressed in the `next` branch by #309. It currently only supports inference at startup but it should be trivial to add continuous checks as you type.

**Comment by ifiokjr** [comment]
Oh and thanks for raising this issue. The PR you referenced was very useful for adding the functionality.
