### ISSUE TITLE
Remirror not working on Chrome and Safari on iOS devices

### ISSUE THREAD

**Issue by marcelovicentegc** [remirror/remirror#1864]
# Summary

When opening remirror website and storybook stories on iOS devices (Chrome and Safari - possibly other browsers), it breaks (on storybook), or loads infinitely (per website)

# Steps to reproduce

> Tried on iPhone XR iOS v14.8 and iPhone 

## Open and visit any story from: https://remirror.vercel.app/?path=/story/introduction--introduction 

You will notice that varying errors pop up:

### Markdown story
![WhatsApp Image 2022-09-19 at 1 40 46 AM](https://user-images.githubusercontent.com/33183880/190951178-bc6814d6-5ed0-4f2b-858d-957af7ccf0dd.jpeg)

### Social story
![WhatsApp Image 2022-09-19 at 1 41 30 AM](https://user-images.githubusercontent.com/33183880/190951188-224203e6-51ed-4e5a-947b-a94622eaa751.jpeg)

### Notice that it gets stuck at the `loading` state**
![WhatsApp Image 2022-09-19 at 1 44 34 AM](https://user-images.githubusercontent.com/33183880/190951307-3feb0b1d-4f56-4005-8173-3e36d10c457f.jpeg)

**Comment by ocavue** [comment]
macOS safari Version 16.0 doesn't work too. 

<img width="900" alt="image" src="https://user-images.githubusercontent.com/24715727/191230079-7c44310f-a1d9-4da8-b775-012d6b96cf5b.png">

**Comment by ocavue** [comment]
Fixed in remirror@2.0.2

**Comment by marcelovicentegc** [comment]
Thanks so much @ocavue! Congrats on the job done, this tool is fantastic! :rocket:
