### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by mrexox** [remirror/remirror#1866]
I understand the reasons for this code, but it seems like a buggy thing. It always throws a warning, and for some checks/linters warnings are considered as errors.

https://github.com/remirror/remirror/blob/2c96b54ace3eab11aa5a5215944556cdee5dbdca/packages/remirror__core-utils/src/core-utils.ts#L1224-L1232

When starting a server, I get two warnings:
```
./node_modules/@remirror/core-utils/dist/remirror-core-utils.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/@remirror/core-utils/dist/remirror-core-utils.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by ocavue** [comment]
> When starting a server, I get two warnings:

Could you share me an example repo for such warning? I'm not exactly sure how to reproduce the problem.

**Comment by mrexox** [comment]
Here is the basic repo I could create to reproduce the issue: https://github.com/mrexox/test-remirror-warning

**Comment by ocavue** [comment]
Your repo is useful. I'm already working on a PR based on your replication. Thanks!

**Comment by mrexox** [comment]
Thank you very much for the quick fix! I really appreciate your fast response :pray: :rocket:
