### ISSUE TITLE
Version 2.0.6 has client-side error

### ISSUE THREAD

**Issue by potrepka** [remirror/remirror#1884]
### Summary

I am using remirror for the first time today, and I have an error on the frontend that I believe is due to some recent changes.

### Steps to reproduce

Install and use remirror with `pnpm`.

### Screenshot(s)

![Screen Shot 2022-09-27 at 6 16 11 PM](https://user-images.githubusercontent.com/9044824/192669198-33b632f6-5550-4e5c-9d0a-583c1c45aa9c.png)
![Screen Shot 2022-09-27 at 6 16 54 PM](https://user-images.githubusercontent.com/9044824/192669209-c04c8ed7-4d15-4ff9-9037-47bf1b3e3aeb.png)

**Comment by ocavue** [comment]
Hi @potrepka. Could you share me more detail about how to reproduce this issue? A minimal reproduction repository would be best.

**Comment by rockiger** [comment]
@ocavue https://github.com/remirror/remirror-examples/tree/main/with-vite

Has the same issue on my machine. It happens only with **Vite**. CRA is working fine.

OS: Ubuntu 22.04
Node: v16.16.0
Browsers: Chrome 105 / Firefox 106

**Comment by ocavue** [comment]
I can reproduce it. Thanks! It seems that only `vite dev` has this issue and `vite build && vite preview` works fine.

**Comment by ocavue** [comment]
remirror@2.0.8 should fix this issue. I tested Create React App, Vite and Next.js, both on production and development.
