### ISSUE TITLE
Material UI Errors in React Toolbar Components

### ISSUE THREAD

**Issue by JanReichelt** [remirror/remirror#1901]
## Summary

The React Toolbar Component (e.g. the CommandButton) throws Errors, because a disabled Button is wrapped with a Tooltip (see screenshot), which directly disables it (because pointer events are prohibited this way).  
I experienced it with the prebuilt react undo and redo buttons, but it should apply to all other Toolbar buttons as well.

## Versions
(used in the example repo)
```
    "remirror": "^2.0.10"
    "@remirror/pm": "^2.0.0",
    "@remirror/react": "^2.0.10",
```
## Steps to reproduce

Just use the [5 Minute Tutorial](https://remirror.io/docs/5-min-tutorial) boilerplate and add a MarkdownToolbar from `@remirror/react`. Or:
Example Git-Repo: https://github.com/JanReichelt/remirror-mui-error

Inspect the browser console to see the mentioned errors.

## Possible Solution

It is proposed [here](https://github.com/mui/material-ui/issues/8416#issuecomment-1168715702) that the Button could be wrapped in an intermediary html tag to re-enable pointer events as a quick fix.

## Screenshot(s)
<img width="1440" alt="Bildschirmfoto 2022-10-12 um 10 26 55" src="https://user-images.githubusercontent.com/45282277/195294804-d0c3d20f-cf35-4d94-b5f5-3c858ff47434.png">

**Comment by NotNikita** [comment]
Interesting, i also have MUI error in remirror, but in node_modules:
![image](https://user-images.githubusercontent.com/47776039/198291613-8ce4c24c-20fb-402a-bd04-90e82c1a18f0.png)

**Comment by peter-popluhar** [comment]
Hello. Any progress on this issue?
Im having same problem, and it throws a lot of warnings in jest test runner as well.
codesanndbox: https://codesandbox.io/p/sandbox/silly-mayer-70ehsh?selection=%5B%7B%22endColumn%22%3A10%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A10%2C%22startLineNumber%22%3A5%7D%5D&file=%2Fcomponents%2FRemirror.tsx

page: https://70ehsh-3000.preview.csb.app/ (open console in browser, and reload page. warnings should be present)

**Comment by ajspetner** [comment]
I just submitted the above PR which implements the [proposal](https://github.com/mui/material-ui/issues/8416#issuecomment-1168715702) referenced by @JanReichelt . This fix also makes tooltips work for inactive buttons (which is the typical behavior seen in most apps).
