### ISSUE TITLE
Pseudo class ":first-child" used in Remirror raises warning when using Next.js and Emotion

### ISSUE THREAD

**Issue by leonard-henriquez** [remirror/remirror#1919]
### Summary

I have a warning in the console raised by Next.js that seems to be related to the use of ":first-child" in the styles of Remirror which is unsafe for server side rendering

My versions:
- @emotion/react: 11.10.0
- @emotion/server: 11.10.0
- @emotion/styled: 11.10.0
- @remirror/core: 2.0.6
- @remirror/pm: 2.0.0
- @remirror/react: 2.0.12
- @remirror/react-components: 2.0.10
- @remirror/styles: 2.0.1
- @remirror/theme: 2.0.1
- next: 12.3.1

### Steps to reproduce

- Use Next.js
- Use Remirror with the emotion styling described [here](https://remirror.io/docs/concepts/styling)

### Expected results

No warning in the browser console

### Actual results

Warning in the console:
> The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".

### Possible Solution

Replace all the instances of ":first-child" with ":first-of-type" in the `@remirror/styles` package

https://github.com/remirror/remirror/blob/b637f9f3ebfef7b77849476988bf98db2c0808a2/packages/remirror__styles/components.css#L112-L115

### Screenshot(s)

<img width="1148" alt="Capture d’écran 2022-10-24 à 12 10 37" src="https://user-images.githubusercontent.com/30215564/197503080-8d82bc3a-fec5-4337-bfcc-30b7acd1014b.png">

**Comment by ocavue** [comment]
Duplicate https://github.com/remirror/remirror/issues/1785
