### ISSUE TITLE
No matching version found for prosemirror-view@^1.29.0

### ISSUE THREAD

**Issue by gaowujian** [remirror/remirror#1928]
### Summary

The problem is same as the title

### Steps to reproduce

We use monorepo to manage our projects. When we add the dependencies to the project, using `pnpm add remirror @remirror/react @remirror/pm`. The error alert show up. No matching version found for prosemirror-view@^1.29.0

### Expected results

all of three libs can be added successfully

### Actual results

No matching version found for prosemirror-view@^1.29.0

### Screenshot(s)
![image](https://user-images.githubusercontent.com/29998334/198973881-f4a82522-2672-407e-891a-6c97fef3568d.png)

**Comment by ocavue** [comment]
prosemirror-view 1.29.0 was published 19 days ago. I guess your are using the `--offline` flag when doing `pnpm install`. 

```
$ npm info prosemirror-view

prosemirror-view@1.29.0 | MIT | deps: 3 | versions: 242
ProseMirror's view component
https://github.com/prosemirror/prosemirror-view#readme

dist
.tarball: https://registry.npmjs.org/prosemirror-view/-/prosemirror-view-1.29.0.tgz
.shasum: 5a9baa32a3c520442ad443f4bbf5ec7400e55b4e
.integrity: sha512-bifVd5aD9uCNtpLL1AyhquG/cVbNZSv+ALBxTEGYv51a6OHDhq+aOuzqq4MermNdeBdT+5uyURXCALgzk0EN5g==
.unpackedSize: 765.4 kB

dependencies:
prosemirror-model: ^1.16.0    prosemirror-state: ^1.0.0     prosemirror-transform: ^1.1.0

maintainers:
- marijn <marijnh@gmail.com>

dist-tags:
beta: 1.24.0-beta.3             latest: 1.29.0                  prerelease: 1.9.14-prerelease6

published 2 weeks ago by marijn <marijnh@gmail.com>
```
