### ISSUE TITLE
EntityReference isn't getting added around a hyperlink

### ISSUE THREAD

**Issue by devcer** [remirror/remirror#1933]
### Summary

LinkExtension and EntityReference extension aren't working together

### Steps to reproduce

* Configure LinkExtension using `new LinkExtension({ autoLink: true })` in Entity reference extension storybook -> https://remirror.vercel.app/?path=/story/extensions-entityreference--highlight
* Type a link say `www.google.com` in the document 
* Create an `interesting` entity reference around it

### Expected results
Link should also have been a part of the entity reference

### Actual results
Link is not highlighted

### Possible Solution
Mark should be added around Link

### Screenshot(s)
<img width="1366" alt="Screenshot 2022-11-02 at 10 17 45 PM" src="https://user-images.githubusercontent.com/3799600/199552098-fc9f85cb-ea33-4117-ad03-68b678609257.png">

**Comment by whawker** [comment]
The Link extension [explicitly excludes all other marks](https://github.com/remirror/remirror/blob/main/packages/remirror__extension-link/src/link-extension.ts#L318)

To allow it to mix with other marks you need to add

```js
new LinkExtension({
  autoLink: true,
  markOverride: {
    // only exclude self 
    exclude: 'link', // or 'bold italic underline link' (assuming those extensions)
  }
})
```

##### Aside

Also it seems like the `LinkExtension` has [Medium priority](https://github.com/remirror/remirror/blob/main/packages/remirror__extension-link/src/link-extension.ts#L290) by default, so **if you want to the entity reference to _wrap_ the link** you could either

```js
extensions: () => [
  new EntityReferenceExtension({ priority: ExtensionPriority.Medium }),
  new LinkExtension({
    autoLink: true,
    markOverride: {
      exclude: 'link', 
    }
  })
]
```

or 

```js
extensions: () => [
  new EntityReferenceExtension(),
  new LinkExtension({
    autoLink: true,
    markOverride: {
      exclude: 'link', 
    },
    priority: ExtensionPriority.Default
  })
]
```

**Comment by whawker** [comment]
CodeSandbox: https://codesandbox.io/s/inspiring-bash-vdwn5e?file=/src/App.tsx
