### ISSUE TITLE
jest-prosemirror do not set text selection correctly

### ISSUE THREAD

**Issue by werreour** [remirror/remirror#1945]
### Summary

After update jest-prosemirror do not set text selection correctly anymore. `<start>`, `<end>`, `<cursor>` tags are ignored and the whole node is selected.

### Steps to reproduce

the easiest way to reproduce is via sample code (it fails):

```ts
import { createEditor, initSelection, ol, li, doc } from "jest-prosemirror";

describe("describe", () => {
  test("my test", () => {
    const document = doc(ol(li("lorem"), li("<start>ipsum<end>")));
    const state = createEditor(document);
    const { $from, $to } = state.selection.ranges[0];

    const { $anchor, $head } = initSelection(document);
    console.log({ $anchor, $head, $from, $to });

    expect($anchor.pos).toBe(9); // actual 0
    expect($from.pos).toBe(9); // actual 0

    expect($head.pos).toBe(14); // actual 16
    expect($to.pos).toBe(14); // actual 16
  });
});
```

I built a codesanbox also to demonstrate the issue:
https://codesandbox.io/s/friendly-jerry-4z9o10?file=/test/index.test.js

(tab "tests" should be selected to view the results of the test)

### Expected results

Text is selected via tags correctly.

### Actual results

The whole node is selected.

**Comment by whawker** [comment]
Need to investigate here, but at first glance looks like your `li` might be missing a paragraph child?

```diff
- doc(ol(li("lorem"), li("<start>ipsum<end>")));
+ doc(ol(li(p("lorem")), li(p("<start>ipsum<end>")))); 
```

**Comment by werreour** [comment]
Yeap, it does seem to fix the issue 🤔 was a bit confused it worked before update. Thank you!
