### ISSUE TITLE
Question about tables support

### ISSUE THREAD

**Issue by sorokinvj** [remirror/remirror#195]
Hey guys, I am considering Remirror for the replacement of new beta-Slate-JS, so I am now choosing a new RichText Editor. 

The main thing is that I need tables and just wondering how you guys are dealing with them? Are there any problems that I need to know in advance? All the frameworks I worked before have some problems with tables, either connected to performance or just too complicated to implement.

I am writing transcription/translation app which mainly looks like this:

![2020-01-14_16-49-52](https://user-images.githubusercontent.com/4914235/72364390-5b4b4f80-36ee-11ea-8a67-405a3e7db4fc.png)

There should be custom rendered components in Editor and custom keypress events (particularly I want my users to easily send text from cell to cell by pressing Enter). 

Do you see any blocks if I go for Remirror to implement this interface?

Sorry for asking this, but I am a Junior and not really experienced with all the complications of web development yet, so I need some help. 

Thanks!

**Comment by ifiokjr** [comment]
Right now `remirror` doesn't support tables by default, but it's available via [`prosemirror-tables`](https://github.com/ProseMirror/prosemirror-tables). It's a feature I really want to see added to the core libraries in the near future.

**Comment by sorokinvj** [comment]
@ifiokjr thanks! how do you connect prosemirror modules to remirror?

**Comment by ifiokjr** [comment]
@sorokinvj I somehow missed your question, I'll add some documentation on how to do this as it's a common question.

**Comment by sorokinvj** [comment]
@ifiokjr Thanks Ifiok! It would be nice also if you can clarify how to init Remirror with text from db, like from json or other source.

**Comment by ocavue** [comment]
Related issue: #49
