### ISSUE TITLE
"5 Minute Tutorial" instructions don't work

### ISSUE THREAD

**Issue by siefkenj** [remirror/remirror#1970]
### Summary

I am trying to follow the instructions in the "5 Minute Tutorial" here https://remirror.io/docs/5-min-tutorial

However, `npm run start` produces an error about `./node_modules/babel-loader/lib/index.js`

### Steps to reproduce

Set up just as the guide says:
```
mkdir tmp
cd tmp
npm init
npm install create-react-app
npx create-react-app cra-remirror --template typescript
cd cra-remirror
npm add --save remirror @remirror/react @remirror/pm @emotion/react @emotion/styled @remirror/react-editors
```

Then replace the contents of `App.tsx` with
```
import { WysiwygEditor } from '@remirror/react-editors/wysiwyg';

const App: React.FC = () => {
  return (
    <div style={{ padding: 16 }}>
      <WysiwygEditor placeholder='Enter text...' />
    </div>
  );
};

export default App;
```

and run `npm run start`

### Expected results

A development live-preview of the app

### Actual results

An error, which appears to be from babel:
```
Compiled with problems:

ERROR in ./node_modules/@remirror/core-helpers/dist/remirror-core-helpers.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /tmp/cra-mirror/cra-remirror/node_modules/@remirror/core-helpers/dist/remirror-core-helpers.js: When using '@babel/plugin-transform-parameters', it's not possible to compile `super()` in an arrow function with default or rest parameters without compiling classes.
Please add '@babel/plugin-transform-classes' to your Babel configuration.
  438 |   constructor({ code, message, disableLogging = false } = {}) {
  439 |     var __super = (...args) => {
> 440 |       super(...args);
      |       ^^^^^^^^^^^^^^
  441 |       __publicField(this, "errorCode");
  442 |       __publicField(this, "url");
  443 |     };
```

**Comment by ocavue** [comment]
I can reproduce this issue. Thank you for the feedback. 

We've seems many CreateReactApp-only issues from all users. I guess maybe I will just remove CRA from our docs and replace it with Vite.

**Comment by LeiSe7en** [comment]
Hi @ocavue :
We have a project created by using create-react-app, it was working fine with remirror before. But today after i ran `yarn install` it's not working anymore. and the error is exactly same with the error reported in this issue. 
So do we have any workaround right now?
Thanks

**Comment by ocavue** [comment]
I'll check it today and try to provide a workaround.

**Comment by ocavue** [comment]
@LeiSe7en Could you try to upgrade to latest version (`remirror@^2.0.23`) and see if this issue has been fixed? 

You might also need to [de-duplicate](https://github.com/ocavue/pnpm-deduplicate#solutions-for-other-package-managers) the lock file (`pnpm-lock.json`, `yarn.lock` or `pnpm-lock.yaml`).

**Comment by siefkenj** [comment]
@ocavue Thanks! `remirror^2.0.23` fixes this issue :-D
