### ISSUE TITLE
[Docs Bug] Advanced example doesn't work

### ISSUE THREAD

**Issue by aried3r** [remirror/remirror#202]
## Description

First of all, thanks for this project! Should have opened with this in #201. :)
Opening this separately, since – while related – it doesn't necessarily have the same solution as #201.

I believe the [advanced example](https://docs.remirror.org/guides/advanced-guide/) doesn't work, or is at least heavily tied to being run within the context of this repo. Ideally, it should be standalone, see also #201.

A few things I noticed:

```JS
import { wysiwygEditorTheme } from '../theme';
```

This assumes that I have a `theme` somewhere, but I believe this is only the case if being run in this repo.

Some steps are missing, even if somewhat logical. In one snippet it says to create an `InnerEditor` but this is never used again, however a `MyInnerEditor` is being used later on. Nothing tragic, but I believe as a showcase it should be possible for new developers to throw the code in somewhere and just run it without having to fix the example. I'm not saying that people shouldn't have to do any work by themselves, but at least the examples should Just Work™. Maybe also comments as to where to put the code would help as well.

There's also unused imports and type errors.

## Possible Fix

Provide standalone examples for the basic and advanced example, see #201.

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/remirror/blob/canary/docs/contributing.md)
      document.

**Comment by ifiokjr** [comment]
Thanks for opening this issue. It hasn't been fixed but it has been removed. 

I'll create a working advanced example later. For now, the [playground](https://remirror.io/playground) should suffice.
