### ISSUE TITLE
Newlines and extra spaces are filtered?

### ISSUE THREAD

**Issue by halodong** [remirror/remirror#2026]
### Summary

I just started to get in touch with remirror, and I found a strange behavior. When I `setContent` or `getMarkdown` or `getText`, no matter how many times the spaces and newlines occur, it seems to only keep it once, which makes me unable to get the actual input. In the example on the official website It also happens like this, can anyone help me how to solve this problem?

https://remirror.vercel.app/?path=/story/editors-markdown--dual-editor
### Expected results
Newlines and spaces can be obtained normally

### Screenshot(s)
<img width="662" alt="截屏2023-04-22 21 43 59" src="https://user-images.githubusercontent.com/48054715/233788945-61b2311f-674e-4934-ba8a-b36f522893a9.png">

**Comment by jfrader** [comment]
What is the solution to this problem?

**Comment by halodong** [comment]
@jfrader I didn't solve it, because I found that the current mainstream markdown editors, including github's editors, seem to behave like this, so I didn't rush to do it, but if you need the content to be exactly the same as the rendering, you should be able to use codemirror6 extension([link](https://remirror.io/docs/api/extension-codemirror6/))
