### ISSUE TITLE
On paste got error: "Uncaught TypeError: navigator.clipboard.readText is not a function"

### ISSUE THREAD

**Issue by dgtllion** [remirror/remirror#2029]
### Summary

On storybook page https://remirror.vercel.app/?path=/story/editors-wysiwyg--basic when i try to paste with paste button i get this error:
```Uncaught TypeError: navigator.clipboard.readText is not a function```

### Steps to reproduce

Open [link](https://remirror.vercel.app/?path=/story/editors-wysiwyg--basic) with Firefox browser and try to click on paste button.

### Expected results

Paste the copied text to editor

### Actual results

Raising an error: "Uncaught TypeError: navigator.clipboard.readText is not a function"

**Comment by dgtllion** [comment]
@ocavue the error is gone but the behavior of paste is not correct.
When i paste with CMD+V it gives me another result then when i paste it with button.

And another question is the a function to paste plain text without format?

**Comment by ocavue** [comment]
> When i paste with CMD+V it gives me another result then when i paste it with button.

Firefox doesn't support this API so I guess there is no way to implement the paste button correctly in Remirror. Let me know if you know any kind of workaround for it.

**Comment by ocavue** [comment]
> a function to paste plain text without format?

You can copy the existing [`paste` command](https://github.com/remirror/remirror/blob/e88cf35bbc32a18ed24cbf0e239c0f835145c124/packages/remirror__core/src/builtins/commands-extension.ts#L898-L930), but change `this.insertNode(htmlToProsemirrorNode(value))` into `this.insertText(value)`.

**Comment by dgtllion** [comment]
i see that the behavior in Chrome is also not equal. with CMD+V it gives me another results then when i paste with button.

> Firefox [doesn't support `navigator.clipboard.readText`](https://caniuse.com/mdn-api_clipboard_readtext) so I guess there is no way to implement the Remirror paste button correctly in Firefox. Let me know if you know any kind of workaround for it.

Ill check the workaround for Firefox.

**Comment by ocavue** [comment]
> with CMD+V it gives me another results then when i paste with button.

Could you open a new issue with more details? Thanks.

**Comment by dgtllion** [comment]
> Let me know if you know any kind of workaround for it.

on Google Docs they open a modal with description to install a plugin or to use CMD+V. So that will be a workaround for now.
