### ISSUE TITLE
Easy keybindings

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#204]
## Description

It's quite common to want to take actions on certain keypresses (for example Enter -> save/send, Escape -> dismiss popover). The best way to do this in Remirror seems to be with an extension. However, the extensions seem to replace the keybindings rather than work together, it feels like Remirror extensions should automatically chain keybindings, or at least give the user a way of doing so. (I'm basing this on the implementation of BaseKeymapExtension which explicitly chains to baseKeymap; if I'm wrong maybe this code snippet can serve as an example anyway.)

## Example

Here's an example using the current API. I have not thought of a good name for `E` yet :wink: 

```ts
import { baseKeymap, chainCommands } from "prosemirror-commands";

export interface RemirrorEditorProps extends SproutEditorProps {}
type E = { commandModifier: boolean; shiftKey: boolean };
export interface SproutKeymapExtensionOptions extends BaseExtensionOptions {
  Enter?: (e: E) => boolean;
}

class SproutKeymapExtension extends Extension<SproutKeymapExtensionOptions> {
  name = "sproutKeymap";

  defaultOptions = {};

  // keys?(params: ExtensionManagerTypeParams<GType>): KeyboardBindings;
  public keys(): KeyboardBindings {
    const returnRule = (e: E) => (_state: any, _dispatch: any) => {
      return this.options.Enter
        ? this.options.Enter(e)
        : false;
    };
    return {
      Enter: chainCommands(
        returnRule({ commandModifier: false, shiftKey: false }),
        baseKeymap.Enter
      ),
      "Cmd-Enter": chainCommands(
        returnRule({ commandModifier: true, shiftKey: false }),
        baseKeymap.Enter
      ),
      "Shift-Cmd-Enter": chainCommands(
        returnRule({ commandModifier: true, shiftKey: true }),
        baseKeymap.Enter
      ),
      "Ctrl-Enter": chainCommands(
        returnRule({ commandModifier: true, shiftKey: false }),
        baseKeymap.Enter
      ),
      "Shift-Ctrl-Enter": chainCommands(
        returnRule({ commandModifier: true, shiftKey: true }),
        baseKeymap.Enter
      ),
      "Shift-Enter": chainCommands(
        returnRule({ commandModifier: false, shiftKey: true }),
        baseKeymap.Enter
      ),
    };
  }
}
```

Note this uses `chainCommands` to say that if the keypress is not handled it should pass onto the next handler; however we cannot determine what the next handler is so we just have to pass off to the default handler from `prosemirror-commands`. Maybe `keys()` should be passed the existing handlers?

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/remirror/blob/canary/docs/contributing.md)
      document.

**Comment by ifiokjr** [comment]
> Maybe keys() should be passed the existing handlers?

Sounds like the way forward. I started working on this and then got sidetracked. Looking at it today.
