### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by yyqx-dj** [remirror/remirror#2059]
### Summary
  Browser error： Uncaught SyntaxError: Unexpected token =
### Steps to reproduce

```
import 'remirror/styles/all.css';

import { BoldExtension } from 'remirror/extensions';
import { Remirror, useRemirror } from '@remirror/react';

export const MyEditor = () => {
  const { manager, state } = useRemirror({
    extensions: () => [new BoldExtension()],
    content: '<p>I love <b>Remirror</b></p>',
    selection: 'start',
    stringHandler: 'html',
  });

  return (
    <div className='remirror-theme'>
      {/* the className is used to define css variables necessary for the editor */}
      <Remirror manager={manager} initialContent={state} />
    </div>
  );
};
```

### Expected results

The editor is displayed

### Actual results

Browser error： Uncaught SyntaxError: Unexpected token =

![image](https://user-images.githubusercontent.com/65763530/236365331-d28ddc4e-12d2-429a-adbf-858b5703eeba.png)

**Comment by ocavue** [comment]
Could you share a minimal reproduction for this issue? You can start by picking one example from https://github.com/remirror/remirror-examples

**Comment by yyqx-dj** [comment]
I suspect that my version of Google Browser is too low. Is there a way to solve this problem?

**Comment by ocavue** [comment]
You can compile your application with your bundler (e.g. Webpack, Vite) to a lower target (e.g. ES6).
