### ISSUE TITLE
`create-context-state` ships incorrect types in `create-context-state.d.ts` causing typescript error "Type 'Context' is not generic."

### ISSUE THREAD

**Issue by ceisele-r** [remirror/remirror#2070]
### Summary

The package `create-context-state` ships multiple versions of types through the files `dist/create-context-state.d.ts` as well as `dist-types/create-context-hook.d.ts`, `dist-types/create-context-state.d.ts`:
![image](https://github.com/remirror/remirror/assets/54797986/5ea633ea-b22a-4810-9928-fe09675ab30a)

This causes multiple definitions for e.g. `CreateContextReturn` to exist (one in `dist/create-context-state.d.ts` and one in `dist-types/create-context-hook.d.ts`) with different signatures.

The definition in `dist/create-context-state.d.ts` seems to be wrong as it is declared as following:
```typescript
import { PropsWithChildren, ComponentType, Context } from 'react';

...

type CreateContextReturn<Context extends object, Props extends object = object> = [
    Provider: ComponentType<PropsWithChildren<Props>>,
    hook: ContextHook<Context>,
    DefaultContext: Context<Context | null> // The first "Context" should be used from the react import but is the Type parameter here is incorrectly being used as generic type. The react import is generic but not the Type parameter.
];
```
We can also see in the IDE that the Context import from `react` is unused here:
![image](https://github.com/remirror/remirror/assets/54797986/fd69cedc-1f29-4443-b623-6adfa7cf597f)

Comparing to the correct definition in `dist-types/create-context-hook.d.ts`, we can see that here, the correct import `Context` from the react import is being used as it was aliased to avoid name collisions:
```typescript
import { PropsWithChildren, ComponentType, Context } from 'react';

...
import React, { ComponentType, Context as ReactContext, PropsWithChildren } from 'react';

...

export type CreateContextReturn<Context extends object, Props extends object = object> = [
    Provider: ComponentType<PropsWithChildren<Props>>,
    hook: ContextHook<Context>,
    DefaultContext: ReactContext<Context | null> // Here the correct aliased ReactContext is used
];
```

As the incorrect type definitions are additionally shipped via `dist/create-context-state.d.ts`, this causes the following typescript compile error:
```
node_modules/create-context-state/dist/create-context-state.d.ts:76:21 - error TS2315: Type 'Context' is not generic.

76     DefaultContext: Context<Context | null>
```

### Steps to reproduce

1. Install `create-context-state` in a typescript project
2. Execute `tsc`

### Expected results

* Only correct types are shipped (`dist/create-context-state.d.ts` is not shipped with npm package as all type definitions are present in `dist-types/...`)
* No typescript compile error when using the package

### Actual results

* Incorrect types are shipped, see above.
* This was most likely caused by this commit https://github.com/remirror/remirror/commit/7b2c3928d064cc45f22fef3e2d8b5d1c5c697c3d

### Possible Solution

Remove `dist/create-context-state.d.ts` from the shipped npm package.

**Comment by ocavue** [comment]
> The package create-context-state ships multiple versions of types

The files in `dist` should be used. 

> The definition in dist/create-context-state.d.ts seems to be wrong

This seems to be a bug from [rollup-plugin-dts](https://www.npmjs.com/package/rollup-plugin-dts). I think we can try to create a mini reproduce for rollup-plugin-dts team so that they can fix the bug, or maybe we can try to rename the `Context` in our code so that we won't trigger this bug.

**Comment by ocavue** [comment]
Created issue in https://github.com/Swatinem/rollup-plugin-dts/issues/266

I will also rename `Context` on the remirror side while wait for the fix on the rollup-plugin-dts side

**Comment by ocavue** [comment]
`create-context-state@2.0.2` is released and should fix this.

**Comment by ceisele-r** [comment]
Thanks @ocavue , I can confirm I no longer see this specific error.
