### ISSUE TITLE
Add support for resizing images

### ISSUE THREAD

**Issue by hboylan** [remirror/remirror#209]
## Description

`@remirror/extention-image` supports the ability to drag and drop images into the DOM. It would be nice to have the ability to import images from URL or computer using a menu button as well. Also, I've seen prosemirror examples that allow image resizing in the editor that would be nice as well.

https://github.com/ifiokjr/remirror/issues/88#issuecomment-581413715

## Possible Implementation

First off, getting familiar with the monorepo. I'd like to dig in and start by adding the menu button first as that seems more straight-forward to implement than resizing.

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/remirror/blob/canary/docs/contributing.md) document.

**Comment by zhaoyao91** [comment]
alignment of image would be a nice feature :)

**Comment by tx0c** [comment]
and, can it have some input rules for markdown image syntax paste?

like when use type in or paste `![title](https://i.imgur.com/9wxMsKr.jpeg)` the ImageExtension should convert it to an image?

some site has this extended markdown already, user can specify like this `![title](./pic/pic1s.png =250x)` for a width, small/medium/large, and/or aligning

at least can have it as an option? like `new ImageExtension({ withInputRules: true })`

**Comment by ocavue** [comment]
Resizing image is already released. https://remirror.io/docs/extensions/image-extension
