### ISSUE TITLE
dependency library of @remirror/react and @remirror/pm is vulnerable

### ISSUE THREAD

**Issue by CeceliaYu** [remirror/remirror#2114]
### Summary

semver, the dependency library of @remirror/react v2.0.32 and @remirror/pm v2.0.6 is vulnerable:
[semver vulnerable to Regular Expression Denial of Service](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)

### Steps to reproduce
NA

### Expected results

Use later version of semver

![image](https://github.com/remirror/remirror/assets/5575493/a06bc0b7-4dd3-4824-b7ad-c6ecf0eebc1d)

### Actual results

<img width="646" alt="image" src="https://github.com/remirror/remirror/assets/5575493/0502653e-da8e-4691-846c-14173eb60d67">
<img width="646" alt="image" src="https://github.com/remirror/remirror/assets/5575493/d52fb140-7923-4620-9433-aaef9276ef8e">

**Comment by ocavue** [comment]
Remirror doesn't depend on `semver` directly. It's `@babel/helper-compilation-targets` that depend on `semver`. The latest `@babel/helper-compilation-targets` v7.22.9 already use the unvulnerable `semver` v6.3.1, so I don't see anything we need to do here. You might just need to remove your `node_modules` and lock file (e.g. `yarn.lock`) and do a fresh re-installing.
