### ISSUE TITLE
CodeBlockExtension / HardBreakExtension - bad interaction with shift-enter

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#218]
There's a few issues here; forgive me for bypassing the issue template.

All of these examples use the with-next example, on the `render-source` branch so the document model can be viewed. Reproduced at http://localhost:3000/editor/rich-social

(Shift enter is because we submit the message on enter, so shift-enter is required to gain a newline.)

## Swallowed keypresses

1. type `Hello: `
2. shift-enter
3. triple backticks
4. shift-enter
5. `sdfsdfsdf`
6. shift-enter
7. triple backticks
8. up arrow twice
9. type whatever you like; nothing shows and the document model does not change

GIF:

![Peek 2020-02-06 16-10](https://user-images.githubusercontent.com/129910/73955380-2bf9be00-48fb-11ea-84db-34214fa55755.gif)

## Cannot easily escape code block (without enter)

Setup is 1-8 above (yes, step 8 is definitely required), but then go back to the bottom and type whatever you like at the end; you cannot easily terminate the code block and go below it with normal text again _except_. Pressing enter escapes to normal text, but as mentioned above we cannot use this. Another escape hatch is using backticks and another shift-enter and more backticks.

![Peek 2020-02-06 16-17](https://user-images.githubusercontent.com/129910/73956250-952e0100-48fc-11ea-9d9e-ec770647a275.gif)

## Disappearing backticks

This can be seen in the two above examples. I think what's going on is it's using inline code rather than code blocks.

---

Potential solution: inline code should not be allowed to contain `hardBreak` elements.

Potential solution: inline code should not be allowed to contain already styled blocks (including other inline code).

Potential solution: after typing a backtick, no further text will be formatted until another backtick is seen.

---

I'd like to drop the HardBreakExtension but use shift-enter for newlines inside code blocks and new paragraphs outside. i.e. I want shift-enter to be equivalent to enter. Do you know how I might do this?

**Comment by ifiokjr** [comment]
I'll take a look at this sooooon.
