### ISSUE TITLE
Unable to use Remirror for SSR with ExecJS/Node

### ISSUE THREAD

**Issue by ericraio** [remirror/remirror#221]
## Description

When you process a React Application through Rails's ExecJS/Node, you'll receive the following error message.

```Error: secure random number generation not supported by this browser use chrome, FireFox or Internet Explorer 11```

This is happening because the nano library has a dependency that roots down to the [randombytes library](https://github.com/crypto-browserify/randombytes/blob/f18ded32b209f0d4c637608a11ae042ae96b4c2e/browser.js#L12)

In the randombytes library, it does a check to see if a function is defined and just throws the error.

## Possible Fix

I trailed the issue of where nano is being used to here, https://github.com/remirror/remirror/blob/b096ed1dd300d682e28f9a7721ad9debbe1c1eb3/%40remirror/core-helpers/src/core-helpers.ts#L579

One suggestion is to create our own unique ID generator.

**Comment by ifiokjr** [comment]
I'm not keen on modifying the codebase to (potentially) support what seems to quite an adhoc build process.

How are you planning on using ExecJS with `remirror`?

Additionally it looks like [support for node@6](https://github.com/rails/execjs/issues/64#issuecomment-466085193) and above is missing. `remirror` officially supports versions `>=10`.

**Comment by ifiokjr** [comment]
Turns out you were right. I've had some problems with `nanoid` in other parts of the code and I've removed it in the `next` branch.
