### ISSUE TITLE
.digital TLD not supported by LinkExtension

### ISSUE THREAD

**Issue by villesau** [remirror/remirror#2230]
### Summary

shook.digital is not linkified by LinkExtension. However, the latest `extract-domain` that LinkExtension uses seems to support it. I believe the culprit is outdated `extract-domain`. Maybe update it to the latest, 4.1.5 at the time of writing?

**Comment by whawker** [comment]
Actually this is because the Link extension supports the top 50 TLDs by default, to extend this you can

```ts
import { LinkExtension, TOP_50_TLDS } from 'remirror/extensions';
 
const extensions = () => [
  new LinkExtension({ autoLinkAllowedTLDs: [...TOP_50_TLDS, 'digital'] })
];
```
