### ISSUE TITLE
BubbleMenu positioner throws when view.state != newState

### ISSUE THREAD

**Issue by tomas-c** [remirror/remirror#224]
## Description

I set up the WysiwygEditor as a controlled component. It looks like this causes the BubbleMenu component call bubblePositioner.getPosition() when view.state != newState which ends up throwing an exception [here](https://github.com/remirror/remirror/blob/b096ed1dd300d682e28f9a7721ad9debbe1c1eb3/%40remirror/react/src/react-positioners.ts#L73) with message  "Error: Invalid position X" (where X is a number).

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

## Steps to reproduce

1. Clone https://github.com/tomas-c/remirror/tree/demo/bubble-positioner-throws
2. Start the next.js example and navigate to http://localhost:3000/editor/wysiwyg/content
3. Clear all content
4. Type some text
5. Select the text
6. Press menu button to make the selected text a bullet list
7. Observe error thrown

@ifiokjr Happy to submit a PR if you have any ideas for potential fixes

I tried modifying to bubblePositioner to use `const { from, to } = view.state.selection;` instead of `const { from, to } = newState.selection;` which prevents the error from being thrown but then the bubble menu location is not correct.

**Comment by ifiokjr** [comment]
Thanks for the well written issue. 

While there may be some simple fixes around this, I think the fundamental issue is around poor controlled editor testing and support currently. 

This is being addressed currently in the next branch #251.

**Comment by ifiokjr** [comment]
I'll start looking at reimplementing `wysiwyg` editor with the new API next week.   The new controlled editor support is more robust and I've rewritten the positioner to consume the `extension` API. 

Hopefully 🤞 it's all fine when I test it.

**Comment by ifiokjr** [comment]
This has been fixed in recent versions of the `next` branch.
