### ISSUE TITLE
Wrong indent of list item

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#225]
## Description

![Kapture 2020-02-12 at 22 42 17](https://user-images.githubusercontent.com/3808838/74345595-48a96080-4de9-11ea-9b3e-d15739e0ee2a.gif)

When the current item is indented and have no content, pressing enter would create an item with less indents.

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Just verified that this happens. It seems to be a general bug with prosemirror list items. Might take a deep dive in order to work out why it's happening. 

It only happens for me once the indent level is at least 2 levels deeps.

**Comment by ifiokjr** [comment]
This is the default behaviour for **ProseMirror** and to actually change it would be a new feature. There's an issue in the backlog #528 which address the `@remirror/preset-list` to add command chaining. It would be a better time to revisit this. 

I'll close this favouring the new issue.
