### ISSUE TITLE
Content not updated from the parent

### ISSUE THREAD

**Issue by nappalm** [remirror/remirror#2253]
### Summary
I have run into a problem with useRemirror, when a user changes page the content is different, however, remirror stays with the latest version 1 and when switching to 3 it stays with version 2, so on and so forth, offset by 1.

### Steps to reproduce

```
export default function NoteEditor({ content}) {
 console.log({content}); // 🗨️ the content arrives for sure, but useRemirror never changes it

  const {manager, state, onChange} = useRemirror({
    extensions,
    content,
    selection: 'start',
    stringHandler: 'html',
  })
```
```
  const notes = useSelector(selectNotes);
  const content = JSON.parse(notes.current?.content) : '';

return (
<NoteEditor content={content} />
)
```

**Comment by whawker** [comment]
By default Remirror does not work this way by design.

If you want this behaviour you should use a controlled editor https://remirror.io/docs/controlled-editor
