### ISSUE TITLE
isEnabled not implemented for bullet and ordered lists

### ISSUE THREAD

**Issue by tomas-c** [remirror/remirror#226]
## Description

If current selection is an ordered list, it's not possible to convert it to a bullet list by pressing the bullet list button. Yet the button is not disabled. This is because BulletListExtension and OrderedListExtension are using the default isEnabled implementation that always returns true.

## Possible Implementation

The following code solves this:

```
export class BulletListExtension extends NodeExtension {

  // <...> //

  public isEnabled({ getState, type, schema }: ExtensionManagerNodeTypeParams): CommandStatusCheck {
    return ({ command }) => {
      switch (command) {
        case 'toggleBulletList':
          return toggleList(type, schema.nodes.listItem)(
            getState(),
            undefined,
            (undefined as unknown) as EditorView,
          );
        default:
          return true;
      }
    };
  }

  // <...> //

}
```

Options:

1. Add the above isEnabled implementation to BulletListExtension and OrderedListExtension
2. Make the NodeExtension.isEnabled implementation always run the command without dispatch argument to determine if the command can be executed successfully (instead of always returning true).

I like the second option as:
* it's not possible to forget to implement isEnabled
* ensures that all other extensions correctly implement it

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Oh I like option 2 as well!
