### ISSUE TITLE
`aria-label` and tooltip of `HeadingLevelButtonGroup` incorrect in v3

### ISSUE THREAD

**Issue by mdmower-csnw** [remirror/remirror#2284]
### Summary

After updating to remirror v3 and using `<HeadingLevelButtonGroup />` from `@remirror/react-ui`, the tooltips have extra information that doesn't look like it belongs.

v2
![image](https://github.com/user-attachments/assets/85598f07-43dc-44f3-bb1b-c826cc5cdad3)

v3
![image](https://github.com/user-attachments/assets/5c84445a-d309-43c7-bd44-ff1bbf0099b8)

### Steps to reproduce

Add react component to a page:
```tsx
import {Toolbar, HeadingLevelButtonGroup} from '@remirror/react-ui';
...
<Toolbar>
  <HeadingLevelButtonGroup />
</Toolbar>
```

### Screenshot(s)

It looks like this affects `aria-label` as well.

v2
![image](https://github.com/user-attachments/assets/37c3b9bb-08cb-468f-badb-b370aa6ac91c)

v3
![image](https://github.com/user-attachments/assets/84a1981f-0ac9-423a-809d-cc8ee912c12e)

**Comment by whawker** [comment]
This is an intentional change from V2, translations are no longer provided by default (unless using out-of-the-box editors)

Restoring previous behaviour is [detailed in the migration guide](https://remirror.io/docs/migration-v3#restoring-the-previous-behaviour)

**Comment by mdmower-csnw** [comment]
Ah, I see, thanks for the help @whawker. Would it make sense for `i18nFormat` to be a required prop? Or do folks generally not need to define it?
