### ISSUE TITLE
Incompatibility between emojis and mention/tags

### ISSUE THREAD

**Issue by watlandc** [remirror/remirror#230]
## Description

Consumers are unable to insert a mention/tag directly after an emoji.  A space must be inserted after the emoji before a mention/tag (i.e. typeahead menu) will be recognized.

**To reproduce**
* Insert an emoji into the `social-editor`.
* Type `#` or `@` immediately after the emoji without adding a space.
* Mention/tag typeahead menu won't appear unless you insert a space first.

**Contributing**
- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
This is by design. 

By default the only valid prefix characters directly before the activation character are whitespace characters. 

https://github.com/remirror/remirror/blob/db20a731608970a4948fc97faf8c3a31bd6df333/packages/prosemirror-suggest/src/suggest-types.ts#L58-L81

This setting can be amended when creating the mention extension.

```ts
import {MentionExtension} from '@remirror/extension-mention';
import emojiRegex from 'emoji-regex';

const mention = new MentionExtension({
	/// Other options ...

	// Adds emoji characters the the valid prefix characters.
	validPrefixCharacters: '^([\\s\\0]|${emojiRegex().source})?$'
});
```

**Comment by ifiokjr** [comment]
Turns out that setting doesn't actually get passed through at the moment. I'll create a PR with the change.

**Comment by watlandc** [comment]
That's good to know that a feature by design and that it's configurable 👍 

I'm used to finding many small quirks in in our previous DraftJS implementation, thus I assumed it was a bug.
