### ISSUE TITLE
What's the standard/best way to disable the editor?

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#241]
I've searched the codebase with `disabled`, only found some of them in the menu item button.

I've thought aobut setting the `contenteditable` of the editor, but the root props are only applied to the wrapper of the editor, and it was not a style, so I can't override it with css.

Could you please give some hint or thought about this problem?

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by zhaoyao91** [comment]
I've had a hard wary to finally make out a workaround for this.
It's hard to use remirror as controlled component. So I made a helper component which expose remirror context upward via ref. And then, the parent component could listen to the onChange and if it is disabled, just set the content as the previous state to prevent any change:

```
import { ProsemirrorNode, toHTML } from "@remirror/core";
import { useRemirrorContext } from "@remirror/react";
import { FC, MutableRefObject } from "react";

export type RemirrorHelpers = {
  setContent: (content: any) => void;
  getPreviousContent: () => ProsemirrorNode;
  getContentHTML: () => string;
  getContentJSON: () => any;
};

type Props = {
  helpersRef: MutableRefObject<RemirrorHelpers>;
};

export const RemirrorHelper: FC<Props> = ({ helpersRef }) => {
  const { state, manager, setContent } = useRemirrorContext();

  helpersRef.current = {
    setContent,
    getPreviousContent: () => state.oldState.doc,
    getContentHTML: () =>
      toHTML({
        node: state.newState.doc,
        schema: manager.data.schema
      }),
    getContentJSON: () => state.newState.doc.toJSON()
  };

  return null;
};
```

**Comment by rafalp** [comment]
In WYSIWYM editors "disabling" editor is usually known as "making editor read-only", so try searching codebase for `readonly` ;)

**Comment by ifiokjr** [comment]
> I've searched the codebase with `disabled`, only found some of them in the menu item button.

@zhaoyao91 you should be able to set the prop `editable` to be `false` when creating the react component. 

https://github.com/remirror/remirror/blob/aa0fe5736e6da7cd1b3bb20223a4ee299ea5d1d7/%40remirror/react/src/react-types.ts#L88-L92

**Comment by zhaoyao91** [comment]
> > I've searched the codebase with `disabled`, only found some of them in the menu item button.
> 
> @zhaoyao91 you should be able to set the prop `editable` to be `false` when creating the react component.
> 
> https://github.com/remirror/remirror/blob/aa0fe5736e6da7cd1b3bb20223a4ee299ea5d1d7/%40remirror/react/src/react-types.ts#L88-L92

Great, this works. PS, the commands will continue to work with editable `false`, so users should disable the buttons too.

**Comment by ramvermilion** [comment]
https://remirror.io/docs/static-rendering/

editable={false}
