### ISSUE TITLE
Add class to editor when `autoFocus: true` for pseudo iOS support

### ISSUE THREAD

**Issue by watlandc** [remirror/remirror#261]
## Description

In testing the WYSIWYG Remirror Showcase, it appears autofocus is not working on iOS.

**To reproduce**
* Visit [WYSIWYG Showcase](https://docs.remirror.org/showcase/wysiwyg)
* Editor autofocuses on desktop, but not iOS

iOS does not allow focus to be set programmatically, but autofocus should work.  Autofocus is useful on mobile for a variety of cases (e.g. creating a social post). Falling back to a plain text editor on mobile is undesirable.

Of note, autofocus appears to work as expected on iOS in a TipTap demo giving a  positive indication that it is achievable.

https://tiptap.scrumpy.io/focus

https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/extensions/Focus.js

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
This should be fixed by #262

**Comment by ifiokjr** [comment]
Reopening, even though it works on the simulator, it doesn't actually seem to be working on device. I think it'll need a similar `FocusExtension` to make the functionality identical to `tiptap`.

**Comment by ifiokjr** [comment]
The new extension will be added as part of the new updated API.
