### ISSUE TITLE
mention-extension: add extraction of extraAttrs to parseDOM

### ISSUE THREAD

**Issue by lightpohl** [remirror/remirror#263]
Hello! We've recently started using Remirror and the `mention-extension` to create a new text editor. It's been working really well so far, and has been a big step up from what we were using before. 

## Description

We noticed when reinitializing a new editor from saved HTML that the custom attributes saved in the HTML for mentions were not being parsed, and that they would fallback to their default values. We use those attributes for some custom behavior, so it would be awesome if those could be preserved when parsed.

## Possible Fix

[Updating the `getAttrs` property of `parseDOM`](https://github.com/remirror/remirror/blob/3b9cee410ed597d4f7ad028cfe0fc668fcb10417/%40remirror/extension-mention/src/mention-extension.ts#L82) to parse out the custom attributes fixed the issue for us locally.

```
getAttrs: node => {
  if (!isElementDOMNode(node)) {
    return false;
  }

  const id = node.getAttribute(dataAttributeId);
  const name = node.getAttribute(dataAttributeName);
  const label = node.innerText;

  // Check node for our `extraAttrs`, and save them
  const extraAttrs: { [key: string]: string } = {};
  Object.keys(this.extraAttrs()).forEach(attrKey => {
    const nodeAttrVal = node.getAttribute(attrKey);
    if (nodeAttrVal) {
      extraAttrs[attrKey] = nodeAttrVal;
    }
  }, {});

  // Add our `extraAttrs` to the result
  return { ...extraAttrs, id, label, name };
}
```

Definitely would be happy to open a PR for this one, but I wanted to run the new behavior by the code owners first. 👍 

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for raising this issue, and I'm glad you're enjoying using remirror! There's a lot of work going into the codebase, so hopefully your experience keeps improving. 

There's actually a `getExtraAttrs` method defined on every `Extension` that provides the functionality you seek.

https://github.com/remirror/remirror/blob/9d13d46f29c9c02fe28408e34e5d71f3780344e4/%40remirror/core/src/extension.ts#L155-L180

It's being used in the the following places (for your example):

- `ParagraphExtension`

https://github.com/remirror/remirror/blob/9d13d46f29c9c02fe28408e34e5d71f3780344e4/%40remirror/core-extensions/src/nodes/paragraph/paragraph-extension.ts#L70-L73

- `ImageExtension`

https://github.com/remirror/remirror/blob/9d13d46f29c9c02fe28408e34e5d71f3780344e4/%40remirror/extension-image/src/image-extension.ts#L44

- and `LinkExtension`

https://github.com/remirror/remirror/blob/9d13d46f29c9c02fe28408e34e5d71f3780344e4/%40remirror/core-extensions/src/marks/link-extension.ts#L57-L61

For some reason I forgot to add it to the `MentionExtension`. I'll merge any PR you send that fixes the issue.

For a while I considered how this could be done automatically for all extensions that define `extraAttrs`, but I couldn't think of a simple way.

**Comment by lightpohl** [comment]
Thanks for a bunch for the code examples and letting me know about `this.getExtraAttrs`. The doc for contributing is really handy by the way--getting setup locally was easy.
