### ISSUE TITLE
Tab Key not working in code block extension

### ISSUE THREAD

**Issue by arpitchaudhari** [remirror/remirror#266]
I am not able to use tab key in the code block.

**Comment by ifiokjr** [comment]
Can you provide an example? A screenshot would be helpful.

**Comment by arpitchaudhari** [comment]
![tab](https://user-images.githubusercontent.com/29978858/76150630-83de3d00-60d2-11ea-84d3-d8c1ef17d5c8.gif)
When I use tab key, instead of giving space it is moving to url.
