### ISSUE TITLE
How to add a New Extension to Wysiwyg Editor?

### ISSUE THREAD

**Issue by arpitchaudhari** [remirror/remirror#268]
I am trying to add table extension in  menu bar in Wysiwyg but can't figure it out.

![IMG_6966](https://user-images.githubusercontent.com/29978858/76258225-2f28f680-6279-11ea-81b4-eb6fb7a67147.JPG)

File: https://github.com/remirror/remirror/blob/master/%40remirror/editor-wysiwyg/src/components/wysiwyg-menu.tsx

**Comment by ifiokjr** [comment]
I'm don't think support was yet added for this. I'd be open for a PR if you're happy to give it a go 😊

**Comment by ifiokjr** [comment]
I'm closing this as it's a question. Feel free to open it again if you feel the functionality should be added and have some ideas on how it can be done.
