### ISSUE TITLE
link extension should not select word on mod-k if there is already a selection

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#278]
## Description

![image](https://user-images.githubusercontent.com/3808838/78849969-8a9cfe80-7a48-11ea-96a4-b18376437de4.png)

This is a strange user experience. With some text already selected, mod-k should just apply link to this selection instead of try to select a word.

## Possible Fix

if there is selection, do not select the word

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
@zhaoyao91 I'm open to a PR. 

If you add the following to the beginning of the method in you PR it should fix the issue. 

```ts
// Only select the word if there's no selection.
if (!state.selection.empty) {
  return;
}
```
