### ISSUE TITLE
Remove JSDOM selection API warning

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#289]
Currently, `jest-remirror` will mock some methods from `EditView` and print a [warning](https://github.com/remirror/remirror/blob/jest-remirror%400.11.1/packages/jest-remirror/src/jsdom-patch.ts#L43) about "Test depends on DOM selection API which is not supported in JSDOM/Node environment".

In this [PR](https://github.com/jsdom/jsdom/pull/2719), someone added the implementation of selection API for JSDOM. This feature was shipped with [JSDOM v16](https://github.com/jsdom/jsdom/releases). So maybe we can remove this warning? 

Something that needs to be addressed:

- [ ] Does JSDOM really implement all the selection APIs we need?
- [ ] ~~The latest Jest (v25.3.0) is still using JSDOM v15~~, so we can't simply remove the mock and the warning from the codebase. We need to provide a way to detect the Jest/JSOM version. (update: Jest v26.0.0 is using JSDOM v16)

This issue is not important and should have a low priority. I just post it as a memo.

-----

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for posting this issue.

I'll fix it in the `next` branch. 

The questions you've asked are questions I keep asking myself. Jest is lovely to use but it's lack of real browser support is a massive cost for developing a text editor. The test suite doesn't provide enough assurance since most of the meaningful api's are being mocked insufficiently. 

A problem is that most of the other solutions lack the tooling of jest. I've looked at karma and mocha and while they can run in the browser, there are so many features that they don't have out of the box. 

I'm even tempted to have a go at building true browser support for Jest, either as a `testRunner` or as a fork. 

On another topic, I really like what you're doing with [rino](https://github.com/ocavue/rino). It should be added to a showcase on what's being built with remirror. 

It would also be useful to get your insights on what you'd like to see improved for upcoming releases. What's the best way to contact you?

**Comment by ocavue** [comment]
First of all, I'm really happy that you like Rino. It's my honor to add my project to what's being built with remirror. 

---

> I'm even tempted to have a go at building true browser support for Jest, either as a `testRunner` or as a fork.

During the development of Rino, I've written *a lot* of puppeteer tests because (1) it provides a true browser environment so I don't have to mock those API that missing from JSDOM environment (e.g. Selection API, localStorage) and (2) it provides a way to debug my code in the browser GUI with powerful devtools. I even wrote a plugin call [jest-puppeteer-istanbul](https://github.com/ocavue/jest-puppeteer-istanbul) so that I can collect the coverage information from my puppeteer tests. 

However, after using remirror (Rino is developed with pure Prosemirror at the beginning), I found that remirror has some awesome APIs for testing (`toEqualRemirrorDocument` for example). That's why I'm moving my test cases from puppeteer to `jest-remirror`.

Maybe we can build the test suite on the top of existed tools like puppeteer, [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer), [pptr-testing-library](https://github.com/testing-library/pptr-testing-library) to get the true browser support as well as the convenient APIs? However, in my own personal experience, which is very limited though, the current test suite works pretty well.

---

> what you'd like to see improved for upcoming releases.

Speaking of the upcoming release, I do have a small question. One of the best features of remirror in my own opinion is that I can collect all methods of a Prosemirror node into one single extension (the functions of `schema.toDOM` and `nodeView` are very similar. Why should I write them into different places?). I also add the other two methods (`fromMarkdown` and `toMarkdown`) in Rino since these two methods have a very strong connection to all other methods in the same extension.

An example of an extension [definition](https://github.com/ocavue/rino/blob/%40rino.app%2Fweb%400.9.1/src/editor/extensions/list/list-extension.ts#L52-L98) in Rino: 

```typescript
class RinoListItemExtension extends NodeExtension implements MarkdownNodeExtension {
    get name() { return "rinoListItem" as const; }
    get schema(): NodeExtensionSpec {}
    public keys({ type, schema }: ExtensionManagerNodeTypeParams) {}
    public nodeView() {}
    public fromMarkdown() {}
    public toMarkdown({ state, node }: NodeSerializerOptions) {}
}
```

The `next` branch is changing the extension API from *class* to *function*. So my question is: *can users add custom methods (`fromMarkdown` and `toMarkdown` in my case) into an extension with the new API?*

---

> What's the best way to contact you?

Maybe via my email since I check my email daily. You can get it from `git log | grep ocavue`.

**Comment by ifiokjr** [comment]
> That's why I'm moving my test cases from puppeteer to `jest-remirror`

That's a real encouragement. I'm glad the API is proving useful. 

> Maybe we can build the test suite on the top of existed tools like puppeteer, [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer), [pptr-testing-library](https://github.com/testing-library/pptr-testing-library) to get the true browser support as well as the convenient APIs?

This sounds like a good path forward. The only change would be to use [playwright](https://github.com/microsoft/playwright) for improved browser support. I'll monitor how it feels using the current test suite for the rewrite and if I run into too many mocking problems, I'll revisit the whole running jest directly in the browser idea. It would be amazing if it were possible without loss of tooling support.

> The `next` branch is changing the extension API from *class* to *function*. So my question is: *can users add custom methods (`fromMarkdown` and `toMarkdown` in my case) into an extension with the new API?*

Excellent question. This is something I've been thinking about a lot. After wrestling with multiple problems when using the extension factory pattern I've switched back to `classes`. I mention some of my reasons in this commit 45df7623cbe7e7996e09a314089187cdff16288a and the reasons are pasted below.

>The project has moved back to using classes. They're just much better for type inference than factory objects in typescript.
>
> - With a class I can infer the type of all the fields without needing to capture the type in a generic. The initial factory pattern had reached 6 generics at a certain point all which need to be captured to create good inference.
> - Classes are types and can be used without the `typeof` indicator.
> - Classes are inherently stateful which allows creators of extensions and presets to manage the lifecycle and state directly on the class. With the factory pattern I was just about to create a new state field where extensions could store state. This would have required another generic type parameter.
> - With the object parameter everything has to be passed into each method, since there's no access to `this`. Classes allow me to create a store object on the extension which has commonly used items like the `view` `prevState` `schema`.
>
> There are a few pitfalls to moving away from classes though.
>
> - `defaultSettings` and `defaultProperties` were really nice with the factory pattern. The extension factory could infer whether you needed to add defaults based on the shape of the `Settings` / `Properties`. With the new class syntax this isn't possible. Now the extension requires a static property on the Extension class. The value should be the right shape. However, this means a lot of mistakes can be made by extension creators. I want to create a plugin at `eslint-plugin-remirror` which produces an error when the wrong default settings / default properties are set. It also creates auto fixable suggestions which add the required type annotation and object shape.



Looking at what you're proposing how do you feel about the following. 

Some additions to the API mean that the `next` version will make it easier to do what you've suggested. 

### 1. Installation

Installing remirror has changed (improved? 🤷).

```bash
yarn add remirror # yarn
pnpm add remirror # pnpm
npm install remirror # npm
```

Note that all the scoped packages are now aliased as different entry points within the `remirror` package. 

- `@remirror/core` -> `remirror/core`
- `@remirror/react` -> `remirror/react`

It's for convenience and to avoid the need to install multiple packages when getting started. This will be the recommended method once the next version is published. Of course, you can still install from the scoped package if preferred.

### 2. Code

Firstly the new version provides lifecyle methods to the extensions which allow an extension to modify and augment the behaviour of the manager.

```ts
import {
  AnyExtension,
  AnyPreset,
  CreateLifecycleMethod,
  PlainExtension,
  Shape,
} from 'remirror/core';

import {
  buildParser,
  buildSerializer,
  FromMarkdown,
  Parser,
  Serializer,
  ToMarkdown,
} from './markdown-utils';

export class MarkdownExtension extends PlainExtension {
  public readonly name = 'markdown';

  public onCreate: CreateLifecycleMethod = (parameter) => {
    const serializerMethods: FromMarkdown[] = [];
    const parserMethods: ToMarkdown[] = [];

    return {
      // Loops through each extension during the first phase of the
      // manager lifecycle.
      forEachExtension(extension) {
        if (extension.fromMarkdown) {
          serializerMethods.push(extension.fromMarkdown);
        }

        if (extension.toMarkdown) {
          parserMethods.push(extension.toMarkdown);
        }
      },

      afterExtensionLoop() {
        const { setStoreKey } = parameter;

        const parser = buildParser(parserMethods);
        const serializer = buildSerializer(serializerMethods);

        // Add the serializer and parser to the manager.
        setStoreKey('serializer', serializer);
        setStoreKey('parser', parser);

        // Now the manager can be called with `manager.store.serializer` and
        // `manager.store.parser`.
      },
    };
  };
}

declare global {
  // This is a global namespace for remirror, similar to jest that allows you to
  // augment the types available to jest. This means that any extension has the
  // power now to improve the core functionality of remirror.
  namespace Remirror {
    interface ManagerStore<ExtensionUnion extends AnyExtension, PresetUnion extends AnyPreset> {
      /**
       * Parse content from markdown
       */
      parser: Parser;

      /**
       * Serialize prosemirror content to markdown
       */
      serializer: Serializer;
    }

    interface ExtensionCreatorMethods<Settings extends Shape = {}, Properties extends Shape = {}> {
      /**
       * Convert to markdown.
       */
      toMarkdown?: ToMarkdown;

      /**
       * Create from markdown.
       */
      fromMarkdown?: FromMarkdown;
    }
  }
}
```


Next we make use of a new feature, `Preset`s. A preset provides a wrapper for combining the behaviour of multiple extension together. In this case we are going to update some extensions with a `toMarkdown` and `fromMarkdown` methods. In some cases this might be easier than extending the class. These will be consumed by the 

```ts
import { Preset } from 'remirror/core';
import { ParagraphExtension } from 'remirror/extension/paragraph';
import { TextExtension } from 'remirror/extension/text';
import { MarkdownExtension } from './markdown-extension' 

export class MarkdownPreset extends Preset {
  public readonly name = 'markdown' as const;

  // Create extensions and manage with the preset.
  public createExtensions() {
    const paragraphExtension = new ParagraphExtension();
    const textExtension = new TextExtension();
	const markdownExtensoin = new MarkdownExtension()

    // create markdown parser and serializer for paragraphs.
    paragraphExtension.toMarkdown = function () {};
    paragraphExtension.fromMarkdown = function () {};

    // create markdown parser and serializer for text.
    textExtension.toMarkdown = function () {};
    textExtension.fromMarkdown = function () {};

	// etc...

    return [paragraphExtension, textExtension, markdownExtension];
  }

  // No properties are used here but can respond to updates in properties passed
  // into this preset and pass them to the properties.
  protected onSetProperties() {}
}
```

As you can imagine `Preset`s are very powerful and allow composing functionality in a simple but elegant way.

**Comment by ocavue** [comment]
Sorry for the late response. I haven't got the time to respond to your comment these days.

Thank you for your explanation of the new API. It's very detailed and I do understand the new API better.

----

Most changes in my option are pretty great. However, I do have a small question:

A `plainExtension` object could provide 3 lifecycle methods tho will be called during the initiation of the manager:

- `plainExtension.onCreate()`
- `plainExtension.onInitialize()`
- `plainExtension.onView()`

Each lifecycle method are actually made by two sub-methods: `forEachExtension` and `afterExtensionLoop`. So in fact an extension object can provide 6 lifecycle methods.

Is it possible to reduce the number of lifecycle methods? More specific:

- Can we remove `forEachExtension` and simply give `afterExtensionLoop` all extension instances as a argument? 

- Can we merge `onCreate` and `onInitialize` into one method? It's seems that a `EditorManager` object will call `this.onInitializeExtensionLoop` right after `this.afterCreate`.

I think I may miss something and I'm very happy if you can point out my mistake.

**Comment by ifiokjr** [comment]
> Sorry for the late response. I haven't got the time to respond to your comment these days.

Not a problem at all. That's actually the beauty of using **GitHub** for communication. It's asynchronous and there's never a rush.

> Can we merge onCreate and onInitialize into one method? It's seems that a EditorManager object will call this.onInitializeExtensionLoop right after this.afterCreate

This sounds like a great idea! `onCreate` is probably all we need. I was refactoring from the `master` branch, which uses the `initialize` method to pass in a state getter and other properties.

> Can we remove forEachExtension and simply give afterExtensionLoop all extension instances as a argument?

The reason I added the `forEachExtension` pattern is to help improve the startup performance of the editor. I've noticed that the more features I add the more it slows down. You can see that in the docs. There's a perceptible lag when using the editor and waiting for it to become responsive.. After that it seems to be okay. 

To help reduce this initialization lag in the `next` branch

- I've moved from using `map`, `filter` and `reduce` to relying on `for of` loops, which are faster, require less iterations and are often easier to read. 
- I added the `forEachExtension` pattern to prevent an explosion of extensions each looping through all the extensions.  

It's not the prettiest pattern but my reasoning is based on my assumption that the lifecycle methods aren't something most users will care about. Extensions can be consumed and created without ever needing to think of them. I think they help give power users and advanced extension creators a set of tools for customising `remirror` to their own needs.

Anyway, I'll think consider it some more. But that's my reasoning for this awkward pattern.

**Comment by ocavue** [comment]
> I've noticed that the more features I add the more it slows down. You can see that in the docs. 

Could you give me a reference link to the document?

**Comment by ifiokjr** [comment]
> Could you give me a reference link to the document?

This was the link https://docs.remirror.org/showcase/wysiwyg/

But turns out it's actually seems quite fast. Not sure maybe I was on a slower machine or mobile.

**Comment by ocavue** [comment]
> I added the `forEachExtension` pattern to prevent an explosion of extensions each looping through all the extensions.

I don't think there is much performance improvement by adding `forEachExtension`. 

For example, there are N extensions in total, and M extensions have lifecycle methods. 

- With `forEachExtension`, we will call `afterExtensionLoop`  M times and `forEachExtension` N*M  times
- Without `forEachExtension`, we will still call `afterExtensionLoop` M times. Each `afterExtensionLoop` method will accept an extension array with N items. So there are still N*M operations. 

Correct me if I'm wrong since I don't really understand, for example, how CPU works during a for-loop.

**Comment by ifiokjr** [comment]
I wrote a little [gist here](https://gist.github.com/ifiokjr/b49563482ae301bf31ccb1d2b7374982#file-for-each-extension-md) and would be happy to change my mind. I've pasted it into this reply for brevity. 

## Why `forEachExtension`?

For the sake of this example let's assume that all extensions implement all the lifecycle methods. With that assumption we can compare the reasoning behind the `forEachExtension` instead of the default `Inner Looping`

### Inner Looping

This style relies on the following lifecycle methods.

- `(unnamed)` - **+1**
- `onCreate` - **+1**
- `onView` - **+1**

`unnamed` refers to when the manager inspects each extension initially in order to determine which extension have the relevant methods.

So there are 3 lifecycle methods and each runs through all extensions.

There are **10** extensions and **3** lifecycle methods.

- **Best case:** 30 steps.

If each each extension needs to create its own loop over the other extensions then we now have a multiple of **10** for the worst case scenario. So within the `onCreate` and `onView` methods there are now **10** extensions looping through all **10** extensions.

- **Worst case:** 230 steps.

_**Reason:** 10 x 3: (calling each lifecycle method) + 10 x 10: (looping each extension per lifecycle method) x 2: (lifecycle methods)_

### `forEachExtension`

We effectively add an extra two lifecycle methods for a total of **5** steps.

- `(unnamed)` **+1**
- `onCreate` **+0**
  - `forEach` **+1**
  - `afterForEach` **+1**
- `onView` **+0**
  - `forEach` **+1**
  - `afterForEach` **+1**

With `10` extensions now the best case scenario is **50** steps

- **Best case:** 50 steps

However, since none of the lifecycle methods receive the full list of extensions they are forced to use the `forEachExtension` to implement whatever loop they needed. So there's are no extra steps.

- **Worst case:** 50 steps

### 100 extensions

There are already **20** extensions in the stripped down version of the remirror editor. **12** of them rely on the lifecycle methods. However, let's imagine a case for a huge editor with 100 extensions.

#### Inner Looping

- **Best case:** 300 steps
- **Worst case:** 20300 steps

_**Reason:** 100 x 3: (calling each lifecycle method) + 100 x 100: (looping each extension per lifecycle method) x 2: (lifecycle methods)_

#### `forEachExtension`

- **Best case:** 500 steps
- **Worst case:** 500 steps

<br>

## Conclusion

None of this probably matters. Browsers are very performant these days The performance bottle necks will probably come from loading `prettier`, or a 1mb json file to represent emojis. This just outlines the reasoning behind the `forEachExtension`.

**Comment by ocavue** [comment]
I don't understand this part:

> However, since none of the lifecycle methods receive the full list of extensions they are forced to use the `forEachExtension` to implement whatever loop they needed. So there's are no extra steps.
> 
> - **Worst case**: 50 steps

I write some sample code:

### Inner Looping

```typescript
class MyExtension extends Extension {
  onView (extensions: Extension[]) {
    // extensions.length === 10
    for (let e of extensions) {
      // step start
      this.#doSomethingHeavy(e)
      // step end
    }
  }
}

class EditorManager {
  public addView(view) {
    // this.#extensions.length === 10
    for (const extension of this.#extensions) { 
    	extension.onView(this.#extensions)
    }
  }
}
```

### `forEachExtension` (current implementation)

```typescript
class MyExtension extends Extension {
  onView () {
    return {
      forEachExtension: (e: Extension) => {
      	// step start
      	this.#doSomethingHeavy(e)
      	// step end
      }
    }
  }
}

class EditorManager {
  public addView(view) {
    // this.#extensions.length === 10
    for (const extension of this.#extensions) { 
      // this.#handlers.view.length === 10
      for (const { forEachExtension } of this.#handlers.view) {  
        forEachExtension?.(extension);
      }
    }
  }
}
```

In the examples below, both implementations will call `this.#doSomethingHeavy` 100 times so I don't see how to get "50 steps". Maybe we have different definitions for "step"?

**Comment by ifiokjr** [comment]
Oh wow! Yes you're right. I completely missed the fact I was doing that in the code. 😅

Haha, I must have been at my computer too long. I'll update the API in the next refactor in a few days.

**Comment by ifiokjr** [comment]
I'll close this since it's been addressed in the `next` branch.
