### ISSUE TITLE
Transform pasted content before parsing

### ISSUE THREAD

**Issue by lightpohl** [remirror/remirror#294]
## Description

I would love a way to transform pasted content before it's parsed by the editor. Currently, I'm seeing a clash between some pasted content and my implementation of the mentions extension, and if I was able to clean up the pasted HTML before parsing it could be prevented pretty easily.

## Possible Implementation

Naively, I think what I'm looking for is to surface ProseMirror's [`transformPastedText`](https://prosemirror.net/docs/ref/#view.EditorProps.transformPastedText) and [`transformPastedHTML`](https://prosemirror.net/docs/ref/#view.EditorProps.transformPastedHTML) to the Remirror manager. If there's a better solution you can think of definitely let me know.

If it is something you'd like to support, I would be up for PR-ing this behavior with your go-ahead. :+1: 

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
That would be excellent. I'm open to a PR. Let me know if you need any pointers. It's been a while since I looked at the paste logic.

**Comment by lightpohl** [comment]
Apologies for the delay! Realized a few days ago that while some of the ProseMirror props are not available on the top-level manager, they are available and easy to use via use of a Remirror extension.

Here's some example code in case anyone needs to do something similar. 👍 

```
import { Plugin } from 'prosemirror-state';

import { BaseExtensionOptions, Extension } from '@remirror/core';

const createTransformPastedHtmlPlugin = (ctx: TransformPastedHtmlExtension) => {
  return new Plugin({
    key: ctx.pluginKey,

    props: {
      transformPastedHTML: htmlString => {
		// manipulate HTML string here
        return htmlString
      },
    },
  });
};

export default class TransformPastedHtmlExtension extends Extension<
  BaseExtensionOptions
> {
  name = 'transformPastedHtml';

  public plugin() {
    return createTransformPastedHtmlPlugin(this);
  }
}
```
