### ISSUE TITLE
cannot add link when use cmd + a to select all content

### ISSUE THREAD

**Issue by zhaoyao91** [remirror/remirror#298]
## Description

in my app and the [wysiwyg editor showcase](https://docs.remirror.org/showcase/wysiwyg), when select content with `cmd + a`, and click the url button to add url, it has no effect.

other cases work well:
- `cmd + a` to select but use `cmd + k` to enter url
- use cursor to select all content and click the url button

![Kapture 2020-05-15 at 18 02 07](https://user-images.githubusercontent.com/3808838/82038527-3daae880-96d6-11ea-8adc-e24554853ddb.gif)

## Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/canary/docs/contributing.md) document.

**Comment by zhaoyao91** [comment]
I've found the problem is from here:
https://github.com/remirror/remirror/blob/remirror%400.13.1/%40remirror/core-extensions/src/marks/link-extension.ts#L107

When I remove the `(!isTextSelection(selection) && !isMarkActive({ state, type }))` part, it works well. But I am not sure if they have other purpose here.

**Comment by ifiokjr** [comment]
Thanks for such a well crafted issue, with a potential fix as well. I'm sure there was a reason for adding this guard, but it's not coming to my mind right now. Since tests don't fail, feel free to open a PR.
