### ISSUE TITLE
Using getPositionerProps with a popup menu

### ISSUE THREAD

**Issue by jhlabs** [remirror/remirror#300]
## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

I am currently trying to setup a popup menu that I am using with the mention plugin to correctly position itself at the beginning of the inserted suggestion item. I have looked at the emoji extension and tried to replicate the example, but the position values never change from the initial position. Here is how I setup the positioner:

```ts
import React, { FC } from 'react';
import {
  useRemirrorContext,
  defaultPositioner,
  GetPositionParams,
  popupMenuPositioner
} from '@remirror/react';
import { WysiwygExtensions } from '@remirror/editor-wysiwyg';
import { EditorWrapper } from '@remirror/editor-wysiwyg';
import { StyledEditor } from './editor.styled';
import { Mention } from '../mention';
import { MentionItem } from './mention-item';
import { SocialExtensions } from '@remirror/editor-social/lib/social-types';
import { useEffect } from 'react';

interface Props {
  showMentionSuggestion: boolean;
  setExitTriggeredInternally(): void;
  tags: MentionItem[];
  activeIndex: number;
  getMention(): any;
  isFocused?: boolean;
}

export const InnerEditor: FC<Props> = ({
  tags,
  showMentionSuggestion,
  activeIndex,
  setExitTriggeredInternally,
  getMention,
  isFocused = false
}) => {
  const {
    getRootProps,
    actions,
    focus,
    getPositionerProps
  } = useRemirrorContext<SocialExtensions>();
  useEffect(() => {
    if (isFocused) {
      focus('end');
    }
  }, [isFocused]);
  const onClickMention = ({ id, name, link }: MentionItem) => {
    const {
      range,
      suggester: { char }
    } = getMention();
    console.log(getMention());
    actions.updateMention({
      id,
      range,
      label: `${char}${name}`,
      role: 'presentation',
      href: `${link}`,
      replacementType: 'full'
    });
    setExitTriggeredInternally();
  };

  const { top, left, right, bottom } = getPositionerProps({
    ...popupMenuPositioner,
    positionerId: 'mentionPopup'
  });

  return (
    <EditorWrapper>
      <StyledEditor {...getRootProps()} data-testid="editor" />
      {showMentionSuggestion && (
        <Mention
          top={top}
          left={left}
          right={right}
          bottom={bottom}
          mentions={tags}
          activeIndex={activeIndex}
          onSelect={onClickMention}
        />
      )}
    </EditorWrapper>
  );
};
```

Any help on how to use the positioner would be highly appreciated! Thanks for a great library.

**Comment by ifiokjr** [comment]
Looking at the code, nothing is jumping out to me as an obvious error. Can you try removing the `right` and `bottom` props. I've found that over specifying the absolute position can sometimes create issues. 

Also do you have a codesandbox visible where you can replicate the issue?

**Comment by jhlabs** [comment]
Thanks @ifiokjr! Good to hear that it should be possible to use the `positionerProps` like this. It seems that when I console log the values for `top` and `left` that they never change from their initial value of `-99999`. I will prepare a sandbox later today.

**Comment by jhlabs** [comment]
I am sorry this took such a long time. I can't even get the simple example from the docs up and running on the codesandbox since I believe they are not updated with the latest version. I will close this for now and add a solution if I find one. This will be a great library once the `next` branch and documentation are ready!
