### ISSUE TITLE
Make wysiwyg editor a controlled component

### ISSUE THREAD

**Issue by qwwwpp** [remirror/remirror#301]
I am trying to create a component that can switch between plain text/markdown editor and WysiwygEditor editor. 
If I use defaultMarkdownParser and defaultMarkdownSerializer from prosemirror to convert the node , it will throw error every time I type markdown syntax(e.g. ```). Also, I won't be able to type anything, if I add `initialContent={defaultMarkdownParser.parse(text)}`

Here is the sample code.
https://codesandbox.io/s/jolly-hermann-fnt5b?file=/src/App.js

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Full and robust support for controlled components has been added here https://github.com/remirror/remirror/pull/308

I'll be integrating this into the social, wysiwyg and markdown editors over the coming days.

**Comment by ifiokjr** [comment]
Closing as duplicate #246
