### ISSUE TITLE
How to transpile map-obj is an es6 module in @remirror/core-extensions

### ISSUE THREAD

**Issue by hennessyevan** [remirror/remirror#305]
## Question

Hey, I know this probably isn't really related to remirror directly but there is an untranspiled es6 module in `@remirror/core-extensions` called `map-obj` that is somehow slipping through my webpack and babel transforms and killing browsers that don't support object rest spread in the process. This one line in my repro is what is causing it. https://github.com/hennessyevan/razzle-transpile-repro/blob/master/build/public/static/js/bundle.cac7c908.js#L24529

When I explicitly add `map-obj` to be included I get an error saying that the module doesn't have a default export which I think may be because it is also being transformed to cjs exports but remirror is requiring it as a default.

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for raising this issue. I'll take a proper look soon.

At a glance it may be to do with the `browserlist` configuration used by remirror.

**Comment by ifiokjr** [comment]
I hope you don't mind, I've been so busy with the `next` branch I haven't had a chance to look into this. How comfortable would you be at looking into a PR?

I've completely revamped the build system in the latest branch so hopefully stuff like this doesn't come up once it's ready.

**Comment by ifiokjr** [comment]
I've removed `map-obj` from the codebase in the `next` branch. So this won't be a problem once the release is made available.
