### ISSUE TITLE
jest-prosemirror docu: mention React dependency

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#317]
I just figured out that `jest-prosemirror` depends via `@remirror/core-types` on `react`, which isn't really convenient for non-React setups.

It would be great to state the React dependency in the README for `jest-prosemirror`.

PS: I love the idea of `jest-prosemirror`. Thanks for open sourcing!

**Comment by samuelnunoo** [comment]
Yeah, I'm not just realizing this as i'm getting an error 

`  Cannot find module '@emotion/core' from 'react-utils.js'`

**Comment by ifiokjr** [comment]
Oh yes, this was an oversight on my side. It's been* fixed in the upcoming version which will sit behind a `next` release flag. I can prepare a release soon if you're happy to test it out. 

The plan is to eventually move this package into its own separate repository.

**Comment by ronnyroeller** [comment]
Awesome. Thanks!

**Comment by ifiokjr** [comment]
@ronnyroeller It took longer than planned but a new version is available with the following.

```bash
yarn add jest-prosemirror@next
```
