### ISSUE TITLE
dist file is not correct.

### ISSUE THREAD

**Issue by DiamondYuan** [remirror/remirror#326]
## Description

![image](https://user-images.githubusercontent.com/9692408/86738108-61036b80-c067-11ea-8071-c1b64f404d30.png)

## Checklist

    "@remirror/pm": "^1.0.0-next.0",
    "remirror": "^1.0.0-next.1"

**Comment by ifiokjr** [comment]
Yeah there was a problem in the first release. Use `@remirror/pm@1.0.0-next.1`.

**Comment by ifiokjr** [comment]
@DiamondYuan I'm happy to provide guidance on the discord server https://discord.gg/C4cfrMK

I respond pretty quickly 😄
