### ISSUE TITLE
Cannot create editor

### ISSUE THREAD

**Issue by oliver-hoff** [remirror/remirror#328]
## Description

Following the instructions at: https://remirror.io/docs/guide/create-editor

I installed the packages:

`yarn add remirror@next @remirror/pm@next`

Whenever I try to run the example to create my own editor, this is the result:

node_modules/@remirror/pm/view/dist/pm.esm.js:15:25: Cannot resolve dependency '/Users/ifiokjr/Coding/kickjump/remirror/prs/packages/@remirror/pm/src/view.ts' at '/Users/ifiokjr/Coding/kickjump/remirror/prs/packages/@remirror/pm/src/view.ts'
  13 | // this solution could change but for now, it's working
  14 |
> 15 | module.exports = require("/Users/ifiokjr/Coding/kickjump/remirror/prs/packages/@remirror/pm/src/view.ts")

It seems as though there is an absolute path that is being used... 

Could you please help?

Thanks!

**Comment by ifiokjr** [comment]
Try now?

**Comment by ifiokjr** [comment]
See #326 for the fix
