### ISSUE TITLE
[next] expect(...).toEqualRemirrorDocument is not a function

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#338]
## Description

After I edit the Jest configuration as below,  `expect(...).toEqualRemirrorDocument` is still undefined.

```
/* jest.config.js */
 
module.exports = {
  setupFilesAfterEnv: ['jest-remirror/environment'],
  ...
}
```

## Version

jest-remirror@1.0.0-next.4

## Possible Fix

```
export const setupRemirrorEnvironment = () => {
  ...
  expect.extend(remirrorMatchers);
  ...
};
```

Remirror use `setupRemirrorEnvironment` to extend Jest `expect`. However, currently `jest-remirror/environment` doesn't call `setupRemirrorEnvironment` but only *exports* `setupRemirrorEnvironment`. So we should fix this issue by simply call `setupRemirrorEnvironment` in `jest-remirror/environment`.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ocavue** [comment]
`jest-prosemirror` should have the same issue.

**Comment by ifiokjr** [comment]
Oh good spot. Are you happy to create a PR?
