### ISSUE TITLE
[docs] Usage example uses non existent exports

### ISSUE THREAD

**Issue by bart-kneepkens** [remirror/remirror#341]
I'm trying the guide over at https://remirror.io/docs/guide/installation/, which has the following in the example code:

`import { RemirrorProvider, useManager, useRemirror, useExtensionCreator } from 'remirror/react';`

Upon running this will give the error `Attempted import error: 'useExtensionCreator' is not exported from 'remirror/react'.`, because no such export exists

**Comment by bart-kneepkens** [comment]
I'd be happy to fix this, btw, if you could add me as an assignee.

**Comment by ifiokjr** [comment]
Thanks for raising this @bart-kneepkens 

I completely forgot to change this when removing `useExtensionCreator()`. The recommended way now to create extensions is by using `new BoldExtension()` or whatever extension is needed.

I'd love a PR by the way.
