### ISSUE TITLE
usePositioner does not work with controlled editor

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#364]
## Description

I have created a minimal reproduction repo to show the problem here, https://github.com/tommoor/remirror-custom-blocks/tree/use-positioner (branch = `use-positioner`)

The yarn.lock was created minutes ago, should have all the latest copies of remirror/babel etc.

## To reproduce

- `git clone git@github.com:tommoor/remirror-custom-blocks.git`
- `git checkout use-positioner`
- `yarn install && yarn start`
- Type some text and select it, notice that no floating menu appears
- Comment out the value prop `value={value}` in `App.js`
- Type some text and select it, notice that the floating menu appears.

I'm at a loss as to what's causing this. Even more bizarre, the [identical code in playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABAEoCmAhgrrPsPgGIDCVArgM7EDKupuxzb9pADaCARuQDW+AL74AZtkxh8AHRDYyFVQG5lAOzRY81fACFMggCYBRAB49dLFJl3S5CpavVgU2BdgD0xHbEDk66-iLmFtp6BjgENACSXIIoCLb2js6u8ooqasTevjiBwaHO-igpaTH6GPHGABJkFii6AOYZIVkuMrkeBUV+pZlh-gAWLW3ttXFGNAAyKCy4AArqbAR97vlePsPoG8S4-qkrs-XzRIX7OOuYAG4oFsTYfMQAsqS6pO2v7yQhjh3qtMI5cGFXjkdp4bsUAupyLhaghnCt8FYABoAFSsADl2IkAPIE-AAXnwAG09Ph8LpiAB3fDNUitDpdcq6AAUAEpYDS6YzTFEOT1efyXIKmckhGlRWFxQL6Uylit1sRNordABdHS6PSyJi6ChhfAfEJMXnUAW01EOAiUpEoB7EeiKMDfCwsKibACCJpdbrAHt0Xu15PwrA4XB4XOANtp+EilkgciEbAlicTVVlCFTsnTvATtKNL2wqXp+cLmcTUh5eoT-n8+Gxk0jbHwWHBkOw+HGmEwkiEgkwDJYchw+Fw2Ak0ynbYQTF8IQIbEExBN2Ta8+I+GIrVwOAAdAm7eiaIf0FR17JKPh1LJXBSo6Du85XlyAOQiJgiETrz96z0U80QSfBUWDT1vXwJ0XSfdtiEBW5sC5K0yQAPmtSUsz9ANXXdKC42LRNkwsVNYOII9SK1LMsxzVI8xgvCj3otIaNoktQ1eCtiHI5jS24tpiHYrM6z1USgP1bD72OJcXC5YiAB5WgeGTZDJYAHxkFYAE91w0i9MCvfAbzvLsqjCVNP1IEQWHMJgeE-KgpCkdDiNpRSf1wQ8pI4rNnHoBjxA0tDMIgkMvSPQ92nadczEsXkpHcxNdP04AaFkZxcAAdWIFB2nGXA+IhQMCNDFgqKifAAH58G-KJP3wVMBNkISLGkJLpKzNyutokxksUiIHJ8nq-PwTzhucZLaQCoKQp5ckwrKyLoti4gZQYxLpvwVLiAMiddByvKCqKpiSvwyDypY6oEBqurSMa5quNa+l2pc5LRrG-BEgGobvOcT6OIm-7fK+2a0mC4BQvA5aKtW9cAFUuPLIStt6nDcD0vb0oOo78sK4rnQuiKKoElH6Tu+rLEeyNnrajqPu2hHfq8kalP8FTAfwSTaU6g0jU3FwX1eRwVn3AA1IQmGEkNfleBb40lM8HQeKXeB245JcEaXw2fNhOG4YSE1lv5sCPBBER4A3Y0Vji7XsU6ACl2BJI90FIbA2C5EcECETgcDlo8-lwZJCgUkAWFIF1ohAHkeQTOsBUkgVlfwALxm+P4IyjARhDEBBxFQ4gXUOhaMKwujHy5YuVyi3sADJ673EvcDro8LEwBB6Azjp9wV4im3wVYReWVcY13Q8TM7v3DxnLPMt7F4wEwYjU8j6OIxrw6jxWQ3287qLMGdkleXE2ifZngO-h345Q7AcP1-3VQqGPvEd+naYUFkHSuUfiw47PrzBMCZNha2ltXFu79DY82kFQSk2pk6SnULgOSxhVba3VunTOu5Op83CAAKnwTSfBLZxjLBhvUekh0YaHVIG0ccuA2z7iqJOT0MFdA6SnAOUQHsWD+AQOMdwu4qgyQAI5MB8BqE8Lh8H+D0KndgHphBWAPDgVMDAIzQ1tjQ88+Bg6EAHGsBQ6BxwyD1ohOEfhT4CmQaghS0llLOi5h5FS1AjzuP0YY+4JjEr4H8M48a5pdBMD8VzQanMk56ikHqBRSjBAqJYdgbKM50DoChBSLRKdQJ7jKD0L4PxTbZzYPkuWKEsS4gJMSAkMDU40HQdLKgWDe7wWFp7UeEs1bV1yWEEpptEG0lsdgeSCZFJIXhPcJ4ZZiIm1eBpIIoxnC9NeJ1Di9TsZrJWbRJpfwNLbOIJs2kATFKKOHAk2eoSRn+DGX4CZzxXifUktE4C9IbCGAIC8AsTBBAEBOco1RSSUlpOwFoEAUggA) seems to work fine.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks again for a clearly written issue.

This actually looks like it's a problem with controlled editors. The previous state is always identical to the current state. I should have a fix ready soon but meanwhile, if you're happy with a workaround take a look at https://github.com/tommoor/remirror-custom-blocks/pull/2.

Since `previousState === state` is always equal to true, the default `hasChanged` method always returns false, and the position is never updated.

Rather than using the default positoner the following also works

```tsx
import { bubblePositioner } from 'remirror/extension/positioner';

// In the component 
const { top, left, ref, bottom, right } = usePositioner({ ...bubblePositioner, hasChanged: () => true });
```

**Comment by tommoor** [comment]
A hacky solution is fine for now, many thanks

**Comment by ifiokjr** [comment]
I've created a new issue #365 which will track this, so I'll close this issue once you've verified that the hack works.
