### ISSUE TITLE
Add new package `@remirror/extension-native-bridge`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#37]
## Description

The goal of this project is to be an editor available on all platforms. Handling text in a WebView with bidirectional communication via React Native, Expo helps a lot in this regard.

`Flutter` and `NativeScript` could be looked at post 1.0.

## Possible Implementation

- Create a new package called `@remirror/native-bridge`
  - This extension will be responsible for handling bi-directional communication. It will take in events from the native layer via `window.onMessage` and post messages to the native layer via `window.postMessage`. 

**[STATUS UPDATE](https://github.com/remirror/remirror/issues/37#issuecomment-688686546)**

I'm looking for two or three sponsors who'd like to champion this feature. If you're not in a position to sponsor but would still like to see this integrated into **remirror**, please reply with your use cases and upvote this comment for more visibility.

It's something I really want to work on, but am also aware it's a big undertaking.

**Comment by tylercollins590** [comment]
Thank you for the great work on Remirror. How is progress coming with react native/expo support. I would love to use this in my cross platform apps

**Comment by ifiokjr** [comment]
@tylercollins590 thanks for your kind words and interest in this project. Native integration is still a goal. 

The main problem is deciding the best compromise for integration.

### `WebView`

My initial thoughts were to use WebViews for the bridge. 

The reasons I haven't rushed into it are the following.

#### Poor performance

React native WebViews on Android don't pass messages as quickly as I'd hoped. I should open an issue about this soon. 

- `iOS`: 1000 tiny messages back and forth takes 6 seconds - **167 messages/sec**
- `Android`: 1000 tiny messages back and forth took 30seconds (even fully built) - **33 messages/sec**

You can run this yourself by cloning the repository

```bash
git checkout native

yarn
yarn bundle:install
cd examples/with-react-native
yarn pod:install
yarn start # Seperate terminal
yarn ios
yarn android
```

Then click `Performance > start`

This doesn't even take into account that larger messages will possibly take longer to run.

#### Difficult setup

Setting up a native editor actually means setting up a new editor that runs in a WebView and communicates with the outside react-native instance. 

For this we need to:

1. Create a custom WebView only editor (UI interactions should happen from the native code). This may end up being very different from the web version to handle the cross channel communication 
2. bundle the editor you've created into a string for injection into the WebView
3. integrate this code into your react native editor with custom handling of commands and async isActive checks.

It just doesn't seem very elegant and so far I've stopped at point 2.

You can take a look at the current CLI for bundling webview editors in the [`native`](https://github.com/ifiokjr/remirror/tree/native) branch.

### `native-prosemirror-view`

A more elegant but more difficult solution would be to create a `native-prosemirror-view` which mimics the API of prosemirror-view but renders to react and listens to events which happen from the native code. 

It would be a lot of work and there would be a few challenges (like dealing with events happening over the bridge). But if executed correctly it should be more performant and provide a better DX than the WebView solution.

### Next steps

Although I've been stalling I think the best course of action would be to start with a WebView solution (approx a few weeks of development ) and once `Remirror` is more mature to explore the `native-prosemirror-view` solution which may take months to flesh out.

**Comment by mjsarfatti** [comment]
I was wondering if there was any development on the native side of things?

**Comment by ifiokjr** [comment]
I'd love to get it done. I'm in the middle of a rewrite at the moment, so between that, work and other things it's difficult to find the required time. Fingers crossed there's time to make build a sample during June.

**Comment by ifiokjr** [comment]
Okay, progress update. 

I'm pitching my current company to see if they'll give me a few weeks to work on this functionality. If that materialises then it will be part of the `next` release.

**Comment by ifiokjr** [comment]
**STATUS UPDATE:** 

I'm looking for two or three sponsors who'd like to champion this feature. If you're not in a position to sponsor it but would still like to see it integrated into `remirror`, please reply with your use cases and upvote the initial issue for more visibility. 

It's something I really want to work on, but am also aware it's a big undertaking.

**Comment by jsamr** [comment]
@ifiokjr If you are still considering a first step with a `WebView` based component, you might want to consider [webshell](https://formidable-webview.github.io/webshell/) to ease the implementation! There is also an interesting concurrent worth to mention, [lepont](https://github.com/kt3k/lepont). The main advantage I see:

- Abstraction layer over [bidirectional communication](https://formidable-webview.github.io/webshell/docs/implementing-features).
- Don't reinvent the wheel (cf [autoheight](https://formidable-webview.github.io/webshell/docs/autoheight)).

Disclaimer: I'm the author.

**Comment by ifiokjr** [comment]
@jsamr thanks for sharing the library. I'll definitely take a look when integrating the WebView implementation.

**Comment by willurmston** [comment]
Hey there, any updates on a timeline for RN support? I know y'all are rushing to get the beta out. I am working on rustling up some sponsorship cash. We are refactoring our text editor to use Remirror, which will run on web and React Native. Any time estimate you could give would be very helpful.

**Comment by ifiokjr** [comment]
@willurmston I started working on the implementation, but I paused the development for a few weeks. There's actually not much work remaining. I need to create a few examples. 

I'll keep you posted on the progress.

**Comment by willurmston** [comment]
@ifiokjr Wonderful, thanks for the update
