### ISSUE TITLE
new ReactPreset is called every render (@next)

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#370]
## Description

On the `next` branch `new ReactPreset()` is called every render, this causes extensions to be instantiated every time a key is pressed in the editor. 

There are no obvious problems that this creates other than making debugging more difficult and a hit on performance that will become noticeable as the number of extensions increases.

You can see this problem in action by putting a breakpoint inside the `createPlugin` or `constructor` call of any extension.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Dropping by to say thanks for opening this issue. Let me know if it hasn't fixed it fully. 

The fix was to wrap the instantiation of the extensions in a function call to prevent them being re-instantiated on every render.

Much better!
