### ISSUE TITLE
useRemirror:onChange callback isn't called in StrictMode

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#371]
## Description

I'm setting up a remirror editor with the `onChange` callback to capture the active state of the commands as explained in the [Usage example](https://remirror.io/docs/guide/create-editor/):
```javascript
const { commands, active } = useRemirror(() => {
  setActiveCommands({
    bold: active.bold(),
    italic: active.italic(),
    underline: active.underline()
  });
});
```

The `onChange` callback is correctly called if the editor element isn't placed within `<React.StrictMode>`. Yet, running it in StrictMode stops the callback from being called.

Reproduction case in CodeSandbox:
https://codesandbox.io/s/determined-breeze-ewjky?fontsize=14&hidenavigation=1&theme=dark

## Possible workaround

Remove React.StrictMode

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Forgot to say, thanks for opening this issue. I appreciate the effort that goes into it and it makes the codebase so much better.
