### ISSUE TITLE
commands.XXX.isEnabled returns old value in useRemirror:onChange()

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#372]
## Description

I'm setting up a remirror editor with the `onChange` callback to capture the enabled state of the commands:
```javascript
const { commands } = useRemirror(() => {
  setEnabledCommands({
    heading: commands.toggleHeading.isEnabled(),
    orderedList: commands.toggleOrderedList.isEnabled()
  });
});
```

This won't disabled the commands when the user took the action (e.g. disable heading when a block was changed to a list) but only during the next call of `onChange`.

Reproduction case: https://codesandbox.io/s/peaceful-wiles-mwbq2?fontsize=14&hidenavigation=1&theme=dark

## Workaround

Call `isEnabled` from within `setImmediate`:
```javascript
const { commands } = useRemirror(() => {
  setImmediate(() => {
    setEnabledCommands({
      heading: commands.toggleHeading.isEnabled(),
      orderedList: commands.toggleOrderedList.isEnabled()
    });
  });
});
```

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
@ronnyroeller Good spot. I've got a local fix. I was using the wrong event handler which was called before the state had actually been updated. As a result the checks are always one update behind and is the reason that `setImmediate()` was working. 

I'll push the changes in an hour or so.

**Comment by ronnyroeller** [comment]
👏  Great solution! Thanks
