### ISSUE TITLE
DropCursorExtension - Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#381]
## Description

**[Example playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDClsuQDKuVrnLCxE6SAVncuvqGOAREAEKYzPwAogAe7rykKJi8nuKYkjIKtPQ4KuTx5InJvCoARpH8gQYYIVYAkq7MKAhxCUkpad5ZirmqBe0lKihNLdXBxkQAqgLk2M285G1FHaki6Zm+vcr5hcUpKnz8cwvk47WT+AAS5Kz8KLycy-trXhk+2Up5AytDABa3e6Pc5GUL4AAiDHQtmI2FIOGeqy67x6OR2PxeKn4UIAtAhYfDsCC6kQADIoUi4RgKCgEdbdLZovLoGnkXAqZqU4mXahM7DUzAANxQx2wDgoAFlWLxWJw5uKqNscArGJgkrgSnNkZtPn0VH5zNUEClKfhogANAAq0QAck56gB5O34AC8+AA2vp8PhFgB3a6Ah5PParAAUAEpYF6feR-REooiShGo6kY-7Gqxmq0Q0nI9G-fgZqLTomUsn87H8OTKdTyLTy6mC5DMNCCQic2Xw-oALp6Xj6UR8cwlfASorECOEaPelQqfCWgEkCj4LDqzXYfB-TCYADW+EzzEwvtIYhw+Fw2DMO6D58X+PoRQIFGY5GHnQet485HuuBwADpp3wY1ElCCpcF-MBLBfUQLHwBRRBEN1HFVNcUjmUMAHIymIMoyhfDDwz7QDgNNIhjTAMBpX4UhLH8FBBQ8RCl0VPlQyIVhiF-KZ0H4NxyEgc9sGIRjCP0QCFFwWFUlDQDvQAHnuQU4PIUQXWAeCREpdgXzUogwIgqCVNg1cRhKASMNYMp4WYTjyAwywhCEAA+WTvXwOTsPAlJXLc-AUlsLMdzUycXScoCMkogRSD-X9OE4F9434CMhB8tytJ04AiFEFJcAAdXIFBOD+XABLohi-wqKJJwAfnwLDKgw-ABKOFSHm-YQUtTXzvRcrruu9MJUrk8pON-Xhev6+TPLG1LvX8wLgvDV0wvIyLqJizA4pfDMs2S2b8HS8hdNPXg8oKoqSv3YdypGTMWhqurKv4RrmtmUQ2sERzUomybvXqIaRq88ahum7y+v6+aWiC4AQpWiKqOi2L4vIIsTjavbwe6w7juy078sK4rSuu8g-xa+Z0aW2r6qiF6SDej6Ou+-apgB0HgcxqbRrB365t4AKocW5bwoohGNq28gbjuIM2PwF8GOYAToGEcNOp5g7cG0o7MpOs6CcusqSYBKXHhluXyAV-AlaESnHoapq6eOd7Fk+1XJp+36rmgVmufZ36PJ9-bIYQaHYeFtbEc25HJaBThTfIeWBIAJmV13fux7Xcd1i6iY1cqjZjuOE-wZPrfwKmntplqnfar6Ofwd3JquRPvaBhv5KxeiG9E1NOrE0oACp+69fv5z+ClhawRZTvC07WAeE9cEXb8RjPKj914dhz23ZgylYOEVAQP4JA8EZlIAR2IOg6wA1J+5UfQSIIJxKOYZhoh-HABLsV18FD4Bo0flYOUuBKDbipFCGiYcEaeCQhQXkXxsARj7N6CSUlf6AQUp3VymClLAD-Pg4BoDMDgJbKQZK+AVBt3cmOXgxAKEN2GopH63chB9kAc-A878V7YFypedA6AtRuj-gAk0BAMSrClDKOUG5YHkEkbKdCFprR2kdHabu3pAFEEFJmYSlh-J-GlHKGBzF4F9BYBwbgmAjihnESUeR0jCIULnOCc2bIPCL3HqcaMqDsDSQwaY5QAphSilcpFBR2A1K2JSPYuYqc3LaJslrBJwk4m81sAYx4Wt9GGPIHEqhckOGvy4b+DclCMEqACUwBgwS5jML7KwvuBRQT4EdhxZgT8X5vw-jwvhAjsA6BAEIIAA)**

There is a `TypeError: Cannot read property 'nodeType' of undefined` error thrown _sometimes_ as you drop an item.

![demo](https://user-images.githubusercontent.com/12195101/88460482-7bf91c80-ce6a-11ea-8712-dff1b1b62f4d.gif)

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for raising this as an issue. I'll look into why it's happening.

**Comment by timc1** [comment]
Thank you! 🙌

**Comment by ifiokjr** [comment]
I've decided to simplify the drop cursor extension for now by using the `prosemirror-dropcursor` plugin. The issue is fixed as a result in #398.

**Comment by timc1** [comment]
💯
