### ISSUE TITLE
HeadingExtension – extra dom attributes should be passed down to headings

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#384]
## Description

While trying to add a unique `id` to each node, I noticed that the attribute was not being added when inspecting the DOM.

## Possible Fix

Looks like `extra.dom(node)` should be passed down to `HeadingExtension`'s `createNodeSpec.toDOM` [here](https://github.com/remirror/remirror/blob/857fd4ddc13b151ea9983cb965452cf35bf1eb81/packages/%40remirror/extension-heading/src/heading-extension.ts#L79-L82) for passing any additional attributes, in my case when running into this, `id`. 

Maybe there is a reason for not passing through extra attributes?

Also, if/when additional attributes _are_ passed, I think we'll run into https://github.com/remirror/remirror/issues/385 😬

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Oh, that's true. It also needs to receive `extra.parse(dom)` so that it can parse the attributes from the document.
