### ISSUE TITLE
Setup `Documentation & Publicity` project

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#390]
## Description

One area that `remirror` falls short, is with inadequate documentation. It's a personal failing of mine and I've found writing particularly difficult of late. 

If there are any contributors who would like to help in this area, please reach out on the [discord channel](https://discord.gg/C4cfrMK) or reply to this issue. Your contributions and willingness to participate will be appreciated and I'll be there to help you to understand different parts of the API.

During the month of August (2020) I'm looking to invest a significant amount of time on the `remirror` project. One of those areas will be creating video content on how to create custom editors with `remirror`.

- [x] Create project for `Documentation`.
- [x] Add tasks and topics to address in the documentation 
- [x] Add tasks for video tutorials and documentation structure

This can be closed once these tasks are addressed.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by shakti64** [comment]
Hi im interested to contribute to this documentation project as I am recently done a certification and working also as a API writer in Singapore. If interested can discuss more on the project.

**Comment by ifiokjr** [comment]
@shakti64 are you able to join the [discord channel](https://discord.gg/C4cfrMK)?
