### ISSUE TITLE
Readme refers to non-existant preset-formatting

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#393]
## Description

Various points of the documentation refer to a preset "formatting", which doesn't seem to exists:
- https://github.com/remirror/remirror/tree/next/packages/%40remirror/extension-auto-link#alternatives
- https://github.com/remirror/remirror/tree/next/packages/%40remirror/extension-bold#alternatives
- https://github.com/remirror/remirror/tree/next/packages/%40remirror/extension-paragraph#alternatives

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks @ronnyroeller, good spot. Would you be able to open a PR to remove these occurrences?
