### ISSUE TITLE
Consider allowing the EmojiExtension suggestion popup to appear after just the leading colon is typed

### ISSUE THREAD

**Issue by emilschutte** [remirror/remirror#403]
## Description

(May not be a bug but just a design choice.)

I'd like the `EmojiExtension` to show the popup as soon as I type a single colon `:`. Right now it doesn't appear until I type a letter after the colon.

The emoji list is not super useful with no letters typed unless you show recently-used first, but somehow I still prefer the feel of it showing me a popup as soon as I type the colon. Might just be me.

## Possible Fix

I looked into what was happening and initially thought I needed to set `matchOffset` for `prosemirror-suggest` to 0, but actually it seems more like the `PositioningExtension` responsible for the popup is returning the default offscreen position because it gets false when it calls `hasChanged()` when the popup first appears.

I don't really have any ideas for a fix yet.

I'm happy to help with any fix, but I don't yet understand the root issue well enough.

## Checklist

- [X] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for opening this issue. The update should be live in less than an hour.

**Comment by ifiokjr** [comment]
Looks like emojis are matching mid word.
