### ISSUE TITLE
Allow user to exclude some extension when creating `CorePreset` 

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#408]
## Description

In a previous PR, `GapCursorExtension` was been added to `CoreExtension`, which make one of my test case failed. In this case, I use `add().fire({ event: "click", position: 2 })` to simulate a click, and this event is catched by `GapCursorExtension`. `GapCursorExtension` uses `elementFromPoint`, which is not implemented by `JSDOM`, so an error is throwed.

The error stack is as below:

```
    TypeError: root.elementFromPoint is not a function

      619 |             ),
      620 |         )
    > 621 |             .fire({ event: "click", position: 2 })
          |              ^
      622 |             .callback((content) => {
      623 |                 expect(content.state.doc).toEqualRemirrorDocument(
      624 |                     doc(

      at posAtCoords (../../node_modules/prosemirror-view/dist/index.js:371:18)
      at EditorView.posAtCoords$1 [as posAtCoords] (../../node_modules/prosemirror-view/dist/index.js:4781:10)
--->  at Plugin.handleClick (../../node_modules/prosemirror-gapcursor/src/index.js:60:23)  
      at ../../node_modules/jest-prosemirror/dist/jest-prosemirror-environment-06f525b8.cjs.dev.js:1341:63
      at EditorView.someProp (../../node_modules/prosemirror-view/dist/index.js:4737:40)
      at Object.fireEventAtPosition (../../node_modules/jest-prosemirror/dist/jest-prosemirror-environment-06f525b8.cjs.dev.js:1341:34)
      at RemirrorTestChain.fire (../../node_modules/jest-remirror/dist/jest-remirror.cjs.dev.js:743:23)
      at Object.<anonymous> (src/editor/extensions/list/__test__/list.spec.ts:621:14)

```

So I don't want to add `GapCursorExtension` when running this test. However, I can't stop `jest-remirror` to create an `CorePreset` instance, so I want to exclude `GapCursorExtension` when `jest-remirror` creating a `CorePreset` object.

## Possible Implementation

Currently, we have one `excludeHistory` option in `CorePreset`'s argument. Maybe we can extend this option to allow user to exclude all kind of extensions when creating `CorePreset`. For example, an `excludeExtensions` option with type `Array<'history' | 'gapCursor' | 'text' ... >`.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
> `excludeExtensions` option with type `Array<'history' | 'gapCursor' | 'text' ... >`

That sounds like a good solution.

**Comment by ocavue** [comment]
ok. I will submit a PR for this.

**Comment by ifiokjr** [comment]
Thanks for the PR. I'm now wondering if this could be generalised so that all presets support it. Similar to how all extension support some base options. 

It might lose the type support though.

**Comment by ocavue** [comment]
>  this could be generalised so that all presets support it

This may be overdesign. For two reason:

Firstly, we don't necessarily need this option for other presets.

`CorePreset` is special. The framework may force users to use `CorePreset` and may not allow users to use the inheritance of `CorePreset`. `jest-remirror` is an example for this case: it creates a `CorePreset` object implicitly so I have not an easy way to remove `GapCursorExtension`. 

But other presets are not special. I can easily inherit a preset class and rewrite the `createExtensions` method to remove or add extensions.

Secondly, I think this is only a few people who will need this feature.  Increase the complexity of all presets (both on implementation and on API interface) seems to be a bad choice. Maybe we can wait for a while to see if there are enough people who need this?
