### ISSUE TITLE
HorizontalRuleExtension – cursor should be placed below the created node

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#417]
## Description

**[Playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDClsuQDKuVrnLCxE6SAVncuvqGOAREAEKYzPwAogAe7rykKJi8nuKYkjIKtPQ4KuTx5InJvCoARpH8gQYYIVYAkq7MKAhxCUkpad5ZirmqBe0lKihNLdXBxkQAqgLk2M285G1FHaki6Zm+vcr5hcUpKnz8cwvk47WT+AAS5Kz8KLycy-trXhk+2Up5AytDABa3e6Pc5GUL4AAyKFIuEYCgoBHW3S2OR26Dh5FwKma0JBdSIVxwKAAXikmpRiMwlntVl13j0Ud9qf9CSTeE0ALTYClnEB6GqgqzUBnYWGYABuKGO2AcFAAsqxeKxOHMZVRtjhVYxMElcCU5rTNp8+io-OZqggUtD8NEABoAFWiADknPUAPLO-AAXnwAG19Ph8IsAO7XQEPJ5MlIACgAlLB-YHyCGIlFnqtY-HUomQ41WM1WpHeBmE8H8DMpac0yVi1nS5DobDyPCawHSwTsMTSXnyZSq9GY-oALp8-SiPjmEr4WVFYixwgJgMqFT4O0AkgUfBYHV67D4P6YTAAa3weeYmCDpDEOHwuGwZkP4Zva4QxHoRQIFEpE86DyfHnI9y4DgAB0C74BaiShBUuBAWAliUqIFj4AoogiN6jhatuKRzFGADkZTEGUZSUrhMYjlmAYQVaRAWmAYAKvwpCWP4KBih4aHrmqwpRkQrDEEBUzoPwbjkJAN5cuxZH6GBCi4K+qRRmBAYADz3GKyHkKInrAChIjQuwlLaUQ0GwfBmlIVuIwlGJuGsGUpCRPx5C4ZYQhCAAfEpAb4MpBEwSkXnefgKS2Pmh7aXOnrueBGT0QIpDAUBnCcJSKb8LGQiBd5+mGcARCiKSADq5AoJwfy4GJLFscBFRRHOAD8+D4ZUuH4GJRyaQ8AHCJlFFBfgnl9f1+BhFlynlPxQG8INw0qX5U1ZQGIVhRFMZetFtFxYxiWYMllK5vmGWLfgOXkEZV5ssVpXlZVE7VSMeYtA1TW1fwrXtbMohdYIblZTNs0BvUY0Tf501jfNAVDf1y0tOFwCRRtsUMQlSUpeQ5YnF1R1Q0Fp3nQVl0lWVFUnnd5DAR18xY2tjXNVE70kJ9309X9x1TMDENgzjPmc8dMMIHDCMxXRyM7Xt5A3Hc4Y8fglJscwYnQMIMa9QDAZ43lF24FdxO3bq1UAlLjwy3L5AK-gStCDTL0tW1jPHF9iw-ars3-QDVzQBzk0pG7-W+d7vB87woWw6t63C1tKO7WjktApwJvkPLYkAEzKy7AMa-lRVEzdpP6+ThtxwnSf4KnVv4LTr0Mx1jvdb93O+8NVzJ17oONz5Khqb7UlZr10mlAAVAP-oDyufxQsLWCLGyMVsqwDyXrga4ASM14MSevDsDeB7MGUrDYKQKgIH8EgeCMGkAI7EHQTagakA8qPoVEEE49HMMw0SATgYl2F6+BC8ABMz8rDKlwJQA8MIGDoCYhHZGzEyaeHQhQIUXxsCxj5AGWS8l-5gVUqxdueD1LAGAiQ0B4DMCQMwNAjK+AVDt2Gv7UGQcQ4CzDlFWB8VgL7g7KyMk3JsZqxOrgAyZ1NYE21jnEmVUC4si7MwHs5Bnp0zenbGuzN64A3od5K42BW5TQIdOXgxBaG+3Gl3BMPchB8mAa-U8n9V7YEKnedA6B9TegAUAy0BAfgvHlIqZUu4kHkD8UqHCtoHTOjdM6HulEvFWDFHmYg5BLAhT+AqZUiDOIoL6CwDg3BMBHCjD41YISAlkVocuAAImbDEHgl4T1OAmBMWDsAKVwdk5QooJRSi8nFUJ2BtLFJKKUuY6dvIJOYEk7SEykljKWsHNJjxRGpPSeQMZBDbHv3sUBXcdD+5BXGh0pgDBulzH+pY8iBQBQOz4swF+b8P5f0cc41x2AdAgCEEAA)**

Currently a few extensions, `HorizontalRuleExtension` & `HardBreakExtension`, use [`state.tr.replaceSelectionWith`](https://github.com/remirror/remirror/blob/d877adb3e52a85bbccb0342fc21bf7f1937d5190/packages/%40remirror/extension-horizontal-rule/src/horizontal-rule-extension.ts#L34) when inserting new nodes. The expected behavior for these nodes should be to set the cursor below the created node.

In the playground, you'll see the expected behavior if you type some text, place the cursor somewhere between the text, then press the `Hr` button.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for opening the issue. I'll take a look at this later today.
