### ISSUE TITLE
v1.0.0-next.16 – PositionerExtension broken from Positioner not exported

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#441]
## Description

The latest next.16 release exports `Positioner` as a type, whereas it should be exported as a module. This breaks the newly updated `extension-positioner`.

Also as a followup, default tests should probably always import from the root of the package to reflect how it would actually be used.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
Thanks for raising. I've got a fix ready and will push it up in a few minutes. There should be a new release at some point in the next few hours.
