### ISSUE TITLE
HorizontalRuleExtension – unnecessary extra lines

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#451]
## Description

**[Playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDClsuQDKuVrnLCxE6SAVncuvqGOAREAEKYzPwAogAe7rykKJi8nuKYkjIKtPQ4KuTx5InJvCoARpH8gQYYIVYAkq7MKAhxCUkpad5ZirmqBe0lKihNLdXBxkQAqgLk2M285G1FHaki6Zm+vcr5hcUpKnz8cwvk47WT+AAS5Kz8KLycy-trXhk+2Up5AytDABa3e6Pc5GULXHAoABeKSalGIzCWe1WXXePRyOx+LxUfwh0N4TQAtNh4WcQHoaqCrAAZFCkXCMBQUAjrbpbdF5dCM8i4FTNOkgupEajs7AMzAANxQx2wDgoAFlWLxWJw5rKqNscGrGJgkrgSnMUZtPn0VH5zNUECk6fhogANAAq0QAck56gB5F34AC8+AA2vp8PhFgB3a6Ah5PJElAAUAEpYAGg+RQxEos9VnGE6kk6HGqxmq0oylM4mQ-gZtLTumY-HS8n8DS6QzyEyS9my1dcTD83CEdXi7H9ABdcn6UR8cwlfByorEOOEROBlQqfD2gEkCj4LC6-XYfA4zAAa3w+eYmGDpDEOHwuGwZkPEZv64QxHoRQIFARk86DyfHnI9y4DgAB0i74JaiShBUuBAWAlgIqIFj4AoogiD6jjajuKRzNGADkZTEGUZQIrhsajtmgYQdaRCWmAYCKvwpCWP4KDih4aEbuqIrRkQrDEEBUzoPwbjkJAN7EuxZH6GBCi4K+qTRmBgYADz3OKyHkKIXrAChIh0uwCLaUQ0GwfBmlIduIwlGJuGsGUpCRPx5C4ZYQhCAAfEpgb4MpBEwSkXnefgKS2AWh7afOXrueBGT0QIpDAUBnCcAiqb8HGQiBd5+mGcARCiDCADq5AoJwfy4GJLFscBFRRPOAD8+D4ZUuH4GJRyaQ8AHCJlFFBfgnl9f1+BhFlynlPxQG8INw0qX5U1ZYGIVhRFsbetFtFxYxiWYMlCJ5gWGWLfgOXkEZV74sVpXlZVk7VSM+YtA1TW1fwrXtbMohdYIblZTNs2BvUY0Tf501jfNAVDf1y0tOFwCRRtsUMQlSUpeQFYnF1R1Q0Fp3nQVl0lWVFUnnd5DAR18xY2tjXNVE70kJ9309X9x1TMDENgzjPmc8dMMIHDCMxXRyM7Xt5A3HcEY8fgCJscwYnQMIsa9QDgZ43lF24FdxO3Xq1UAlLjwy3L5AK-gStCDTL0tW1jPHF9iw-ars3-QDVzQBzk0pG7-W+d7vB87woWw6t63C1tKO7WjktApwJvkPLYkAEzKy7AMa-lRVEzdpP6+ThtxwnSf4KnVv4LTr0Mx1jvdb93O+8NVzJ17oON95-ug0HIcC2HUUR6LDwUHgnbYFC3bML25DY2rJ24AZZ2awT2s5yTVUF+GxtEKb5tl9bdNvXbNfM-XAPt0FVzYK3U3t+Nam+1J2a9dJpQAFSvwGr+rn8tLC1giz4hiviVgQ8-z4AAiMa8DETy8HYDeTAkQyisGwKQFQCA-gSA8CMDSABHYgdAWygVSK-FQ+gqIECcPRZgzBoiARwGJOw3p8BC2AImchVgVS4EoAg+kDB0BMQHvFTw6EKDCi+NgOM5JAyyXkswsCqlWK3zUoQYCqjOHcMwLwzA-CMr4BULfGcvBiB6N9nfRRiZH5CHJOwyhp5aGQOwIVO86B0AGh9CwthVoCCYlWAqJUKo9wiPIH45UOE7SOhdO6F0j9KJeKsOKfMxByCWBCn8RUKphGcTEX0FgHBuCYCONGHxJQQkBLInolcAARM23IPC4B-peU4iYZHYAUvI7JygxSSmlF5OKoTsDaWKSkUpcx07eQScwJJ2kJlJLGUtYOaTHiL1Sek8gYzb62OofYoCe59HyJUB0pgDBulzH+pY8iBRKQOz4swChVCaF0Mcc41x2AdAgCEEAA)**

Click `Hr` a few times and notice extra lines getting appended

<img width="837" alt="Screen Shot 2020-08-07 at 10 16 10 AM" src="https://user-images.githubusercontent.com/12195101/89654696-06904180-d897-11ea-81bd-3737d5f4e7fb.png">

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
I've found a fix for this and it's merged in the latest version, but please take a look at #524 for information on a known Chrome bug.
