### ISSUE TITLE
Create floating menu components

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#453]
### Description

Floating menu components include.

- Bubble menu on selection (with positioner API)
- Bubble menu on selection (with popperjs)
- Inline menu (for showing menu at the start of the line).

**Comment by Bertg** [comment]
FYI ChakraUI uses popper internally as well to position their "floating" components. 
If you need some inspiration on how it can be done: https://next.chakra-ui.com/docs/overlay/tooltip

I've seen their code and it looks pretty good. IMO the entire ChakraUI is quite neat.

**Comment by ifiokjr** [comment]
@Bertg I've decided to follow this suggestion. I was a bit nervous since the bundle size is quite large, but the alternative is redoing a lot of the brilliant work they've done.

**Comment by Bertg** [comment]
@ifiokjr You mean adopting ChakraUI entirely ?

**Comment by ifiokjr** [comment]
Literally 10 minutes after posting, I realized that it didn't really make sense. Instead, I've decided to borrow some of their components and combine them with [`react-aria`](https://react-spectrum.adobe.com/react-aria/why.html) which seems to fill in some gaps for full accessibility.

**Comment by Bertg** [comment]
@ifiokjr I was just surprised that's all. I think it could make sense. They have - as you said - done a lot of work. But so have you on your existing components. I think it would also not be in the best interest of this project - and it adoption - to have a strong preference for one UI framework or an other.

I was just mentioning that the usage of Popper in ChakraUI is pretty wel done. And they do a lot of things very wel (especially there state mgmt via components, the optional controlled states, hooks etc...)

But, I would really like to see it though :) I think it is rather amazing. A `chakra-remirror` package would be a-mazing :p

**Comment by bishwenduk029** [comment]
Has this feature been released? I was not able to find any documentation for it may be I missing something. Any help would be great
