### ISSUE TITLE
Add prebuilt editors to the playground

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#455]
### Description

When working with the playground you should be able to select 3 different types of editor.

- [ ] A social editor without immediate UI but with basic formatting, dropdown mentions and dropdown actions.
- [ ] A basic editor with a top menu and some formatting.
- [ ] A full WYSIWYG editor with everything included.

**Requires:** #452 #453 #407

**Comment by whawker** [comment]
Closing as we have removed the playground
