### ISSUE TITLE
Set up pre-publish e2e test with verdaccio

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#471]
### Description

Use [verdaccio](https://verdaccio.org/) to prevent deployment errors caused by forgetting to bump a package or add a changeset. 

- [ ] run `pnpm publish --dry-run` to check the packages that have changed and will be deployed.
- [ ] start verdaccio and make it the default npm registry for the duration of the action.
- [ ] build the project and deploy only the packages which have changed to verdaccio via `pnpm publish`.
- [ ] Copy the example `with-next` package to a seperate folder outside the monorepo. Install, build and start the server.
- [ ] Run the `e2e` test suite against this test server.
- [ ] Add TypeScript tests to make sure types are always valid.

If all passes then I can have a high confidence that a release will not be buggy.

**Comment by juanpicado** [comment]
:) ...... I'd love to help here.

**Comment by ifiokjr** [comment]
> :) ...... I'd love to help here.
@juanpicado 

That would be amazing! Let me know how I can assist. I'm available on the [discord server](https://remirror.io/chat) all day today and tomorrow. 

I also think this links well with #497. Especially the first task. The plan is to create an action that runs on every push to the default branch and checks if any packages are releasable. 

It should generate an array of releasable packages with the following properties:

 - `name: string` - the package name.
 - `version: string` - the new package version.
 - `changelog: string` - the changelog contents of the latest version.
 - `commits: string[]` - commit SHA's for release comments.
 - `issues: string[]` - issue ids for release comments.
 - `prs: string[]` - pull request ids for release comments.

The `verdaccio` action can run by waiting for this releasable action to complete, checking to see if the array is not empty and publishing each `name` and `version` to the `verdaccio` registry.
