### ISSUE TITLE
Misleading code documentation for matchOffset (MentionExtension)

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#485]
## Description

I want my MentionExtension to show suggestions whenever the trigger character is entered. Yet, it would show only when entering one additional character, e.g. `@a` instead of `@` alone.

I followed the docu in the type definitions via `MentionOptions` > `MentionExtensionMatcher` > `Suggester`, where it states that the default value is 0:
```javascript
    /**
     * Sets the characters that need to be present after the initial character
     * match before a match is triggered.
     *
     * @remarks
     *
     * For example with `char` = `@` the following is true.
     *
     * - `matchOffset: 0` matches `'@'` immediately
     * - `matchOffset: 1` matches `'@a'` but not `'@'`
     * - `matchOffset: 2` matches `'@ab'` but not `'@a'` or `'@'`
     * - `matchOffset: 3` matches `'@abc'` but not `'@ab'` or `'@a'` or `'@'`
     * - And so on...
     *
     * @defaultValue 0
     */
    matchOffset?: number;
```

Yet, that's not the case for the MentionExtension:
https://github.com/remirror/remirror/blob/4b4307bfd039a83dca885640704654d0b23f9747/packages/%40remirror/extension-mention/src/mention-utils.ts#L19

## Possible Fix

Remove the `@defaultValue 0` from the code documentation.

@ifiokjr Happy to file PR if you are agree with this approach.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

**Comment by ifiokjr** [comment]
> Happy to file PR if you are agree with this approach.

Oh yes, please do. 

This is a problem I've had a lot with extending interfaces. There are often subtle differences between the original type implementation and the type at the point of consumption. In this case it's the `defaultValue` that differs, but in other cases it can be that the explanation for a property no longer makes sense in the new location. 

I've used a pattern in the code base of defining single property interfaces a lot and then composing these together as needed to maximise reuse. This optimises the development flow for contributors but is detrimental to the consumers of the library.

I'd love for TypeScript and VSCode intellisense to support a way of overriding the docs manually when further explanation is required. This would also be helpful for automated generation of docs.

Something like this would be great.

```ts
interface MyInterface extends SchemaParameter, ProsemirrorNodeParameter {
  /**
   * @property schema
   * 
   * This schema should only be used in urgent situation.
   * 
   * @defaultValue `EditorSchema.empty`
   * 
   * @inheritDoc schema
   */

   /**
   * @property node
   * 
   * The node that will be replaced.
   */
}
```
