### ISSUE TITLE
New package @remirror/extension-tables

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#49]
## Detailed Description

Allow for the creation of advanced tables.

## Possible Implementation

`@atlaskit` has a pretty great implementation that can be copied from.

**Comment by ocavue** [comment]
@ifiokjr Do you have any recent plan to implement `@remirror/extension-tables`. If not, I can submit a PR for it.

BTW, when you say "`@atlaskit` has a pretty great implementation", do you meems [ProseMirror/prosemirror-tables](https://github.com/ProseMirror/prosemirror-tables)? It seems that the code maintainer of this package is  from Atlaskit.
