### ISSUE TITLE
Create custom release action using `changesets`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#497]
### Description

It's possible that this should be split up into separate actions for each of the following steps. Actions can now listen for specific workflow runs and retrieve the output.

- [ ] Use `npm --dry-run` to check which packages are ready to be released and create a JSON array of 
  - `name: string` - the package name.
  - `version: string` - the new package version.
  - `changelog: string` - the changelog contents of the latest version.
  - `commits: string[]` - commit SHA's for release comments.
  - `issues: string[]` - issue ids for release comments.
  - `prs: string[]` - pull request ids for release comments. 
- [ ] Use `pnpm release` to publish packages to npm.
- [ ] Get changelog, name and version output from the first task and publish the GitHub release.
- [ ] Add comments to PR's, issues and commits touched by the release.

**Comment by whawker** [comment]
@ocavue I think this is also done?

**Comment by ocavue** [comment]
@whawker  I don't think all features in the issue description have been implemented, but I do agree that the current release workflow is good enough for us. So I'm going to close this.
