### ISSUE TITLE
Rename `areSchemaCompatible` to `areSchemasCompatible`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#500]
### Description

> `areSchemaCompatible` is a kind of awkward name
> Maybe `areSchemataCompatible`...
> `areSchemasCompatible` is fine

This was from @benjie on discord who knows a thing or two about schemata as the creator of [postgraphile](https://github.com/graphile/postgraphile).

This will be a breaking change.

The function is defined in `packages/@remirror/core-utils/src/core-utils.ts`.

**Comment by benjie** [comment]
:+1: Most native English speakers don't know the plural of schema is schemata, let alone people who don't have English as a first language. `schemas` is more comfortable and intuitive for most.

Side note: with the name `areSchemasCompatible`, it implies that `areSchemasCompatible(a, b) === areSchemasCompatible(b, a)`; if that's not true then a better name should be chosen to imply the order of precedence.
