### ISSUE TITLE
Bold italic via markdown does not terminate bold as expected

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#505]
### Summary

After entering `_**Bold italic**_` into editor, when you continue typing text is still bold.

### Steps to reproduce

1. Enter the below into remirror playground
2. Type the following characters at the end of the editor: `**_ more words`

```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "paragraph",
        "content": [
          {
            "type": "text",
            "text": "Here's _**bold italic"
          }
        ]
      }
    ]
  },
  "playground": {
    "m": 0,
    "a": [],
    "e": [
      {
        "module": "remirror/extension/bold",
        "export": "BoldExtension"
      },
      {
        "module": "remirror/extension/italic",
        "export": "ItalicExtension"
      }
    ],
    "p": []
  }
}
```

### Expected results

_**Bold italic**_ more words

### Actual results

_**Bold italic**_ **more words**

**Comment by ifiokjr** [comment]
What a great format for this issue. It took me less than 2 minutes to verify the bug and once a fix is available it'll also be verifiable via the **playground**. Love it 😊
