### ISSUE TITLE
Publish the `next` preleases using the npm `latest` tag

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#507]
### Description

The next branch is quickly catching up in quality to the `0.x` releases. It may soon make sense to release the `preleases` as the default npm tag.

_This is an idea and if you are strongly for or against it, I'd be interested in your opinion._ Normally, I would create a discussion first before adding this to the backlog but in this case I'm happy for feedback. 

This should only happen when the following criteria are met:

- [ ] All currently active bugs have been fixed or discarded. 
- [ ] A migration guide exists for those wanting to transition from `@remirror/pm`.

This depends on #476 and #501 and blocked by #508.

**Comment by whawker** [comment]
Obsolete
