### ISSUE TITLE
Create backend database for storing shorter playground links

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#510]
### Description

This was suggested by @benjie during a recent call.

The playground is proving to be a great way of sharing bugs and documentation. The persistent URL functionality works well in most cases. 

There are two problems with the current implementation. 

- URL's can be very long especially when using the **advanced editor**. This causes problems with certain browsers which limit URL character length. It even breaks `discord` UI which tries to display the whole URL when clicked cutting off the proceed button.
- The URL doesn't persist the editor content due to the fact that it would make the URL's even longer. 

A way around that would be to deploy a database backed service which saves the JSON representation of the playground state along with hashed content as the primary key. 

When the playground is accessed with a link like `https://remirror.io/playground?data=123alphanumerichash123` the hash is referenced in the database and the relevant data is returned.

**Comment by ocavue** [comment]
Closing this because playground thas been removed
