### ISSUE TITLE
`active` doesn't change for an uncontrolled editor in strict mode

### ISSUE THREAD

**Issue by pnfcre** [remirror/remirror#518]
### Summary

`active` doesn't change for an uncontrolled editor in strict mode.

### Steps to reproduce

- Open this CodeSandbox: https://codesandbox.io/s/aged-dream-lfz8k?file=/src/App.tsx.
- Mark the text and make it bold.

### Expected results

`active` should become true.

### Actual results

`active` is false.

### Additional context

It works if strict mode is removed, or if the editor is converted to a controlled one.

### Possible Solution

?

**Comment by ifiokjr** [comment]
Thanks for raising this issue. I'm focusing on bugs today so fingers crossed 🤞 I'm able to get a fix released today.

**Comment by ifiokjr** [comment]
Okay, I've fixed this locally. I'll push it up soon.
