### ISSUE TITLE
Add extension to support highlighting text and linking

### ISSUE THREAD

**Issue by denisnazarov** [remirror/remirror#522]
### Description

Creating links is core editor functionality. It would be great to be easily add support for creating hyperlinks to the editor.

**Comment by ifiokjr** [comment]
[**Playground Link**](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIgCFMzPwAogAeuOS8pCiYvA7imJIyCrT0OCrkYRFRMSoARgH8HgYY3lYAMii8ANah4ZHRsSLxiS6KqaoZddm8KsyVVUVexkTUKcqMDABuKPzk2JZk5ACyrLysnHMLFKNKOHFOSW3KKq7mRfoIMaQEQQAaACpBAHIAygCSAPKv+AC8+AAUAEpfgA+fAAbV45AA7vgKtValkGkDLFDYf5Aoj6jEgQBdPS8fQqABUxP0+GJ+HuAAsUKR8JcSlDeARLizWJV6bhqeR8OR+ChcHtVoJVux8EKArlWNhSCoENSJLzBfgFABHYh0cikAB05OJKguVwILzArGYzCCAqF2EgNnsfyBoMI5IZxqsG1wlEwmFwE0w6FIlkZZoE9JEf0WO3aQIJroUuGI2Fi-1d+HwAB4BZMQWn05ncsRcELYjFbH0EFUfsAnT8wSGRbqhZxOMxyBj+EChCD8oEM3kiyXc7F8+mM4XizF8GWK1Wa8C626wKH+LriOh+KxwvCqv8iIryKI7QByanFwOQFQqTg+1vkHWM4-CQHdgDit7bAEJ+xOh3mx7+U4ziglbVrW9YJCua4blu5A7nu+AHke+CnuepCXtegrUsQuQPgkJxHGkyS7NgT5CC+IKvoKAASOHfgOk68MOo5jtmhA6hxnrer6-qBl2+AqMx+b9tmQmAgSQhxrwbLXPgprmpa1o4AA6tgrDoOgcy-ACC5gsAroyQQnRIjEKxrBs2DaYsZnrHM-x3I8ryfK84n6AZ7pEJM5rEOQlhltSqwbA4kbbIR2AsBw3CYHwnbGdivA2RZ4kCSo+AACLkG24QSrS9J9FCbkjgmSYpnmGbRuMUwzHM-74KGtnYNWcXdIlcxCLVXnMD51adT57UjqO-mBeQ1ZDbwGz9aOQmjhm8kWlagp7IJZUqBVTBVbM2BiRJUkZEYBCzKIrDEMwJpmvNSnYKp6madgBIgEIQA)

If I understand correctly what you're asking for is already available. I'm adding functionality in the future to make it easier, but it's possible already.
