### ISSUE TITLE
Add playground entrypoint for frameworks, extensions and presets

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#545]
### Description

Currently, the configuration of the playground exists within the playground itself. Part of the ongoing work for the playground is to make it more extensible and configurable. 

To help with this, extensions can define the options they make available so that the users of the playground can see how they should be used.

- [ ] Create `/playground` entry point for each package. In this case it will use preconstruct and be set up as a folder with a package.json. But it should support both `/playground.js` and `/playground/package.json` => `/playground/dist/awesome.esm.js`.

Add the configuration object to all current extensions, presets and the `@remirror/react` package.

**Comment by whawker** [comment]
Closing as we have removed the playground
