### ISSUE TITLE
Editor autofocuses on page load with autoFocus=false on Chrome

### ISSUE THREAD

**Issue by kennethacohen** [remirror/remirror#588]
### Summary
The editor I've built seems to receive focus on page load, and ignores the `autoFocus` prop when passed. 

Update: this appears to happen on Chrome, not Safari, and only occurs on a hard refresh. Client-side transitions are fine. You can see this behavior on this page: https://remirror.io/docs/guide/create-editor/

### Steps to reproduce
Here is the component code:

```js
export function Editor({
  initialValue,
  onChange,
  ...rest
}: EditorProps) {
  const manager = useManager(EXTENSIONS)
  const handleChange = useCallback(doc => onChange(JSON.stringify(doc)), [])

  return (
    <RemirrorProvider
      manager={manager}
      initialContent={initialValue ? JSON.parse(initialValue) : null}
      onChange={parameter => {
        handleChange(parameter.getRemirrorJSON())
      }}
  autoFocus={false}
    >
      <InnerEditor {...rest} />
    </RemirrorProvider>
  )
}

function InnerEditor({
  multiline,
}: InnerEditorProps) {
  const { getRootProps } = useRemirror({ autoUpdate: true })
  const [focus, focusSet] = useState(false)
  const handleFocus = useCallback(() => focusSet(true), [])
  const handleBlur = useCallback(() => focusSet(false), [])

  return (
    <Wrapper
      onFocus={handleFocus}
      onBlur={handleBlur}
    >
      <StyledEditor
        {...getRootProps()}
        multiline={multiline}
      />
      <Backdrop active={focus} />
    </Wrapper>
  )
}
```

### Expected results

- Passing autoFocus={false} should work
- I would expect the default behavior to *not* focus (i.e. autoFocus isn't set), but this Editor seems to receive focus no matter what.

### Actual results
Stated above

### Possible Solution
Very possible I've set something up wrong here in my usage of the component! Apologies, if so.

**Comment by kennethacohen** [comment]
You can actually see this behavior on this page:
https://remirror.io/docs/guide/create-editor

On page load, the editor is focused + Chrome scrolls to the editor position. This isn't happening on Safari.

**Comment by ifiokjr** [comment]
Oh, that's an interesting bug. I'll take a look at it, although for me setting the **autoFocus** to false seems to work okay. But I haven't looked at it in detail.

**Comment by ifiokjr** [comment]
Okay, figured it out. It seems that with chrome setting `autofocus="false"` will automatically focus it. The only way for the input not to autofocus is for it not to have the `autofocus` field attached. I'll release the updates soon. But you should be able to try the link now and see the fix.

**Comment by kennethacohen** [comment]
@ifiokjr FYI I'm seeing this error on that link now, not sure if this is expected. Thx for the fix! Will give it a go shortly.

![image](https://user-images.githubusercontent.com/2354611/91501315-5b6e1900-e893-11ea-9235-52e1170618e5.png)

**Comment by ifiokjr** [comment]
Yeah, something I introduced here seems to have broken the gatsby build - #591
