### ISSUE TITLE
`RMR0000` error with versions `^1.0.0-next.28 || ^1.0.0-next.29`

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#602]
### Summary

I updated my application from `^1.0.0-next.27` to `^1.0.0-next.28`/`^1.0.0-next.29` and I saw this error in the console.

### Steps to reproduce

Open https://5f48c19b24ed6422a5ac5d93--rino.netlify.app/ . Sign in with `rino_test_02@test.rino.app` and `awesome&password`. Check a note from left sidebar and you should able to see the error in the console.

### Expected results

No error or an error with more detail. 

### Actual results

`RMR0000` error

### Additional context

N/A

### Possible Solution

N/A

**Comment by ocavue** [comment]
copy from the discord:

> Thanks for raising this, I was hoping 29 would fix it. The issue is probably from these seemingly innocent lines of code https://github.com/remirror/remirror/blob/1d9492bd6efb29bb118514c8d7010c8658217c98/packages/%40remirror/react/src/react-helpers.tsx#L23-L28 which throw an error if the manager doesn't include the required presets.
But thinking about it now, I think that's actually not good. Since there's actually some very good reasons not to want to use the default extensions. If you create an issue, I'll look to fix it as a priority. Better yet, open a PR removing those lines of code.
I'll release version remirror@1.0.0-next.30 as soon as possible.

**Comment by ocavue** [comment]
Based on the quote above, it should raise `INVALID_MANAGER_EXTENSION` (which is `RMR0014`). However, it raise RMR0000 and I don't know if it is by design.

**Comment by ifiokjr** [comment]
> Based on the quote above, it should raise `INVALID_MANAGER_EXTENSION` (which is `RMR0014`). However, it raise `RMR0000` and I don't know if it is by design.

In a production build, errors are stripped away. For security, I guess. It's something I've seen other libraries do, so I copied it. Perhaps I should turn it off.

Here's the link description - https://remirror.io/docs/errors#rmr0000

**Comment by ocavue** [comment]
> For security, I guess.

That's reasonable.

**Comment by ocavue** [comment]
I do see the `RMR0014` in development mode.
