### ISSUE TITLE
`examples/with-next` depends on unpublished @remirror/testing

### ISSUE THREAD

**Issue by ankon** [remirror/remirror#612]
### Summary

I'm trying to follow https://github.com/remirror/remirror/blob/master/examples/with-next/readme.md#getting-started, but am hitting "road blocks".

### Steps to reproduce

0. Preconditions should be mentioned:

    a) `yarn` will fail unless `pnpm` is installed globally (`npm install -g pnpm`, or any other way suggested by https://pnpm.js.org/en/installation)
    b) One needs a reasonably current NodeJS (yarn checks the `engine` field, and that's a good thing!).

1. `yarn` will fail even with `pnpm` available because @remirror/testing doesn't seem to be published into any registry:
    ~~~~
    yarn install v1.22.5
    warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
    info No lockfile found.
    $ pnpm symlink:root && pnpm check:pnpm
    Scope: current workspace package
    
    > root@ symlink:root /home/andreas/project/remirror
    > node support/scripts/symlink-root.js
    
    
    Successfully symlinked the `support/root` files to the root directory.
    
    Scope: current workspace package
    
    > root@ check:pnpm /home/andreas/project/remirror
    > node support/scripts/check-pnpm.js
    
    [1/5] Validating package.json...
    warning root@: The engine "pnpm" appears to be invalid.
    [2/5] Resolving packages...
    warning @changesets/cli > tty-table > smartwrap@1.2.5: Backported compatibility to node > 6
    warning @manypkg/cli > get-workspaces > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1:    https://github.com/lydell/resolve-url#deprecated
    warning @manypkg/cli > get-workspaces > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see    https://github.com/lydell/urix#deprecated
    error An unexpected error occurred: "https://registry.yarnpkg.com/@remirror%2ftesting: Not found".
    info If you think this is a bug, please open a bug report with the information provided in "/home/andreas/project/remirror/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    ~~~~

### Expected results

> After a few seconds you should receive a [ ready ] message, and a URL to open such as http://localhost:3000. You can use the links at the top to visit different examples:

### Actual results

"Stuck", see output above.

### Possible Solution

Right now it seems the @remirror/testing package should be published, or maybe a different reference type could be used. I'm new to pnpm though, so this is just conjecture until I get things working :)

**Comment by ankon** [comment]
```diff
diff --git a/package.json b/package.json
index d03a4bf1..f6d7e512 100644
--- a/package.json
+++ b/package.json
@@ -108,7 +108,7 @@
     "@manypkg/cli": "^0.15.0",
     "@manypkg/get-packages": "^1.1.1",
     "@preconstruct/cli": "^1.1.25",
-    "@remirror/testing": "^0.0.4",
+    "@remirror/testing": "./packages/@remirror/testing",
     "@size-limit/preset-big-lib": "^4.5.7",
     "@testing-library/jest-dom": "^5.11.4",
     "@types/jest": "^26.0.10",
```

With this change I can get past `yarn` and `yarn build`. 

---
That said, I guess the actual problem is the link that got me here in the first place: The documentation at https://docs.remirror.org/introduction/ points to the examples/with-next directory on the master branch, but it seems this doesn't exist on the `next` branch, and the docs on the next branch don't point to the example anymore (or look even remotely related!).

I guess the big issue here is:
1. The docs on remirror.org are built from the master branch, which
2. ... is outdated since forever.

I can close this issue and create a new one, or repurpose this one to fix the docs to get built from the correct branch, which would be better?

**Comment by ifiokjr** [comment]
Yeah, if you check out the `0.x` branch and try the same thing then it should work. Let me know if it doesn't. 

The latest docs are available [**here**](https://remirror.io/docs).

I would, however, recommend that if you're starting with `remirror` today, to use the `@next` version. It's where my time will be focused going forward. 

The default branch is `next` and here `pnpm` is the only way to install, since the `remirror` relies heavily on the new features to manage the codebase. Installation is blocked with anything other than `pnpm`.

**Comment by ankon** [comment]
Actually I'm going to close this: See #613. 

Yes, I really want to start with the current thing! :)
