### ISSUE TITLE
Add notice to `docs.remirror.org` to redirect to `remirror.io`

### ISSUE THREAD

**Issue by ankon** [remirror/remirror#613]
### Summary

I'm trying to use remirror, and the first step was to "read docs and set up development environment". So, I typed in "remirror" into my favorite search engine (ecosia.org), and ended up on `docs.remirror.org`. The first page already says "look at the code, here's a link to an example" ... and nothing worked: See #612. 

Turns out: The remirror homepage isn't `docs.remirror.org`, it's actually remirror.io.

### Steps to reproduce

Search for "remirror" in the common search engines.

### Expected results

Results clearly show how to find the documentation.

### Possible Solution

Ideally: Make remirror.org and remirror.io point to the same content, or maybe make docs.remirror.org a redirect, or at least point to remirror.io?

**Comment by ifiokjr** [comment]
Thanks for the notice. I'm not sure about setting up the redirect right now. For now, a notice will be enough. If you're happy to create a PR into the `0.x` branch I'll happily merge. 

Otherwise, I'll get to it in a few days.
