### ISSUE TITLE
insertHorizontalRule command inserts in the wrong position

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#620]
### Summary

Using `commands.insertHorizontalRule()` adjacent paragraph nodes are split

### Steps to reproduce

- [Load Playground](https://remirror.io/playground#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIgAkcKABemLy4rMyUxMzkAKIAHrjkvKQoIQ7imJIyCrT0OCrkCUkpISoAFgHBoeEAtNhR5B4GGN5W1LnKjAwAbij85NiWZOQAsqy8rJwDQxTtSjjpTtmKeaqu5k36CCGkBDEAGgAqMQByAMoAkgDy5-gAvPgAFACU9wB8+ADavOQA7vj+bBBEJhCINeKJZKpXgvAC6el4+hUACpkfp8Mj8IcyihSPhti0fqF8SDWChkvhcGVyPhyPwULgFuNBON2JTMJhmAAjVjYUgqBBlCQ0hn4BQAR2IdHIpAAdOjkSotjsCGcwOFmDF6YzsJAbPYHi93oR0STkj58FNcJQObguph0KRLAT1QI8SIHsM5qsXgjTdtzfhyRQ8JFovcTOQ3LLhrYNTyEABrR7kbpJAh3D7AU34XO0tOhWXoBQF3AAEXIolYUVwvpzedT6dluwd9vQk1YuGhdd4ebzLuZcuDA1wgOB1TB0R7uaElk+A7dsOe+lNClwxGwvce9YAPPTum967m9yhuoRZRerTbMHaGI6XiIVIfe338DuucRcIzeyFbMwUEmdzAMOoYNEIbwXMkI47ioH5fiEz59jB+6IfgzwIkIfq8AGuz4GqGpagyOAAOrYKw6DoAMEZGpmJovjhBCFJCJS8GMExTNgEbDGxkwDI8BzHOc1znOhK70SqVjdOExDkJYv5lOMUwOJ6swrJ0GjcJgfD8CmRRQiEPEceh+AqCo+AVtEiSUjieL-j8Ym5muG5bru3qdD0fQDEe+Curx2BAUxxTQoZAxCN5UnMDJQERTJYUvn28mKeQQGJbwUxxX2qFIfhzCatqCxPruKhuUwHn9NgqGibwmFiYURgEP0VY1nh6q5YROqkeRlHYAiIBCEAA)
- Type a couple of paragraphs
- Attempt to add horizontal rules with the button

### Expected results

Horizontal rules are created at the root of the doc

### Actual results

Horizontal rules split existing paragraph tags, seemingly randomly

### Additional context

![Kapture 2020-09-01 at 17 46 56](https://user-images.githubusercontent.com/380914/91919555-30ad0780-ec7b-11ea-99d5-1002509079e3.gif)

**Comment by ifiokjr** [comment]
Thanks for raising this. The current implementation of the `horizontalRule` seems to be particularly buggy. In the last month, the following were opened, #451 #417. 

As part of this fix I'll add some robust integration tests, to make sure changes in behaviour are flagged in CI. It's also possible it's always been broken.

**Comment by ifiokjr** [comment]
This is fixed by #641. I won't be adding the integration tests as I've decided to add a suite of integration tests against the playground once it's ready.
