### ISSUE TITLE
useEmoji with autoUpdate leads to  infinite loop

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#625]
### Summary

Use the new `useEmoji` hook in combination with `useRemirror({ autoUpdate: true });` leads to infinite loop warning.

Setting `autoUpdate` to `false` removes the infinite loop warning.

### Steps to reproduce

See sandbox: https://codesandbox.io/s/silent-sunset-qsdvy

### Expected results

I can use `useEmoji` in combintation with `autoUpdate`.

### Actual results

Warning about infinite loop in DevTools console:
![image](https://user-images.githubusercontent.com/9339055/92092629-a11a6c80-edd2-11ea-8c44-00ec9110bf47.png)

**Comment by ifiokjr** [comment]
Oh, that's nasty. I'll take a look and see if it's a general hooks issue. 

For now, if you can separate out your hook consumers from the `useRemirror({ autoUpdate: true });` things should be usable.

Something like the following should work until I get a fix together.

```tsx
import React from "react";
import { RemirrorProvider, useManager, useRemirror } from "remirror/react";
import { EmojiExtension } from "remirror/extension/emoji";
import { useEmoji } from "remirror/react/hooks";
import "./styles.css";

function Emoji() {
  const state = useEmoji();
  console.log(state);

  return null;
}

function TextEditor() {
  const { getRootProps } = useRemirror({ autoUpdate: true });
  // useEmoji();

  return <div {...getRootProps()} />;
}

export default function App() {
  const manager = useManager(() => [new EmojiExtension()]);

  return (
    <RemirrorProvider manager={manager}>
      <TextEditor />
      <Emoji />
    </RemirrorProvider>
  );
}
```

**Comment by ronnyroeller** [comment]
Thanks for feedback! We decided to pin for now to `1.0.0-next.29`, so we can keep on going without having to restructure our components. We'll upgrade once #625 is resolved.

**Comment by ifiokjr** [comment]
> We decided to pin for now to 1.0.0-next.29

Oh interesting,  were you using the `useSocialEmoji` from `@remirror/react-social`? That helps in debugging. It means it's not a fundamental issue with remirror hooks and most likely a buggy implementation.

**Comment by ronnyroeller** [comment]
> Oh interesting, were you using the useSocialEmoji from @remirror/react-social?

We used (and now again) the `MentionExtension` directly without any hooks.

**Comment by ifiokjr** [comment]
Okay, thanks for the update.

**Comment by ifiokjr** [comment]
Turns out I had a few missing `useCallbacks`. I'll merge and release soon.
