### ISSUE TITLE
Attempted import error: 'en' is not exported from 'make-plural/plurals'.

### ISSUE THREAD

**Issue by anotheri** [remirror/remirror#647]
### Summary

I've opened ticket as [we discussed](https://github.com/remirror/remirror/discussions/643).

I'm Using webpack 4 and all the latest remirror packages:

```
"remirror": "^1.0.0-next.32",
"@remirror/pm": "^1.0.0-next.32",
"@remirror/i18n": "^1.0.0-next.32",
```

And I'm getting this error on build:

```
Attempted import error: 'en' is not exported from 'make-plural/plurals'.
```

My `@ ./src/shared/remirrorProvider.js` file looks exactly like one of your basic examples
```
import React from 'react';
import { SocialEmojiComponent, SocialProvider } from 'remirror/react/social';

export const Remirror = () => {
  return (
    <SocialProvider>
      <SocialEmojiComponent />
    </SocialProvider>
  );
};
```

### Expected results

Build pass.

### Actual results

```
Creating an optimized production build...
(node:56701) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
^[Failed to compile.

./node_modules/@remirror/i18n/dist/i18n.browser.esm.js
Attempted import error: 'en' is not exported from 'make-plural/plurals'.
 @ ./node_modules/@remirror/react/dist/react.browser.esm.js
 @ ./node_modules/remirror/react/dist/remirror.browser.esm.js
 @ ./src/shared/remirrorProvider.js
```

**Comment by ifiokjr** [comment]
In the lockfile, what version of `make-plural` is installed. 

I'm looking at [unpkg](https://unpkg.com/browse/make-plural@6.2.2/plurals.js) and it's right there on [line: 213](https://unpkg.com/browse/make-plural@6.2.2/plurals.js) and in the [`mjs` file (line: 166)](https://unpkg.com/browse/make-plural@6.2.2/plurals.mjs) as well. 


I don't know whether webpack 4 is able to resolve the `exports` field yet. So it might have to do with the fact that they're using it to define the main entry points in the [`package.json`](https://unpkg.com/browse/make-plural@6.2.2/package.json) file.

But that doesn't make sense. They also have a `main`, `browser` and `module` field.

**Comment by anotheri** [comment]
```
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "make-plural"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "make-plural@6.2.2"
info Reasons this module exists
   - "@remirror#i18n" depends on it
   - Hoisted from "@remirror#i18n#make-plural"
   - Hoisted from "@remirror#i18n#@lingui#core#make-plural"
info Disk size without dependencies: "172KB"
info Disk size with unique dependencies: "172KB"
info Disk size with transitive dependencies: "172KB"
info Number of shared dependencies: 0
✨  Done in 0.91s.
```

**Comment by anotheri** [comment]
and yeah, `exports` seems the problem with webpack 4: https://github.com/webpack/webpack/issues/9509
it seems should work with webpack `v5-beta18` now.

**Comment by ifiokjr** [comment]
Do you have a reproduction environment I can look at?

I have no idea, I've just added a test here with the built code. It runs okay via the [docusaurus build](https://remirror.io/docs/showcase/social/) which is also using webpack 4 as well. 

A reproduction would make it easier to understand why it's happening.

**Comment by ifiokjr** [comment]
> it seems should work with webpack v5-beta18 now.

Okay, that's good. Are you happy to close this?

Also if you have a moment, it'd be awesome to add a note to the documentation.

I've been thinking of doing this for a while, but haven't found the time. Adding a new heading in the `docs/errors.md` file ** Build Errors**

And then a sub section titled ** Attempted import error**, with the error details as markup and a potential solution of upgrading webpack to `5-beta+`. 

It would be highly appreciated 👍

**Comment by anotheri** [comment]
I'll try to provide minimal reproduction environment today/tomorrow as well as test it with webpack v5-beta18 (or higher) and let you know then.

**Comment by anotheri** [comment]
So I've managed to update my project to latest webpack 5-beta29 but getting the same error, and here are all the details I'm getting in webpack's error:

```
$ node --max_old_space_size=4096 scripts/build.js
Creating an optimized production build...
statsJson.errors [
  {
    moduleIdentifier: './node_modules/@remirror/i18n/dist/i18n.browser.esm.js',
    moduleName: './node_modules/@remirror/i18n/dist/i18n.browser.esm.js',
    loc: '7:11-13',
    message: "export 'en' (imported as 'en') was not found in 'make-plural/plurals' (possible exports: default)",
    moduleId: null,
    moduleTrace: [ [Object], [Object], [Object], [Object] ],
    details: '    at HarmonyImportSpecifierDependency.getLinkingErrors (./node_modules/webpack/lib/dependencies/HarmonyImportDependency.js:168:8)\n' +
      '    at HarmonyImportSpecifierDependency._getErrors (./node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:175:15)\n' +
      '    at HarmonyImportSpecifierDependency.getErrors (./node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:164:16)\n' +
      '    at Compilation.reportDependencyErrorsAndWarnings (./node_modules/webpack/lib/Compilation.js:2055:22)\n' +
      '    at ./node_modules/webpack/lib/Compilation.js:1684:10\n' +
      '    at _next2 (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)\n' +
      '    at eval (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)\n' +
      '    at ./node_modules/webpack/lib/FlagDependencyExportsPlugin.js:331:11\n' +
      '    at ./node_modules/neo-async/async.js:2830:7\n' +
      '    at Object.each (./node_modules/neo-async/async.js:2850:39)',
    stack: "ModuleDependencyError: export 'en' (imported as 'en') was not found in 'make-plural/plurals' (possible exports: default)\n" +
      '    at Compilation.reportDependencyErrorsAndWarnings (./node_modules/webpack/lib/Compilation.js:2060:21)\n' +
      '    at ./node_modules/webpack/lib/Compilation.js:1684:10\n' +
      '    at _next2 (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)\n' +
      '    at eval (eval at create (./node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)\n' +
      '    at ./node_modules/webpack/lib/FlagDependencyExportsPlugin.js:331:11\n' +
      '    at ./node_modules/neo-async/async.js:2830:7\n' +
      '    at Object.each (./node_modules/neo-async/async.js:2850:39)\n' +
      '    at ./node_modules/webpack/lib/FlagDependencyExportsPlugin.js:310:18\n' +
      '    at ./node_modules/neo-async/async.js:2830:7\n' +
      '    at Object.each (./node_modules/neo-async/async.js:2850:39)'
  }
]
Failed to compile.
```

I'll try to provide reproduction environment tomorrow. Wondering if that can be b/c of plugins/loaders I use in project.

**Comment by ifiokjr** [comment]
Could create a random file in your project and try and import `make-plural/plurals`? Does it still error?

You would need to install it directly.

**Comment by anotheri** [comment]
yeah, I tried that. So if I import it like this
```
import { en } from 'make-plural/plurals';
```
it throws the same error.

if I import it like
```
import * as plurals from 'make-plural/plurals';
```
it passes build.
but once I try to use it as `plurals.en` it throws the same error again.

**Comment by anotheri** [comment]
Finally! I found it! I use `file-loader` which had `.js` files excluded but had no `.mjs` excluded, so when it imported `make-plural` it went through wrong loader. Right config looks like this now:

```
{
            loader: require.resolve('file-loader'),
            // Exclude `js` files to keep "css" loader working as it injects
            // it's runtime that would otherwise processed through "file" loader.
            // Also exclude `html` and `json` extensions so they get processed
            // by webpacks internal loaders.
            exclude: [/\.js$/, /\.mjs$/, /\.html$/, /\.json$/], // <--------- added  /\.mjs$/ here
            options: {
              name: 'static/media/[name].[hash:8].[ext]'
            }
          }
```

Thanks for all the support, and sorry for bothering not related to your module. 🙏

**Comment by ifiokjr** [comment]
Great to hear you found what was wrong! This one had me flummoxed. 

It'd be awesome, only if you have time, if you could add a little section to the docs bottom of `errors.md`. Hopefully, it saves the next person from having to go through the same amount of debugging as you did.

**Comment by ivanbanov** [comment]
@anotheri thank you so much for sharing it, I don't even use remirror but ended up finding this solution which fixed my problem while upgrading to Emotion11.

Do you have any clue while this weird thing happens?

**Comment by anotheri** [comment]
@ivanbanov well, as far as I remember that was related to the lib that used `.mjs` file format instead of `.js` (for ES Module, I guess) which broke the webpack build b/c of configuration didn't support such file format.
