### ISSUE TITLE
Selecting text causes RangeError if TablePreset is added

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#661]
### Summary

I've an editor with the `TablePreset`. I call `commands.createTable.isEnabled()` to decide if the [Create table] button should be enabled in the toolbar. When selecting content from the end of the document towards the beginning, a RangeError is thrown.

### Steps to reproduce

1. Open playground with `TablePreset` extension: https://remirror.io/playground#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIgBVWAEbM5IwKFAQi4piSMgq09DhqYeS4KriBwR4GGN5W1PHKoZgAbij85NiWZOQAsqy8rJwVVRT5SjgOUTEuigmqruZZ+giYvKQEAKIAGr4TAHIAygCSAPKL+AC8+AAUAJSbAHz4ANq85ADu+P5BIcm4ewC6erz6KgBUb-r4b1cAFiikfAjHJnXgEEZg1goMb4XC-cj4cj8FC4Dr1QT1diwzCYZgBVjYUgqBC-CQIlH4BQAR2IdHIpAAdF83iphqNxvgFmBWMxmBNkajsJAbPYtntDoQvkD2T5pWBuQJSJYmrhKDjcEV0ICRFtqm0+ntnlKVCp8ABVCiw-6A1GIho3FTI0gZBHHWyuXAI9I3B5S4EK-iMhAe8jXYIMgETe3BfiG-RShS4YjYXg7KX4fAAHmRxQO6YzWZzhAZJZVaswGoYWr2IhUedTBczjpQualu2eQiNvAhHK5PL5ApwAHVsKx0OgKpsdvsNkdgH6ZYiAB6esYoUZ1BpNbBT6qbxoVbbTWaLVaLdvxhs92XFHnEciWUa2X71JoOXWtXqFDTcTB8WPkCu5Brhu9QHtg7b4Ca+AACLkMEnpWgC+DMNC5CXhmibJqm2z5pm+qFAwpTlNg+YZgq4EbMAgGrqQ668Pu25CGR+C3sw95UWx97MQ2Bb4E+L68E0VECa+5A8Xx9Z8RmmZ9ry-Ioh0dZ4SoBFMERZQVFJ+AXrwnaXoBRgEOUoisMQzAEHJA6KdgI5jhO2DPCAQhAA
2. Enter text `12345678901234567890123456789012345678901234567890` (it must be a longer text)
3. Place cursor at the end of the text (that's important -> selecting from the beginning works)
4. Select the text to the left with the keyboard (i.e. SHIFT + ARROW-LEFT)

### Expected results

Selection works

### Actual results

Shortly before the cursor reaches the beginning of the text, the editor crashes in:
![image](https://user-images.githubusercontent.com/9339055/92362763-c5d35480-f0f0-11ea-88fc-4004cc0bc376.png)

**Comment by ronnyroeller** [comment]
See here video recording when reproducing the issue: https://discord.com/channels/726035064831344711/745695521305526302/752439043920363582

**Comment by ifiokjr** [comment]
Thanks for raising this. It looks like the code trying to resolve a position that doesn't exist. Line 86 is where it happens.

https://github.com/remirror/remirror/blob/92ed41350eb540fa9ab5de72cd90f605cdbbc7e9/packages/%40remirror/preset-table/src/table-extensions.ts#L83-L86

I need to add tests for these commands as I haven't done so yet. I'm not 100% sure why it's happening, so I'll take a look at it soon.

**Comment by ifiokjr** [comment]
Oh I see, the problem, it actually doesn't support checking whether the creating the table is enabled. It just tries and fails.
