### ISSUE TITLE
https://remirror.io/docs/guide/hello-remirror contains JavaScript that causes Firefox to hang

### ISSUE THREAD

**Issue by Jaxkr** [remirror/remirror#664]
### Summary

The social example fails to load and simply causes the browser to hang. Firefox will detect this and offer to kill the page

### Steps to reproduce

Open https://remirror.io/docs/guide/hello-remirror in the latest version of Firefox

### Expected results

The demo loads

### Actual results

The entire page freezes

### Possible Solution

There is an infinite loop somewhere that is loading a module over and over?? The page uses a lot of memory as well. I really have no idea.

**Comment by ifiokjr** [comment]
Oh thanks for raising this. The social editor has changed its API and I hadn't updated that example yet. I'll fix it later today when I push up the latest code.

**Comment by ifiokjr** [comment]
Fixed in #665 
See [**link**](https://5f57a276eb4e4631d7cebb7c--remirror.netlify.app/docs/guide/hello-remirror/)
