### ISSUE TITLE
toggleBulletList() creates ordered list

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#669]
### Summary

Calling the `toggleBulletList()` command creates an ordered instead of a bullet list under certain conditions (see minimal reproduction case below).

### Steps to reproduce

Build an editor with these 3 conditions:
- Use `autoUpdate`
- Call `toggleOrderedList.isEnabled()`, e.g. to check if toolbar button should be activated
- Call `focus()` after `toggleBulletList()`

Playground: https://remirror.io/playground#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABAEoCmAhggQGbaZj4A6I2ZFjA3PQHZpZ77BFiYFNhrYACjQBuKACbFssfAFcAzsQCypTqQDmCpWuIlhonPgC++arQZMhIsQHpm5XOy48cBAQBkUqriSxOoEVjZ0jMymzujMoU4ANgHuIBycXJTKnBQomJz4ACrEAB64AKKyKLg4ABQAlPxc+PhOTvgAwvlVuHkF0JD4GmoEofikyjUAquiypLjEzfgI+YH81pgIakr6uISYmEE06KpKK2Bg2rKqlvgAvCrqJo51AhPTs-PEg7jYysSWerpJZtTrdap9fAAJkGwzWCFIiUS+Bqul0iWIAHlsPJmLJ-IEAHQBco6ABGGNk+FqxEJukJKMw+FUAAtMAB3fBkyY1AooAo1TCJMmkbD1JbnS6ca6E1HorE4hTEfEpYmqUmkCnKhrAgr4Zi4ZTYAq1JYtAA8AD4zS18ObubheTbbfh8h1kggANZ3YANe6Wpp6l0uyVXVSyzBojEAIWUSOIuAJuB1zuDoK60oh+XwAGZYSNlojkZRNmpxpQFthGVH+bouXGMQRkmtajV8I3HgoUQBPdAA0gVhSpl2ghAez21-D8xlCkVi4e2ktbVQpoPBiwWVPWtcu2Px9w7u1OB287fBu1VKT8Qk33b7Q6STAnBpWJxn23mt9LIFcTcZTilLwBDyJQEyJFQ2S5NmACC6DoH6wASqsBBSnoXYPEYWg6Po2C1AA2gBnJJsEoQNAAuj+-4tAaRomja5rPGYEjSHIXaoThPrsQoFjvi65rFGUlTVOYX5rp+jFiI+Mi4u+lF-iAFhAA

### Expected results

Create a bullet list

### Actual results

Create an ordered list

**Comment by ifiokjr** [comment]
Ahhh good spot. It's a similar problem to the `tables` issue #663  with the `isEnabled` call mutating the transaction. Calling `toggleOrderedList.isEnabled()` in the component scope means that the list is always set as an ordered list.
