### ISSUE TITLE
Consistent `@remirror/preset-core` vs `remirror/preset/core` references

### ISSUE THREAD

**Issue by Bertg** [remirror/remirror#685]
### Description

The current code base refers to both ```@remirror/preset-core``` and ```@remirror/preset/core``` about the same amount of times. It is unclear if these are the same or what their difference is.

### Context

Trying to understand the project and starting to use it.

**Comment by ifiokjr** [comment]
All examples in readmes and the docs should point to `remirror/preset/core` while Internal code should use the scoped package directly. It's much easier to install just the `remirror` package when getting started than a load of scoped packages. 

I'm getting a PR ready now which removes the references to `@remirror/preset-core` from the readme files.
