### ISSUE TITLE
Social Plugin - If tag is last item in content, it doesn't get associated marks.

### ISSUE THREAD

**Issue by PaybackTony** [remirror/remirror#701]
### Summary

When using the prebuilt social editor and retrieving content via `getRemirrorJSON()`, if the last item in the content is a tag that was entered without using the suggestion list, that item in the content block doesn't contain the necessary `marks` making parsing the content later on more difficult.

### Steps to reproduce

Use Social Editor, enter in content `#this #that #theother`, in JS, call `getRemirrorJSON()` and notice the last item doesn't have the `marks` property when NOT using the suggestion tool. If the last tag is entered from selecting a suggestion, it is tagged properly.

### Expected results

The last item should have the `marks` property.

### Actual results

The last item doesn't have the `marks` property`.

### Possible Solution

PR

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1795806/93688502-26f91180-fa7b-11ea-9b91-47c749cab8f7.png)

Code:

```{
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "marks": [
                        {
                            "type": "mention",
                            "attrs": {
                                "role": "presentation",
                                "href": "/this",
                                "id": "this",
                                "label": "@this",
                                "name": "at"
                            }
                        }
                    ],
                    "text": "@this"
                },
                {
                    "type": "text",
                    "text": " "
                },
                {
                    "type": "text",
                    "marks": [
                        {
                            "type": "mention",
                            "attrs": {
                                "role": "presentation",
                                "href": "/that",
                                "id": "that",
                                "label": "@that",
                                "name": "at"
                            }
                        }
                    ],
                    "text": "@that"
                },
                {
                    "type": "text",
                    "text": " @theother"
                }
            ]
        }
    ]
}```

**Comment by ifiokjr** [comment]
I'll hopefully get to this later today or early tomorrow.
