### ISSUE TITLE
New package `@remirror/extension-codemirror`

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#711]
### Description

While the current code block extension works fine, it isn't a code editor. There's a lot of functionality that `codemirror` would provide for free which isn't available in the current implementation. 

- [ ] Explore work required to add a cross-platform implementation of codemirror. 

### Context

It would be great if I could jump straight to codemirror6 but, it looks like it's still a work in progress.

**Comment by ocavue** [comment]
I'm working on this.
