### ISSUE TITLE
Extract html string handling into a separate package

### ISSUE THREAD

**Issue by ifiokjr** [remirror/remirror#714]
### Description

Right now the handling of html is built into core. I want to extract it into a separate extension. This extension will add a `getHtml` method to the context. It will also allow users to set the `stringHandler` option for their editor to be `html` rather than providing a specific function.

- [x] Rename `fromHtml` to `htmlToProsemirrorNode`.
- [x] Rename `toHtml` to `prosemirrorNodeToHtml`.
- [x] Create a new extension `@remirror/extension-html` which will be included by default in the core preset.

**Comment by anotheri** [comment]
it would be nice to have a way to `insertHtml` too, e.g. if i want to have "Add placeholder" dropdown with some predefined HTML elements, like an anchor `<a href="...">...</a>`

**Comment by ifiokjr** [comment]
This is available in the beta release #706.

@anotheri could you open a new issue with this as a feature request?

> it would be nice to have a way to `insertHtml` too, e.g. if i want to have "Add placeholder" dropdown with some predefined HTML elements, like an anchor `<a href="...">...</a>`
