### ISSUE TITLE
Insert text with marks didn't work

### ISSUE THREAD

**Issue by dalladirosa** [remirror/remirror#716]
When i try to insertText with bold marks with this 
```js
commands.insertText('Hello', {
  marks: {
    // The empty object `{}` represents the attributes being added.
    bold: {},
  },
});
```

The bold marks didn't apply to hello text

**Comment by ifiokjr** [comment]
[**Playground Link**](https://remirror.io/playground#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBIgCFMzPwAogAeuOS8pCiYvA7imJIyCrT0OCrkYRFRMSoARgH8HgYY3lbUKcqMDABuKPzk2JZk5ACyrLysnA1NFOVKOHFOSYqpqq7mRfoIMaQEQQAaACpBAHIAygCSAPLr+AC8+AAUAJT7AHz4ANq85ADu+P6BoeGR0bwnALp6vPoqAFR-fT4P74RYACxQpHw0xKN14BGm8NYKEi+FwYPI+HI-BQuAG7UE7XYaMwAVyrGwpBUCDBEkxuPwCgAjsQ6ORSAA6IF-FRTGYENZgVjMZhBHF47CQGz2A4nc6EIHQ-lWLq4Sik3BVTDoUiWGFCgS6sSYBBkBwHZp9UYnb6KhS4YjYWKHRX4fAAHhx1TOrrdHtyxFweNiMVszBQCAA1ntgHK9hdgL6-X79QTOSiKHhFhlcIcAOQYkWYPOWIhC7CR0hSoj5QLVkRCITHb7J1vG02kG1Jv2Ns4ZhoEWuCQvMTDuvKB4M+2Ktz0oaqEDlL1XqzCahg6k4iFTT5Pjr27-DN-RCW28RGzfCC4Wi8U4WwxXDIm7YfZHU7xhUzi8EHNZN5tB0XSvhaFCAZ0DSHAsyzrNs6zHj837KkQ1TCsQ5CWKGYLtF05okL0IyVBo3CYHw-CHH+rwxOBwHNvgKgqPgAAi5DMOQ4RohCULhjc+h2uxjrOr67pWpUNR1A03YGhB2AxpR2S8DRDRCN2qHMOhMZqehKkzsmWE4eQMb6bwXQ6cmh57teIpiriAw7sJKiiUw4n1Ngh4IaefE3CERgEPUoisMQzACkK1l3tgD5IiiDTfCAQhAA)

Have you added the `BoldExension`? I've added a link to the implementation above and below is a screenshot of the working implementation.

![2020-09-26 14 24 41](https://user-images.githubusercontent.com/1160934/94341787-3391e280-0004-11eb-9512-aa3c8dc60253.gif)

**Comment by dalladirosa** [comment]
I don't why now it's working after I delete @remirror/core and reinstall remirror
