### ISSUE TITLE
ImageExtension: insertImage command not working

### ISSUE THREAD

**Issue by dalladirosa** [remirror/remirror#724]
### Summary
After i update remirror version to `1.0.0-next.42` ImageExtenstion not working. I will give a playground link for easier to test it

[ImageExtenstion Playground](https://remirror.io/playground/#o/N4IgtiBcCMA0IGMogJZgA4HsBOAXABMPgK4DOApgErlgrbY4AKANgIYCeA5g8QHYAm+AL74AZgzD4AOiAAC2GnQbYA9OjZceAmQG4pvNFjz5qrBLliF8AMQDCwsROkgFZ3Lv2GcBItVr0mBgA3FH5ybEsycgBZVl5WTnDIij8lHAdxTEkZBX9lFVdzDwMMbysASTAE8gBRAA9ccl5SFExeDKcAcly01XIGppa2lTRqzr0Sox98WxxyRgUKAhFMyW7FANV0RfJcFQQ58f19A+aCGoANABUagDkAZXKAeQf8AF58AAoASneAPnwAG1eOQAO74SrVeqNZqtXg-Swg8GzBQLchLH4AXQm+hUACo8fp8Hj8FcABYoUj4A6lEG8AinXCsFDNfC4MnkfDkfgoXDpOKCOLsNmYTDMABGrGwpH2ZIknN5+AUAEdiHR0QA6Il4lQnNqkAj3KrMZg1Hl87CQGz2D4-f6EInU-XTRK4Sii3ALTDoUiWGlVAS+sSYBBkBwfKKpTY-HHtJW7YjYdqfR34fAAHh5QT+qbTefT4uIuD57TatmYKAQAGs3sA7W8AcBc3m8-6BaQNSyKHhIYlPkRSNgEJBOmTiz7ICoRlVEh2+KR1KxSGSNTS1GTMHyALTQABsAAZoNAAMwAFgATABOfcAVmgAA4dwh7-wAOyiU-8fhH0QAfhQdQVuKbzYOKO4aueGrQAAZABoRvOQ7AAFJkggAASABCoisAA6gAiigTwAFY1Ow0QACL8Je0GsEWmBvKIOBVLg0GiLybwIAw6DQaCbwPru97Qcqbz3vunTCN8EwttJwahqQMbNnmQhCH8XbhAQoyJOmKiFsWbQ5nGLaZigQSEBq5muu6m5ej6PwiCoBlGSoWaOfgkn6EIsanAa+BGqwJpmryOCzPSzIgtg7xfL8DYOnG3kEP0MJDLwsTxIkEURhQqXVNgnyXDcDzPA87m8I68VWEE-nEOQlhlmScSJOGJApBsygsBw3CYHw-CfIlgxwtl6WSfgU74OR5DMLsnLspS+AViCxxxgouCJsmubplGbXBKE4SKQGOW1n1sJtIN4RCIplXMNVtaXdV52GXmdUNeQtZPbwiT3S2rlGX5AXmukDnrSom2BJgIRhNgrklZ5i39FM+BhNhxDMIaxqmv92AhUyLLhBMIBCEAA)

![](https://im3.ezgif.com/tmp/ezgif-3-b3ca62a2814b.gif)

**Comment by ifiokjr** [comment]
I've confirmed that this is happening. I'll look into what might be causing it and have a fix ready later.
