### ISSUE TITLE
Social editor appends unnecessary extra space when reselecting mention

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#752]
### Summary

Currently using `MentionExtension` alongside `useMention` and getting the same experience as the following:

![demo](https://user-images.githubusercontent.com/12195101/95892516-aca76e80-0d54-11eb-9354-fb9d1a84b585.gif)

**Comment by ifiokjr** [comment]
I see how that can be annoying. I guess it needs a check for whether the next character after the range is whitespace.

I'll add a `trailingCharacters` property (which contains all the trailing characters of the matched range within the active text block) to `prosemirror-suggest`. Then test whether `trailingCharacters` starts with a whitespace character.

```ts
command({ appendText: /^\s+/.test(trailingCharacters) ? '' : ' ' });
```
