### ISSUE TITLE
Duplication occurs when clicking between mentions

### ISSUE THREAD

**Issue by timc1** [remirror/remirror#753]
### Summary

Clicking between two mentions seems to duplicate:

![buggo](https://user-images.githubusercontent.com/12195101/95913489-50ebde00-0d72-11eb-88dd-035102d8fbbf.gif)

**Comment by ifiokjr** [comment]
That's the old documentation site. I haven't been able to replicate this in the [current version](https://remirror.io/docs/showcase/social/).

![2020-10-14 10 18 48](https://user-images.githubusercontent.com/1160934/95969536-c6a18980-0e06-11eb-9d77-c9247e5d3ab8.gif)

**Comment by ifiokjr** [comment]
I'll close but feel free to reopen if there's something I've missed.
