### ISSUE TITLE
History extension overrides keymap from yjs extension

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#772]
### Summary

- If using the yjs extension the key bindings for undo/redo are overridden by the history extension.

### Steps to reproduce

- Use the yjs extension
- Type something
- Use `cmd+z` to undo
- Use `cmd+shift+z` to redo

### Expected results

- Change is redone.

### Actual results

- Change is not redone

### Possible Solution

- Return a tuple from `createKeymap` in the yjs extension to indicate that the keymapping there should take priority?

**Comment by tommoor** [comment]
Heads up: https://github.com/remirror/remirror/actions/runs/356864978

**Comment by ifiokjr** [comment]
Thanks for the heads up. I think that's been resolved by this PR https://github.com/JasonEtco/is-sponsor-label-action/pull/15 now.

**Comment by ifiokjr** [comment]
I'm trying to replicate this and can't. By default, the `YjsExtension` has a higher priority (`ExtensionPriority.High`) so when included it should automatically take precedence.

 Is it possible that the history extension or `CorePreset` has been given a higher priority in your editor setup?

I'm creating a PR which gives the `yjs` key bindings a priority of `High` in case that helps.

**Comment by tommoor** [comment]
>  Is it possible that the history extension or CorePreset has been given a higher priority in your editor setup?

Not in this case.

As I understand it the keybindings have their own separate priority stack?

**Comment by tommoor** [comment]
Interestingly `CMD+Y` works, but `CMD+SHIFT+Z` does not – so that's an additional clue!

**Comment by ifiokjr** [comment]
> Interestingly CMD+Y works, but CMD+SHIFT+Z does not – so that's an additional clue!

Ahhh, amazing. I think that's the issue.
