### ISSUE TITLE
`useSuggester` doesn't get updated on `setContent`

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#778]
### Summary

An active suggestor doesn't get updated when the content is changed via `setContent`, leading to an inconsistent state. This happens independently if `triggerChange` is set for `setContent` or not.

### Steps to reproduce

1. Open reproduction case: https://codesandbox.io/s/hopeful-ganguly-wqbfo?file=/src/App.js
2. Enter a slash to trigger the suggestion
3. Click [Reset content] to change the content to something without a the trigger character (slash)
=> The suggestion is still active
4. Click again [Reset content]
=> Now the suggestion is no longer active

Here is a recording of the issue: https://discord.com/channels/726035064831344711/745695521305526302/776757457112006686

### Expected results

Suggestion is no longer active if the trigger character is no longer in place.

### Actual results

Suggestion stays active

**Comment by ifiokjr** [comment]
This is a tricky one. I'll keep looking into it. 

It highlights to me as well the need to switch over to running unit tests in a real browser rather than `jsdom`.

**Comment by ifiokjr** [comment]
Fixed in beta.
