### ISSUE TITLE
Escaping nodes doesn't work consistently for many node types

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#800]
Currently if you enable the code extension and enter

```
`code` text
```

and then go to the beginning of the word `code`, press the left arrow and then type the text you enter is outside (before) the code block. This is desired; however this behaviour should also apply to bold, italic, links, etc.

Similarly codeblocks handle the left/up arrow to allow you to escape and add a plain paragraph above the code block; however this should also work for other block types: blockquotes, headings, bulleted list, images, etc.

**Comment by ifiokjr** [comment]
Fixed in beta.
