### ISSUE TITLE
The prop: 'currentState' you are trying to access does not yet exist on the target.

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#814]
### Summary

Error RMR0003 with message `The prop: 'currentState' you are trying to access does not yet exist on the target.` occurs when click the editor.

### Steps to reproduce

1. Open https://codesandbox.io/s/cool-sun-j5dn6 
2. Click the editor, which is inside the green border
3. You should see the error 

( I couldn't reproduce this with https://remirror.io/playground, so I used codesandbox )

### Expected results

No error. 

### Actual results

```
The prop: 'currentState' you are trying to access does not yet exist on the target.
``` 

### Possible Solution

The `currentState` is initialized at [`RemirrorManager.onStateUpdate`](https://github.com/remirror/remirror/blob/v1.0.0-next.57/packages/%40remirror/core/src/manager/remirror-manager.ts#L717-L720), which means that `currentState` will not be present after the editor first opened. 

The [`handleClickOn`](https://github.com/remirror/remirror/blob/v1.0.0-next.57/packages/%40remirror/extension-events/src/events-extension.ts#L136) method will throw the error when visit `currentState`.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24715727/100530836-1a8af500-3232-11eb-9e75-14429fe183d4.png)

**Comment by ifiokjr** [comment]
:facepalm: Looks like I introduced this in a recent update. I'll fix and push an update, hopefully (:crossed\_fingers: ) today :smile:
