### ISSUE TITLE
 toggleBlockItem, setBlockType wipe node attrs

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#819]
### Summary

Many of the nodes in our implementation contain custom `attrs` such as `id`, for example. When using the inbuilt remirror commands such as `toggleHeading`, or it's sub command `toggleBlockItem` any custom attrs that were on the node are wiped away.

It's easy to see how this happens in the [implementation of setBlockType](https://github.com/remirror/remirror/blob/1adea88a600ea5f92f4403f6817a4acd140eb0b3/packages/%40remirror/core-utils/src/command-utils.ts#L188).

### Steps to reproduce

- use any of the `toggleX` commands such as `toggleHeading` in combination with custom attrs.

### Expected results

- `attrs` that aren't explicitly wiped are retained.

### Actual results

- `attrs` are removed from the node

### Possible Solution

I guess there's a chance that you might not consider this a bug, but it does mean that we're not able to use any of the inbuilt commands. Particularly with the `toggleX` commands I think it makes sense to retain any attrs that aren't explicitly passed an empty value.

Thoughts?

**Comment by tommoor** [comment]
See comment: https://github.com/remirror/remirror/pull/830/files#r546136283 – unfortunately this isn't resolved, but I don't seem to have the option to reopen this issue.

**Comment by tommoor** [comment]
Hey @ifiokjr – happy new year, may we reopen this issue?

**Comment by ifiokjr** [comment]
Happy new year and sure thing :smile:
