### ISSUE TITLE
Bad kerning on text selection due to <span class="selection">

### ISSUE THREAD

**Issue by benjie** [remirror/remirror#820]
### Summary

Remirror wraps selected text in `<span class="selection">` which breaks the text into multiple segments; this prevents the built in font kerning applying, which then causes later text to be moved to the right depending on what the kerning would have been at the beginning of the selection.

E.g. normally the `T` and `e` in `Te` will overlap slightly, but when we render `T<span class="selection">est</span>` the `Te` is forbidden from overlapping, so the `est` is moved to the right by a couple pixels.

### Steps to reproduce

Enter this into the playground; then slowly drag a selection from the end of the text backwards and watch the text "jitter."

```json
{
  "doc": {
    "type": "doc",
    "content": [
      {
        "type": "heading",
        "attrs": {
          "level": 1
        },
        "content": [
          {
            "type": "text",
            "text": "Test test test"
          }
        ]
      }
    ]
  },
  "playground": {
    "m": 0,
    "a": [],
    "e": [
      {
        "module": "remirror/extension/heading",
        "export": "HeadingExtension"
      }
    ],
    "p": []
  }
}
```

### Expected results

No jitter.

### Actual results

Jitter.

### Possible Solution

- remove `<span class="selection">` entirely
- disable kerning in Remirror (don't do this!)

### Screenshot(s)

![jitter](https://user-images.githubusercontent.com/129910/101017928-abc7d780-3562-11eb-802a-68199a42204a.gif)

![jitter2](https://user-images.githubusercontent.com/129910/101018522-89828980-3563-11eb-88f8-ff075792336b.gif)

**Comment by whawker** [comment]
Just my two cents, perhaps this could be fixed by allowing opt out of the built in [persistent selection extension](https://github.com/remirror/remirror/blob/next/packages/@remirror/core/src/builtins/persistent-selection-extension.ts)?

**Comment by benjie** [comment]
I feel like allowing people to opt in to it would be better; the default experience shouldn't have this issue IMO.

**Comment by ifiokjr** [comment]
Added in beta.

**Comment by yliuaaron** [comment]
@ifiokjr Would you mind giving more context on how this was fixed in beta? I saw in beta it becomes `DecorationsExtension` but it is still in built-in extensions. Thanks! 🙏
