### ISSUE TITLE
LinkExtension – Characters interpreted as markdown when pasting link

### ISSUE THREAD

**Issue by tommoor** [remirror/remirror#823]
### Summary

Pasting a link that contains valid markdown syntax causes unusually behavior, for example this link `https://www.reddit.com/r/aww/comments/k05w86/awoo_on_a_cold_day/` when pasted in the playground results in parts of the link becoming italic:

![image](https://user-images.githubusercontent.com/380914/101560565-6f3c1780-3978-11eb-9988-c78658f5020e.png)

In my own usage of remirror it actually results in an infinite loop as `getMarkRange` [here](https://github.com/remirror/remirror/blob/next/packages/@remirror/extension-link/src/link-extension.ts#L433) returns an incorrect range:

![image](https://user-images.githubusercontent.com/380914/101560765-d9ed5300-3978-11eb-9d33-0ca0b407c7ad.png)

(note that the end of the link is missing). So far I've been unable to reproduce this in the playground, but it seems like fixing the incorrect interpretation as markdown within the link would also fix the infinite loop even though it's not reproducible.

### Steps to reproduce

- Paste the link above into an editor with `LinkExtension` and `ItalicExtension`

### Expected results

- Link is not formatted

### Actual results

- Link contains italic text

**Comment by ifiokjr** [comment]
This is fixed in the `beta` version and a release should be incoming shortly. 

For the coming `beta` version. There's a new package `prosemirror-paste-rules` which manages pasting into the editor in a more controllable manner. 

This specific issue was fixed by adding `excludes: '_'` to the `LinkExtension` `createMarkSpec`.

![2021-01-08 07 27 54](https://user-images.githubusercontent.com/1160934/103989131-25b53700-5187-11eb-9003-92d7045f9133.gif)

**Comment by tommoor** [comment]
> There's a new package prosemirror-paste-rules which manages pasting into the editor in a more controllable manner. 

Is this going to need code changes in remirror usage or is one of the default included packages?

**Comment by ifiokjr** [comment]
> Is this going to need code changes in remirror usage or is one of the default included packages?

It's a default package. I've ported all the extensions which have paste rules to start using it. It was general enough for me to extract and hopefully make life easier for others, not using `remirror` as well.

For any custom extensions there's a small change in the API when using `createPasteRules` similar to the following.

```ts
import {
  ApplySchemaAttributes,
  NodeExtension,
  NodeExtensionSpec,
  NodeSpecOverride,
} from '@remirror/core';
import type { PasteRule } from '@remirror/pm/paste-rules';

export class BlockquoteExtension extends NodeExtension {
  get name() {
    return 'blockquote' as const;
  }

  createNodeSpec(extra: ApplySchemaAttributes, override: NodeSpecOverride): NodeExtensionSpec {
    return {
      content: 'block*',
      defining: true,
      draggable: false,
      ...override,
      attrs: extra.defaults(),
      parseDOM: [{ tag: 'blockquote', getAttrs: extra.parse, priority: 100 }],
      toDOM: (node) => ['blockquote', extra.dom(node), 0],
    };
  }

  createPasteRules(): PasteRule {
    return {
      type: 'node',
      nodeType: this.type,
      regexp: /^\s*>\s$/,
      startOfTextBlock: true,
    };
  }
}
```

**Comment by ifiokjr** [comment]
Fixed in beta.

**Comment by Amethystafyy282** [comment]
Sorry to bother you, @ifiokjr, but the underscore still being removed in the pasted link, is there a way to prevent that? Thank you.
