### ISSUE TITLE
Resize embeds from remirror-iframe

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#840]
### Description

The `iframe-extension` renders an iframe to embed external content like YouTube videos.

The extension should allow users to resize the iframe. Depending on the embed, this could be with fixed aspect ratio (e.g. for YouTube videos) or with flexible aspect ratio (e.g. for Miro boards).

#### Fixed aspect ratio

Notion example for horizontal only resizing (see handlebars on left/right):
![image](https://user-images.githubusercontent.com/9339055/105040305-f7c2d300-5a61-11eb-8f05-d0f378e3f4f4.png)

#### Flexible aspect ratio

Notion example for horizontal and vertical resizing (see handlebars on left/right/bottom and in corners):
![image](https://user-images.githubusercontent.com/9339055/105040483-3062ac80-5a62-11eb-8f03-5124f8f10d51.png)

**Comment by Gaaaga** [comment]
Currently working on this :)

**Comment by ronnyroeller** [comment]
Fixed by @Gaaaga via https://github.com/remirror/remirror/pull/999
