### ISSUE TITLE
Support TODO lists with checkboxes

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#854]
### Description

Users should be able to create TODO lists with checkboxes:
- (input rule) Entering `[]` in the editor should create a TODO item
- Checkboxes can be checked or unchecked by clicking on them
- Pressing enter in a TODO item should create another TODO item, similar to bullet lists. In other words, the first TODO item starts a TODO list.

Checkboxes are a common UI element and therefore likely to be used in the embedding application also outside the editor context. The checkbox extension should therefore allow to pass a render method for the checkbox. With that, the checkboxes in the editor would look the same as in the rest of the embedding application (rendering e.g. `<Checkbox />` component from a UI library like material-ui). See [this blog post](https://medium.com/collaborne-engineering/decouple-look-feel-from-remirror-extensions-87a06ad9214e) for further details.

### Inspiration

Confluence shows a placeholder for each new TODO item to guide the user on how to use it:
![image](https://user-images.githubusercontent.com/9339055/107046154-9ec79e80-67c6-11eb-9fb8-1c36228d720e.png)

### Implementation

See @ifiokjr [comment](https://discord.com/channels/726035064831344711/726035065338986528/751017020883206154) regarding a possible implementation:
_For the todo I think it would combine a CheckboxListExtension, and a CheckboxItemExtension extension. The checkbox list is the way the items would be grouped together while the checkbox item would contain the actual checkbox and content for the todo item._

**Comment by ifiokjr** [comment]
I'm excited to see this addition.

@whawker let me know if I can assist you in any way.

**Comment by ifiokjr** [comment]
If you are looking for some inspiration it might be an idea to make use of [`pretty-checkbox`](https://github.com/lokesh-coder/pretty-checkbox) for the styling and animations.

**Comment by ronnyroeller** [comment]
This has been implemented in the meantime.
