### ISSUE TITLE
Next installation completely broken

### ISSUE THREAD

**Issue by ncioj10** [remirror/remirror#855]
### Summary
We have built our approach based on the next implementation, which now completely breaks with the same imports. It is based on the emoji

social editor (which we customized).

Our current imports are:

```
    "@remirror/core": "1.0.0-next.60",
    "@remirror/extension-auto-link": "^1.0.0-next.60",
    "@remirror/pm": "1.0.0-next.60",
    "@remirror/react": "1.0.0-next.60",
    "@remirror/styles": "1.0.0-next.60",
    "remirror": "1.0.0-next.60",

```
We tried with our old 58 version and also 60.

These dependencies can't be resolved during build: 
```
[0] * @remirror/extension-auto-link in xxx
[0] * @remirror/preset-list in xxx
[0] * @remirror/react in xxx
[0] * @remirror/react-hooks in xxx
[0] * @remirror/react-hooks/use-editor-focus in xxx
[0] * remirror/core in . xxx
[0] * remirror/extension/bold in xxx
[0] * remirror/extension/italic in  xxx
[0] * remirror/extension/underline in  xxx

```
All paths point to our project files. We did not change anything else, just executed yarn install.
We are planning to upgrade to the new beta, but we need to do it slowly, this release broke our complete code base.

### Steps to reproduce

Try building a next based system.

### Expected results

A build is working.

### Actual results

Build breaks and dependencies can't be resolved anymore.

It is currently unfortunately hard for us to determine which imports we need and how to combine them, as the API seems to break even though we are mostly using old components. 
Possibly this is due to the lower level libraries that automatically pull the pr706 releases as well, which seem to have severe breaking changes.

**Comment by ncioj10** [comment]
Update: Pinning dependencies + deleting lock + cleaning cache worked finally. Hopefully helps others with the same

**Comment by ifiokjr** [comment]
Thanks for raising this @ncioj10 I'll be releasing a new `next` version which should hopefully resolve the issue.

**Comment by ifiokjr** [comment]
Closing this as pinning versions works for now.
