### ISSUE TITLE
The prop: 'previousState' you are trying to access does not yet exist on the target.

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#863]
### Summary

My remirror `beta` editor shows the error `The prop: 'previousState' you are trying to access does not yet exist on the target.` ***occasionally***. I can't find the regularity for this error.

### Steps to reproduce

Because I needed multiple refreshes to show the error, and the codesandbox take so much time to refresh, I created a local repository as replication.

```
$ git clone https://github.com/ocavue/remirror-beta-previousstate-issue.git
$ cd remirror-beta-previousstate-issue.git
$ pnpm i 
$ pnpm start 
``` 

Then open http://localhost:3000 in the browser, and repeat the following step until you can see the error:

1. refresh the page
2. input some text in the editor
3. wait for one second 

### Screenshot(s)

https://user-images.githubusercontent.com/24715727/107863565-62fc9b00-6e90-11eb-94fe-7c1330e3f5e6.mov

**Comment by ifiokjr** [comment]
@ocavue can you add the stack trace?

Also I didn't know GitHub supported video now. Good to know.

**Comment by ocavue** [comment]
stack trace from console:

<pre>
Navigated to http://localhost:3000/
log.js:24 [HMR] Waiting for update signal from WDS...
SourceCodeEditor.tsx:17 [SourceCodeEditor] Sun Feb 14 2021 07:00:51 GMT+0800 (China Standard Time)
:3000/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
Navigated to http://localhost:3000/
log.js:24 [HMR] Waiting for update signal from WDS...
SourceCodeEditor.tsx:17 [SourceCodeEditor] Sun Feb 14 2021 07:00:57 GMT+0800 (China Standard Time)
index.js:1 This is a custom error, possibly thrown by an external library.

The prop: 'previousState' you are trying to access does not yet exist on the target.

For more information visit https://remirror.io/docs/errors#rmr0003
console.<computed> @ index.js:1
RemirrorError @ remirror-core-helpers.browser.esm.js:1118
create @ remirror-core-helpers.browser.esm.js:1085
invariant @ remirror-core-helpers.browser.esm.js:1142
get @ remirror-core-helpers.browser.esm.js:1173
getBaseProps @ remirror-extension-positioner.browser.esm.js:871
hover @ remirror-extension-positioner.browser.esm.js:774
methods.<computed> @ remirror-core.browser.esm.js:476
(anonymous) @ remirror-extension-events.browser.esm.js:329
(anonymous) @ remirror-extension-events.browser.esm.js:126
(anonymous) @ input.js:79
someProp @ index.js:231
runCustomHandler @ input.js:77
view.dom.addEventListener.view.eventHandlers.<computed> @ input.js:72
createForOfIteratorHelper.js:53 Uncaught RemirrorError {errorCode: "RMR0003", url: "https://remirror.io/docs/errors#rmr0003", message: "This is a custom error, possibly thrown by an exte…ion visit https://remirror.io/docs/errors#rmr0003", name: "RemirrorError", stack: "RemirrorError: This is a custom error, possibly th…st:3000/static/js/vendors~main.chunk.js:86944:18)"}
f @ createForOfIteratorHelper.js:53
methods.<computed> @ remirror-core.browser.esm.js:488
(anonymous) @ remirror-extension-events.browser.esm.js:329
(anonymous) @ remirror-extension-events.browser.esm.js:126
(anonymous) @ input.js:79
someProp @ index.js:231
runCustomHandler @ input.js:77
view.dom.addEventListener.view.eventHandlers.<computed> @ input.js:72
:3000/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.

</pre>

stack trace from react-script:

![image](https://user-images.githubusercontent.com/24715727/107863972-06e74600-6e93-11eb-8db7-05b08b99acf1.png)

**Comment by ocavue** [comment]
Recently, GitHub allows users to upload videos in the issue directly. Since I can use `Command+Shift+5` to start a video recording on Mac, I absolutely love this feature!

Hope someday GitHub will allow me to play video in README.md too.

**Comment by ifiokjr** [comment]
The `previousState` wasn't being initialized in the `extensionStore`. The `hover` event consumed by the `PositionerExtension` relies on this data. If you hover quickly enough over the editor, before adding any content it should cause the crash in your video.

I've opened a PR which should fix this. 

Release coming soon.
