### ISSUE TITLE
`remirror@beta` doesn't work in production mode. 

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror#866]
### Summary

When running remirror `beta` in development mode, everything seems be fine. However, when I build my app into a static website for production, my app throws errors like `react-dom.production.min.js:216 TypeError: e.store.commands.forceUpdate is not a function`. 

### Steps to reproduce

*Since this issue needs to run `build` command locally, I will reuse my previous issue repo instead of create a codesandbox.*

```
$ git clone https://github.com/ocavue/remirror-beta-previousstate-issue.git
$ cd remirror-beta-previousstate-issue
$ pnpm i 
$ pnpm run start
```

Open `localhost:3000` in the browser and you can see a functional editor in development mode. We will run the editor in production mode then:

```
$ pnpm run build
$ cd ./build
$ python3 -m http.server 
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
```

I ran a python server here to serve static content on `localhost:8000`. You can use any static server to do this, no necessary python.

Open `localhost:8000` in the browser and you can see the following error:

```
react-dom.production.min.js:216 TypeError: e.store.commands.forceUpdate is not a function
    at Object.updateAttributes (remirror-core.browser.esm.js:1278)
    at Me.onSetOptions (remirror-extension-placeholder.browser.esm.js:56)
    at Me.setOptions (remirror-core.browser.esm.js:341)
    at Oe.onSetOptions (remirror-preset-react.browser.esm.js:63)
    at Oe.setOptions (remirror-core.browser.esm.js:341)
    at remirror-react-core.browser.esm.js:965
    at _l (react-dom.production.min.js:262)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Vi (react-dom.production.min.js:122)
    at Pl (react-dom.production.min.js:261)

```

  
### Possible Solution

Remirror did read the environment variable `NODE_MODE` in the codebase, which may have a relation with this issue.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24715727/107910012-7bee7480-6f94-11eb-8004-fca74a5b3202.png)

![image](https://user-images.githubusercontent.com/24715727/107909772-ee128980-6f93-11eb-88fc-9cdd9c032377.png)

**Comment by ocavue** [comment]
It seems that `extension-placeholder` requires `this.store.commands.forceUpdate` before `CommandsExtension` inject this command. Since `CommandsExtension` has `ExtensionPriority.Highest`, I don't see why this happened.

**Comment by ifiokjr** [comment]
Thanks for raising this. I'll treat it as a priority and have a fix available in the next few hours.

**Comment by ocavue** [comment]
Thank you very much.

**Comment by ifiokjr** [comment]
Woah, this was a difficult one to hunt down. It was due to this plugin https://www.npmjs.com/package/babel-plugin-annotate-pure-calls.

Basically, when used with method decorators like `@command` it marks the decorators as pure (even though they have side effects). This means the production builds with `terser` and `uglify` strip the decorators out from the final bundle. This is why the error was saying the `commands.forceUpdate` is not a function.

I'll push a fix soon, once I untangle it from my current branch.

**Comment by ocavue** [comment]
WOW. When you have time please do tell me how you found the cause of this problem. I feel like I can learn a lot from your debugging workflow.
