### ISSUE TITLE
Add configurable emoji to callouts

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#871]
### Motivation

Today, callout nodes have a semantic marker: info, warning, error, success. Depending on the type, the callout can be styled. For example, an error callout could have a red background.

We found the 4 semantic categories too limiting for many use cases - especially "info" callouts could benefit from more, context-specific sub categories (see example below).

### Proposed solution

Users should be allowed to configure an emoji/icon for the callout freely, i.e. independent of the semantic marker.

### Example use cases

In these examples, the emoji/icon conveys better the message than a simple semantic callout:
![image](https://user-images.githubusercontent.com/9339055/108831910-12d9b300-75cb-11eb-8047-76cd7ccbccd9.png)

Note: The emoji/icon allows users to create error/warning/success callouts (similar to semantic callouts):
![image](https://user-images.githubusercontent.com/9339055/108831900-0e14ff00-75cb-11eb-9897-76f37e81b376.png)

### Inspirations

In Notion.so, clicking the emoji of the callout allows users to select a custom emoji:
![image](https://user-images.githubusercontent.com/9339055/108831887-09504b00-75cb-11eb-97f3-dab46d572d80.png)

Callout Ui design comes with icons for callouts: https://dribbble.com/shots/12882818-Callout-Ui-design-Figma-React-UI-kit

**Comment by Gaaaga** [comment]
@ronnyroeller This sounds like an interesting one, is there anyone have been working on it already? Or, I could try to submit a PR to implement it.

**Comment by ronnyroeller** [comment]
@Gaaaga Sure - that would be excellent! I don't think anyone is looking into this so far.

**Comment by ronnyroeller** [comment]
Reopening this issue until we finished the review (it got auto-closed by the merge but that still lacked review by @whawker).
