### ISSUE TITLE
useSuggest returns invalid position (pr706)

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#873]
### Summary

I use a suggestor within the editor (`0.0.0-pr706.5`). When removing the character that triggers the suggestor, the view is already updated with the new content (i.e. the triggering character is gone) but `useSuggest` still returns the - now invalid position. This triggers the below error:

![image](https://user-images.githubusercontent.com/9339055/108849453-715e5b80-75e2-11eb-897d-3e468435b728.png)

### Steps to reproduce

[Note: I used `pr706.4` in codesandbox because it currently doesn't handle `pr706.5` ([details](https://discord.com/channels/726035064831344711/726035065338986528/813766312387412009)). I locally reproduced the issue also with `pr706.5`]

1. Open sandbox: https://codesandbox.io/s/remirror-pr-test-forked-nwx9n?file=/src/App.tsx
2. Enter slash sign (/)
3. Delete slash delete

https://user-images.githubusercontent.com/9339055/108850766-02820200-75e4-11eb-8c19-7c1e06ad39e3.mov

### Expected results

`useSuggest` doesn't return a match after the character was removed.

**Comment by ifiokjr** [comment]
This is strange, I'll investigate and see what's causing the issue.
