### ISSUE TITLE
Support line breaks in paragraphs (Shift + Enter)

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#896]
### Description

Typing `Enter` in a paragraph creates a new paragraph (or in a bullet list it creates a new bullet item). Typing `Shift + Enter` is currently ignored by remirror. It would be great if remirror would instead create a newline within the current paragraph when typing `Shift + Enter`, as done by other editors like Gmail, Confluence, Word.

See here a screen recording from Confluence:
https://user-images.githubusercontent.com/9339055/111747589-c44ccb00-888f-11eb-915b-b0b1b23a2d65.mov

**Comment by Gaaaga** [comment]
Hi @ronnyroeller , I found that remirror already has a extension can solving this issue. 
You could check the example code here to see if it is what you want. 
https://github.com/remirror/remirror/pull/986

**Comment by ronnyroeller** [comment]
@Gaaaga Excellent find - the `HardBreakExtension` seems to do exactly what the issue asks for.
And it clearly shows that documentation is the missing piece to make this feature consumable. So, to me extending storybook sounds like the right way forward to solve this issue.
