### ISSUE TITLE
EmojiPopupComponent is not exported from Remirror

### ISSUE THREAD

**Issue by willurmston** [remirror/remirror#902]
### Summary

We are building an editor that uses the emoji extension, and found that `EmojiPopupComponent` is exported from its own file, but not exported from the `@remirror/react-components` package. We installed Remirror via `yarn add remirror@pr706 @remirror/react@pr706`. Thanks!

**Comment by ronnyroeller** [comment]
https://github.com/remirror/remirror/pull/899 should address this issue.

**Comment by willurmston** [comment]
@ronnyroeller Ah, missed that PR. Thanks
