### ISSUE TITLE
BulletListExtension&OrderedListExtension throws error on copy&paste 

### ISSUE THREAD

**Issue by dalladirosa** [remirror/remirror#906]
### Summary
Copy-paste other code block and try to edit it
Remirror version `0.0.0-pr706.13`

### Steps to reproduce
Go to minimal reproduction case https://codesandbox.io/s/remirror-pr-000-pr70613-forked-4o43y?file=/package.json:292-306
Copy into editor 

- If you guessed right, it continues on.

- If you guessed wrong, the captain will stop, back up, and yell at you to flip the switch. Then it can restart down the other path.

### Expected results
Should not error

### Actual results
The editor throws Maximum call stack size exceeded

### Screenshot(s)
https://user-images.githubusercontent.com/29054050/113472137-19413180-948b-11eb-8002-dd2d993c2f87.mp4

**Comment by ronnyroeller** [comment]
@dalladirosa Try to upgrade to `pr706.14` which contains this fix https://github.com/remirror/remirror/commit/a88440788736e157278f4f81ce5eeec19f55703c

After upgrading your code sandbox to `pr706.14`, I can't reproduce the issue any longer: https://codesandbox.io/s/remirror-pr-000-pr70613-forked-ter9n?file=/package.json

**Comment by dalladirosa** [comment]
@ronnyroeller  Oh yeah, you right i forgot to upgrade to `pr706.14`. It's fixed in `pr706.14`
Thank you for the answer!! I will close this issue
