### ISSUE TITLE
Support files

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#907]
### Description

Users like to enrich documents with files. Some sample use cases:
- Add an image/video for illustration
- Add an Excel file with detailed calculations
- Add a PDF as reference

The files support should:
- [x] Store meta data about the file: name, size, file-type (e.g. `image/png`), url
- [x] URL field should allow for absolute and relative path (to allow the app to serve same content from different domains)
- [x] Model a file as a block node (this leads to simpler UX for editing compared to having images inline with other content)
- [x] Offer command to add a new file (that has been already uploaded to a server)
- [x] Offer command to rename a file
- [x] Offer command to delete a file
- [x] Visualize meta data of the file with option to open & download the file
- [x] This visualization should be pluggable to allow apps to use component libraries for consistent rendering. ([possible pattern](https://medium.com/collaborne-engineering/decouple-look-feel-from-remirror-extensions-87a06ad9214e))
- [ ] Allow for optional custom fields like width/height/license/etc

### Inspiration

[Notion](https://www.notion.so) visualizes meta data of files. The more menu allows to rename/delete the file:
![image](https://user-images.githubusercontent.com/9339055/113411825-0e1cd180-93b7-11eb-9560-7021ada59fe1.png)

### Related tickets

* Visual preview file (e.g. show image itself)
* Support uploading of file

### References

* Prior [discussion on media support](https://github.com/remirror/remirror/discussions/458)

**Comment by ronnyroeller** [comment]
I went through the new file extension to see if we can close this ticket. The only point I couldn't make work are the custom fields (e.g. to add width/height of an image file).
Should this already be possible? If so: how? :)

**Comment by whawker** [comment]
> The only point I couldn't make work are the custom fields (e.g. to add width/height of an image file).
Should this already be possible? If so: how? :)

@ronnyroeller This should be possible via `extraAttributes` functionality that Remirror already provides.

For instance if you wanted to show a preview of the uploaded file, you could do something like this.

```ts
new FileExtension({
  extraAttributes: {
    license: {
      default: 'MIT',
      parseDOM: (dom) => dom.getAttribute("data-license"),
      toDOM: (attrs) => ["data-license", attrs.license],
    }
  }
})
```

[Example here](https://codesandbox.io/s/jolly-aryabhata-8vzsx?file=/src/App.tsx), using a `showPreview` boolean extra attribute.
