### ISSUE TITLE
Preview files

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#908]
### Description

The basic file support (https://github.com/remirror/remirror/issues/907) visualizes only the meta data of the file. Yet, some file types allow for a more visual representation, e.g.:
- The file name of images/videos are often meaningless (`IMG_1.JPG`). The image/video itself is more descriptive.
- PDF files can have meaningful previews.

The file preview should:
- [ ] Allow rendering per file type (e.g. `image/*`, `audio/*`, `application/vnd.ms-excel`, etc.)
- [ ] Provide rendering for common file types (images and videos)
- [ ] Allow resizing of image + video previews
- [ ] Allow to add caption to image + video previews
- [ ] Offer commands as overlay (e.g. rename, delete)

### Inspiration

Confluence shows images as such. Users can resize the image with the left/right handlebars. They overlay allows a.o. to delete the image and to add a caption:
![image](https://user-images.githubusercontent.com/9339055/113412798-78cf0c80-93b9-11eb-93c7-9f93a9d3385c.png)

Confluence shows preview for PDFs:
![image](https://user-images.githubusercontent.com/9339055/113412728-50471280-93b9-11eb-9803-847d397b52e5.png)

Gmail shows a preview of embedded Word files:
![image](https://user-images.githubusercontent.com/9339055/113412666-268deb80-93b9-11eb-92bd-9aedaa663f85.png)

**Comment by whawker** [comment]
Resolved by #1031
