### ISSUE TITLE
Support uploading of files

### ISSUE THREAD

**Issue by ronnyroeller** [remirror/remirror#909]
### Description

The basic file support (https://github.com/remirror/remirror/issues/907) allows to add uploaded files to a Remirror document. The uploading itself requires as well a visual experience within Remirror.

The upload support should:
- [ ] Show a placeholder where the file can be uploaded (see inspiration below)
- [ ] Allow to select multiple files to upload
- [ ] Allow to select files to upload via drag & drop
- [ ] Show progress information while the file us uploaded
- [ ] Show error states if the file upload failed (e.g. connectivity issue, media server down)
- [ ] Offer button to cancel uploads, e.g. when uploading a 1GB video
- [ ] The visualization should be pluggable to allow apps to use component libraries for consistent rendering. ([possible pattern](https://medium.com/collaborne-engineering/decouple-look-feel-from-remirror-extensions-87a06ad9214e)). This also allows to visualize other elements, e.g. an indicator if virus scanning was successful.

### Out-of-scope

* The uploading of the file itself should be treated by the app because there are many app-specific aspects to it (e.g. to where to upload, supported upload protocols, tokens required for upload)

### Inspiration

[Notion](https://www.notion.so) adds a placeholder from which users can upload a file:
https://user-images.githubusercontent.com/9339055/113413895-f6941780-93bb-11eb-909d-f73c09277af2.mov

**Comment by whawker** [comment]
Resolved by #1031
