### ISSUE TITLE
Editable state is not immediately updated for controlled editors

### ISSUE THREAD

**Issue by rickharris** [remirror/remirror#913]
### Summary

For controlled editors with `value`, `onChange`, and `editable` props provided, if the `editable` prop changes, it does not immediately cause the `contenteditable` property in the DOM to change. This is happening both in `1.0.0-next.60` (the version we're using at Abstract) and in `0.0.0-pr706.15`.

### Steps to reproduce

I've got a reduced test case on Code Sandbox: https://codesandbox.io/s/epic-cache-k7b9x?file=/src/App.js:1132-1253

The Code Sandbox example is using `1.0.0-next.60` because I couldn't get `0.0.0-pr706.15` to compile on their platform.

Using `1.0.0-next.60`:

1. Type anything into the editor
2. Click the button to toggle the `enabled` prop to `false`
3. Click back to the editor. The editor will still focus.
4. Type in the editor. After typing one character, the editor will correct itself and no longer be editable.
5. Click the button to toggle the `enabled` prop to `true`
6. Click back to the editor. You won't be able to focus or type in the editor.
7. Triple-click the editor. For some reason the editor will correct itself on triple click and is now properly editable again.

Using `0.0.0-pr706.15`, the only difference is that the editor will fix itself after a single click, so

- After setting `editable` to `false`, click the editor once. It will focus but then immediately after unfocus and not be editable.
- After setting `editable` to `true`, click the editor once. The first click doesn't do anything visually or functional, but it enables the editor so that if you click it a second time it will focus and you can type characters.

### Expected results

> 3. Click back to the editor. The editor will still focus.

The editor shouldn't focus here, it should not be editable at this point.

> 6. Click back to the editor. You won't be able to focus or type in the editor.

The editor should be editable and focus when you click on it.

### Actual results

Covered above.

### Possible Solution

It seems like a change in the `editable` prop is not causing a re-render in this situation. If we manually cause the `value` prop to change when the `editable` prop changes, you can force the editor to update to the correct state by adding this to the Code Sandbox example:

```js
  React.useEffect(() => {
    setValue(value);
  }, [editable]);
```

But this is definitely more of a workaround than a solution.

**Comment by tommoor** [comment]
@ifiokjr this should be marked as sponsored if you can, thanks

**Comment by ifiokjr** [comment]
@tommoor will do 👍
