### ISSUE TITLE
insertHtml is not working right

### ISSUE THREAD

**Issue by laksandy** [remirror/remirror#962]
### Summary

InsertHtml is always inserting in `<p>` tag and introducing a line break because of that

### Steps to reproduce

Demo: https://codesandbox.io/s/strange-pond-lmg0j?file=/src/ReMirrorEditor.tsx

1) Initialize editor
2) Add suggest extension
3) Add onClick handler for suggest extension
4) Observe that if onClick handler uses insertHtml, it always adds in a `p` tag

### Expected results

Expecting to insert html as the input. For eg, 
_me.commands.insertHtml(`<a href=${link}>${text}</a>`, { range: change.range });_

=> expecting this to add the text in link in the same p tag
### Actual results
The above code is adding the text in a new paragraph tag

### Screenshot(s)
Demo: https://codesandbox.io/s/strange-pond-lmg0j?file=/src/ReMirrorEditor.tsx

**Comment by laksandy** [comment]
Also not sure why `target=_blank` is getting ignored

**Comment by ifiokjr** [comment]
Take a look at the fix in the #965 

You can play around with the code here: https://codesandbox.io/s/happy-bird-2847g?file=/src/ReMirrorEditor.tsx

![2021-06-17 18 35 20](https://user-images.githubusercontent.com/1160934/122447460-adf00180-cf9b-11eb-8089-e2e248bcafeb.gif).

I'll merge and release once the PR is reviewed.

**Comment by ifiokjr** [comment]
> Also not sure why `target=_blank` is getting ignored

I'll address this in a different issue #966, since it requires adding a new feature.

**Comment by laksandy** [comment]
Thanks ifiokjr for prompt response. You truly rock. 👍
