### ISSUE TITLE
Pasting links on text doesn't work properly with lists

### ISSUE THREAD

**Issue by Qweest** [remirror/remirror#977]
### Summary

When I try to past link on text in list (using link-extension and list-extension) it replaces selected text.

### Steps to reproduce

Past link in text inside some list

### Expected results

It should link the selected text and not replace it with link text, like: 
<img width="640" alt="Снимок экрана 2021-06-21 в 17 14 00" src="https://user-images.githubusercontent.com/34643993/122776789-1698f000-d2b4-11eb-874f-ead40fbea519.png">

### Actual results

It replaces the text with link text and error occurs:
<img width="1403" alt="Снимок экрана 2021-06-21 в 17 11 00" src="https://user-images.githubusercontent.com/34643993/122776314-a9855a80-d2b3-11eb-95f7-7e2ae2dcc8d7.png">

**Comment by ifiokjr** [comment]
Thanks for raising the issue. I've pushed a fix up and will merge as soon as the build passes.

**Comment by Qweest** [comment]
Thanks 🙏
